### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by tumcode** [TCA-Team/TumCampusApp#1024]
- Integration des Tum Roomfinders
- Öffnen (zumindest per Link) der moodle-Kurse
- Informationen, wer die App entwickelt hat
- Cafeteria wird mir nicht angezeigt
- Sollte auch funktionieren, wenn nicht alle Berechtigungen bei den Login über TUMonline gegeben werden. Dann werden z.B. die Noten halt nicht angezeigt.

**Comment by kordianbruck** [comment]
@tumcode danke für die Vorschläge, hier mal kurzes feedback von mir:
* Roomfinder ist bereits in der App
* Wo sollte man diese Links zu den Moodle Kursen denn einbauen?
* Informationen über die Entwickler finden sich im Menüpunkt "Über die App"
* Wo genau wird die Cafeteria nicht angezeigt?
* Funktioniert bereits ohne alle Berechtigungen zu setzen

**Comment by tumcode** [comment]
- Cafeteria sollte doch eine eigene Karte sein? Wie auf den Screenshots zu sehen ist, wird mir die Karte nicht oberhalb von TU Film angezeigt.
- Ein sinnvoller Ort für die moodle Kurse wäre z.B. eine Verlinkung unter „Lectures“
- Ich schätze die Kurs- und Klausuran-/abmeldung ist von Seiten der tumOnline-Api nicht möglich oder?
- Danke den Roomfinder hatte ich vorher nicht gesehen, weil er keine eigene Karte hat


![085b8512-6296-444a-861a-e1db1a87bd93](https://user-images.githubusercontent.com/41841593/43380321-074f8426-93d1-11e8-8721-0ba12c194b7e.png)
![8c95c45e-3e21-4d77-8cb8-2b7761312464](https://user-images.githubusercontent.com/41841593/43380323-0791ad88-93d1-11e8-9297-8cb3f6b1e208.png)

**Comment by thellmund** [comment]
@tumcode Danke für dein Feedback! 👍 

Die Cafeteria-Karte wird nur an Tagen angezeigt, an denen die Cafeterien geöffnet sind. Da dein Screenshot von Sonntagabend ist, liegt es wohl daran. 

Lass uns wissen, falls du noch weiteres Feedback hast. Du kannst es gerne auch im [iOS-Repo](http://github.com/TCA-Team/iOS) posten.

**Comment by tumcode** [comment]
@thellmund danke für deine Rückmeldung und die Erklärung bzgl der Cafeteria!

Wäre es möglich, die Kurs- und Klausuran-/abmeldung in der App zu ermöglichen? Dies wäre noch ein sehr sinnvolles Feature:)

Danke

**Comment by thellmund** [comment]
@tumcode Ich stimme dir zu. Ich bin mir allerdings nicht sicher, ob wir diese Informationen von TUMonline abfragen können. Außerdem haben wir für den Sommer bereits geplant, einige Funktionen der Android-Version auf iOS zu bringen. Deswegen werden wir deinen Vorschlag – falls überhaupt möglich – hinten anstellen müssen.

**Comment by kordianbruck** [comment]
closing this issue in favor of the issue in the correct iOS repo.
