### ISSUE TITLE
Library Books: OPAC implementation

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#11]
Integration der Bibliothek in die app. Besonders Konto Übersicht und opac Katalog

**Comment by kordianbruck** [comment]
https://f-droid.org/repository/browse/?fdfilter=opac&fdid=de.geeksfactory.opacclient

This client implements the tum. Maybe we can get something useful from their implementation

**Comment by psukys** [comment]
Related library:
 - [opacclient/libopac](https://github.com/opacapp/opacclient/blob/master/opacclient/libopac/README.md)

**Comment by kordianbruck** [comment]
Currently not do-able within any reasonable work effort. Third party library simply proxies the website.
