### ISSUE TITLE
Bad three dots settings button placement

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#1112]
The three dots interfere wirh the news feed content, esp. the TUM logo on "official" news

Also I think for the Movie card the button has assymmetrical margin...

**Comment by pfent** [comment]
![screenshot_2018-10-01-19-41-46](https://user-images.githubusercontent.com/5686284/46305735-90dc3000-c5b2-11e8-9db4-9c2266822896.png)

**Comment by thellmund** [comment]
a) I can make it semi-transparent so that you can still somewhat see the TUM logo. Not sure if that is better – see in #1111.
b) Fixed now.

**Comment by pfent** [comment]
Semi transparent seems fine.

@kordianbruck what do you think?

**Comment by kordianbruck** [comment]
@pfent think semi would look pretty sleek. I wished it would be more out of the way. So move it up and over.

**Comment by thellmund** [comment]
Closed in #1111
