### ISSUE TITLE
Three dot settings: also displayed in other activities

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#1113]
## Steps to Reproduce

1. Go to "Tickets & Events"
2. See setting dots there
3. Open issue here

## Expected Result
No dots in tickets

**Comment by thellmund** [comment]
Same behavior as `NewsCard` had forever (for long-press). Will hide options in non-MainActivity activities.

**Comment by kordianbruck** [comment]
@thellmund yes, that behavior does not make sense in NewsActivity or the Ticketsale
