### ISSUE TITLE
Profile picture placeholder missing when logged in

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#1125]
## Steps to Reproduce

1. Install App (picture placeholder visible when not logged in)
2. Log in with TUMonline (with an account without profile picture)
3. Open the navigation drawer

## Expected Result
The placeholder should be visible when the user does not have a profile picture in TUMonline

## Actual Result
Just a grey circle is shown.

![screenshot_20181007-110811](https://user-images.githubusercontent.com/16260112/46580323-df5e5400-ca22-11e8-8b6f-e6a95d823b37.png)
![screenshot_20181007-111235](https://user-images.githubusercontent.com/16260112/46580326-f00eca00-ca22-11e8-9349-5b2a3563a2b4.png)

**Comment by thellmund** [comment]
Fixed this in #1122 – please test.

**Comment by jacqueline8711** [comment]
I can confirm this is fixed, the issue can be closed after the pull request is merged :)
