### ISSUE TITLE
Navigation drawer completely white after going to Roomfinder via link

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#1126]
## Steps to Reproduce

1. Click on a location in a calendar event
2. Click on one of the suggested rooms
3. Go back to the Roomfinder with the back button in the app bar
4. Click on the back button in the app bar again

## Actual Result
A completely empty (white) navigation drawer appears

**Comment by thellmund** [comment]
Fixed this in #1122 – please test.

**Comment by jacqueline8711** [comment]
Fixed in the case of going to the Roomfinder via the calendar, still an issue when going to the Roomfinder via the Study Rooms

**Comment by thellmund** [comment]
I can’t reproduce the behavior.

**Comment by jacqueline8711** [comment]
@thellmund You're right, in the current master it doesn't happen
@pfent This happens your current PR though (#1107)

**Comment by thellmund** [comment]
I can no longer reproduce it in #1107 after pulling from `master`.

**Comment by pfent** [comment]
I can confirm this being fixed. Thanks
