### ISSUE TITLE
Room maps are not shown

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#1137]
## Steps to Reproduce

1. Search for a room in the room finder
2. Click on one of the results

## Expected Result
Map of the room location is shown (and loading indicator if loading)

## Actual Result
Image is not shown/loading (screen stays white, no loading indicators)

### Environment
* Phone: Pixel XL
* OS version: Android Pie (9)
* TUM Campus App version: v2.0-beta6
* Language: English

**Comment by pfent** [comment]
I just analyzed this:
Apparently the RoomFinder recently switched from serving PNG to GIF files...

GIF files are neither supported in Android's ImageView nor Picasso.
@kordianbruck I think we proxy all requests for Room maps on tumcabe? Could we convert the GIFs on the fly to PNGs?

**Comment by thellmund** [comment]
[Glide](https://github.com/bumptech/glide) supports GIFs. We’d need to investigate how it handles caching, but this could be a valid replacement if we can’t make this work with Picasso.

**Comment by kordianbruck** [comment]
I'd rather not go away from picasso just now. We can proxy images through our API and cache them. That is what we want to do anyway.

**Comment by xsrf** [comment]
Roomfinder maps had a blinking red dot when I first used it 13 years ago and they still have it today... I cannot remember PNG supporting animations back then, so... I call this fake news ;)

**Comment by pfent** [comment]
`curl --verbose -L https://tumcabe.in.tum.de/Api/roomfinder/room/map/01.03.031B@5603/80`

Gives HTTP 302 Found into a HTTP 308 Permanent Redirect into a HTTP 200 OK.
I'm not actually sure how to debug this any further...

**Comment by kordianbruck** [comment]
@pfent why is the redirect a problem? The correct URL for the Backend is app.tum.de - the old one leads to this first 302 redirect.

@jacqueline8711 it would be nice that you comment, if you unassign yourself, so I know there needs more interaction from somebody else.

**Comment by kordianbruck** [comment]
I'm seeing the maps in version 2.1 - did it resolve itself?

**Comment by thellmund** [comment]
It worked for me a couple days ago, but that’s no longer the case (latest commit on master branch).

**Comment by pfent** [comment]
@kordianbruck Picasso clearly reports a HTTP 504.

Wild guess: Is it possible, that Android 9 causes different headers to be sent, such that the forwarding breaks? Strict transport security or something like that?
I guess server logs would be helpful :wink:

**Comment by pfent** [comment]
Hm, I just looked at it in the network profiler and the simulator just decides to not send any request to `portal.mytum.de` after the last redirect...

**Comment by kordianbruck** [comment]
So, I've removed one redirect by actually directly redirecting the client to `https` of mytum instead of going via `http`. This seems to have resolved the issue. @pfent can you please confirm? (Beaware of caching)

**Comment by thellmund** [comment]
I can confirm that the maps are displayed now (Pixel 2 XL, Android 9.0).

**Comment by pfent** [comment]
Can also confirm: works for me!

**Comment by pfent** [comment]
@kordianbruck :see_no_evil: 
```bash
grep -rl 'http:' . | xargs sed -i 's/http:/https:/g'
```
