### ISSUE TITLE
IllegalStateException in TcaDb Migration

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#1150]
Crashlytics reports this as the No. 1 crash source at the moment:

```
Expected: TableInfo{name='Kino', columns={rating=Column{name='rating', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, link=Column{name='link', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, trailer=Column{name='trailer', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, date=Column{name='date', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, actors=Column{name='actors', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, year=Column{name='year', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, cover=Column{name='cover', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, runtime=Column{name='runtime', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, genre=Column{name='genre', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, description=Column{name='description', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, title=Column{name='title', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, id=Column{name='id', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=1}, director=Column{name='director', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, created=Column{name='created', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}}, foreignKeys=[], indices=[]} 
Found: TableInfo{name='Kino', columns={rating=Column{name='rating', type='VARCHAR', affinity='2', notNull=false, primaryKeyPosition=0}, link=Column{name='link', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, trailer=Column{name='trailer', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, date=Column{name='date', type='VARCHAR', affinity='2', notNull=false, primaryKeyPosition=0}, actors=Column{name='actors', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, year=Column{name='year', type='VARCHAR', affinity='2', notNull=false, primaryKeyPosition=0}, cover=Column{name='cover', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, runtime=Column{name='runtime', type='VARCHAR', affinity='2', notNull=false, primaryKeyPosition=0}, genre=Column{name='genre', type='VARCHAR', affinity='2', notNull=false, primaryKeyPosition=0}, description=Column{name='description', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, title=Column{name='title', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, id=Column{name='id', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=1}, director=Column{name='director', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, created=Column{name='created', type='VARCHAR', affinity='2', notNull=false, primaryKeyPosition=0}}, foreignKeys=[], indices=null}
```

Apart from some `TEXT` / `VARCHAR` mixups and some `notNull` changes, the most significant change seems to be the `id` column being an `INTEGER`.

**Comment by pfent** [comment]
The only migration handling the `Kino` table is `Migration2to3`, which does certainly not create the table with an integer ID.

This is just weird

**Comment by thellmund** [comment]
We could simply remove the migration in which this crash occurs. Then Room would fall back on a destructive migration. Not ideal, but at least it would get rid of the crash – unless you want to spend some time fixing the incorrect migration 😉

**Comment by pfent** [comment]
Hm, that might work.
I don't know which migration actually did cause the crash, but just deleting migrations 1 to 6 should also work.

DB version 6 should be about a year old, so everyone not having upgraded for over a year will fall back to destructive migrations. I couldn't care less :man_shrugging: 

@kordianbruck what do you think?

**Comment by kordianbruck** [comment]
DestructiveMigration will only trigger, if we also increase the db version. So only removing the migrations will not work. Either we recreate the DB for everyone or copy the migration again. Either way, I have no clue how this happens.

We've been in this situation before and it somehow happens, that some tables are created with the wrong type. Also I don't think its just the Kino table. The Validation simply stops after the first error.

**Comment by kordianbruck** [comment]
Hint hint: https://stackoverflow.com/a/48292920

**Comment by pfent** [comment]
> Either we recreate the DB for everyone or copy the migration again
Why for *everyone*?
I'd first only provide migrations for the newer DB versions, and see if that reduces the number of crashes.

One thing noted in the SO thread you linked is a connection to `android:allowBackup="true"`, maybe we should disable that?

**Comment by kordianbruck** [comment]
@pfent well then google won't backup our app any longer. Means that you will always have to restore any settings by hand. Surely can also do that, but I think a cleaner approach would be to rename `DATABASE_NAME` to something completely new, so that we don't have to deal with really old DBs. 

We initially tried to port the pre-room db and my suspicion is, that this is where these problems arise from.

**Comment by pfent** [comment]
> Surely can also do that, but I think a cleaner approach would be to rename DATABASE_NAME to something completely new, so that we don't have to deal with really old DBs.
Room already has a system in place about the "really old DBs". IIRC, v1 should be the "pre-room" version.
Just remove the old, maybe buggy migrations. No need to destructively migrate all users, where the migrations have worked.

**Comment by kordianbruck** [comment]
> Room already has a system in place about the "really old DBs". IIRC, v1 should be the "pre-room" version.

Yes, this was the first time we f'd up the deployment. We also didn't export the schema back then. So the current state is like really :hankey: 

>Just remove the old, maybe buggy migrations. No need to destructively migrate all users, where the migrations have worked.

I've removed all migrations, because the problem is not *one* buggy migration, but the overall state of the whole db and pre-room migrations not working correctly.

**Comment by kordianbruck** [comment]
Will revisit this, if this occurs again with 2.1 release
