### ISSUE TITLE
CalendarDetailsFragment crashes in error handling without context

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#1152]
>IllegalStateException
>Fragment CalendarDetailsFragment{d028044} not attached to a context.
>[...]CalendarDetailsFragment.handleDeleteEventError (CalendarDetailsFragment.kt:114)

`handleDeleteEventError()` should probably just swallow the exception, if the context is missing.

**Comment by thellmund** [comment]
Lifecycle-related issue, fixed in #1155.
