### ISSUE TITLE
Mensa Widget

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#12]
Show prefered caferia and food

**Comment by arash-a2k** [comment]
Done! 
The preference of the mensa is based on closest mensa to the current location: (with the help of the usage of previous development LocationManager and CafeteriaManager )

**Comment by kordianbruck** [comment]
I think I've migrated all the code into the base now, but the widget does not show in the list. Any ideas? @pfent @arash-a2k

**Comment by pfent** [comment]
:telephone_receiver: Have you tried turning it off and on again?

Works on my device. I can select the widget and put it on my homescreen.
![screenshot_20161011-230636](https://cloud.githubusercontent.com/assets/5686284/19288738/bc58561a-9007-11e6-9449-acdb15dd5d3b.png)

**Comment by kordianbruck** [comment]
Well, it does not work in the emulator, but on my phone it seems to be working. Fun times!
