### ISSUE TITLE
Mitfahrer "Light"

### ISSUE THREAD

**Issue by TCA-Team** [TCA-Team/TumCampusApp#179]
The idea would be to extend the current chat feature in that way that we are using a chat room for announcing imminent car rides (on the same day only). All messages are deleted after a few hours automatically and sorted by an id (cf. showing interest). The meeting points are predefined by us and selectable by the driver. Also the pick-up time is attached. By default these rides should be free of charge or cost-sharing only (e.g. 1-2 Euro maybe). It's not possible to chat in this room nor to contact the driver. Just simple and straight forward. Nevertheless it's possible to show interest so that other users know when it gets crowded.

e.g.
TUM Forschungscampus -> TUM Stammgelände ; Meeting point XY ; departure: 5pm 
- Max Mustermann is interested
- Susanne Mustermann is interested

TUM Weihenstephan -> TUM Fak. Informatik ; Meeting point XY ; departure: 2pm
- Ulrike Mustermann is interested

**Comment by pfent** [comment]
I just noticed that the Chair for Information Systems released an Android App for this matter: [TUMitfahrer](https://play.google.com/store/apps/details?id=de.tum.mitfahrerapp).

So probably close this issue in favor of their solution?

**Comment by kordianbruck** [comment]
No, the idea back then was, to merge the two apps or at least provide some basic capability in ours for their service.

**Comment by nilstk** [comment]
The other apps lacks popularity. I found myself NEVER a ride so far. The TCA might solve this issue and provide TMA the users. If someone is interested, feel free to contact them and to discuss the idea on how to integrate it in the TCA maybe.

**Comment by kordianbruck** [comment]
Collab requests were not pursuit.
