### ISSUE TITLE
StickyListHeadersListView getFirstVisiblePosition returns wrong value

### ISSUE THREAD

**Issue by DreierF** [TCA-Team/TumCampusApp#190]
This causes the pull to refresh act as if the list has been scroll to the top already.

**Comment by kordianbruck** [comment]
Where can I reproduce this? The description is a bit short...

**Comment by DreierF** [comment]
If you scroll down a long list with headers e.g. chatrooms and then you scroll up again there is sometimes the case that pull-to-refresh is triggered even if there are items above the top visible item. I had tracked the error down to getFirstVisiblePosition returning 0 even if the first visible item had index 2 or what so ever.

**Comment by kordianbruck** [comment]
Ok, I've played with this for a bit and it happened about once out of ten times. Even then the issue was solved by scrolling or pulling to refresh. After the refresh the list started again at the very top. I vote to close this issue and unblock the next release.

**Comment by pfent** [comment]
I tried to reproduce this, but I don't get this behavior.
Tried to test this on a Nexus 10 and a Nexus S and this does not happen.
Tried on both about 20-30 times...

You are certainly using it wrong!
