### ISSUE TITLE
MVV: Special Characters 

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#20]
Sometimes there is the error "No station found" / MVV for an existing station - Can we fix it? (I assume it's a YQL problem)

The Problem here is, that Garching Forschungszentrum is that it contains a dash instead of a space. Maybe need to send a second request with the replaced text

**Comment by pfent** [comment]
Fixed in #320. The MVV EFA implementation doesn't care about dashes
