### ISSUE TITLE
Fun feature for the chat - Quiz Bot

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#217]
The idea is to add a quiz-bot to the current chat (fun feature).
It acts like this and is based on predefined questions.

10:00 Nils: !ask
10:00 QuizBot: Who is the current president of TU Munich?
10:01 Peter: Prof. Nahab
10:03 Nils: Prof. Herrmann
10:03 Quizbot: Nils was correct and got 1 point.
10:05: Paula: !results
10:05: QuizBot: Results: Nils 1 ; Peter 0 ; Paula 0
10:09: Kordian: !highscore
10:09 Quizbot: Top 3 - Rolf 100 ; Sabine 28 ; Rudi 5

Questions might be added by users, but need to be approved by us.
e.g. !addq _Wieviel ist 1+1?_2*

There might be several other commands e.g. !restart

**Comment by kordianbruck** [comment]
@Biart95 whats your progress?

**Comment by thellmund** [comment]
The chat is barely used. We should focus on other areas.
