### ISSUE TITLE
Wear notification shows false U6 departure time 

### ISSUE THREAD

**Issue by dkarv** [TCA-Team/TumCampusApp#224]
On the latest beta, the wear notification shows "1414576964921min" as next U6 departure
Inside the app the times are displayed correct.

Devices: 
Nexus 5, CyanogenMod
Gear Live, 4.4W2

**Comment by kordianbruck** [comment]
Maybe we should do #245 first; if we reimplement the whole mvv thing. I've been error hunting for a couple hours now and could locate the exact point of malfunction...

**Comment by pfent** [comment]
@dkarv This should be fixed with the latest PR. 
Since I don't have a Wear device, I cannot confirm this myself. Feel free to reopen the issue, if this isn't fixed in the 1.3 release
