### ISSUE TITLE
Build without Google Play Service

### ISSUE THREAD

**Issue by nextl00p** [TCA-Team/TumCampusApp#226]
It can only be updated in F-Droid when you remove the Google Play Service dependency.

**Comment by kordianbruck** [comment]
@holkili what about adding the https://f-droid.org/wiki/page/Antifeatures Antifeature tag? Is that not possible?

**Comment by krt16s** [comment]
Unfortunately not. Some apps require non-free dependencies on the device, which we can flag. But play-services are pulled in at build time, which we cannot do. Sorry.

**Comment by kordianbruck** [comment]
@krt16s  are you sure? [Firefox](https://f-droid.org/wiki/page/org.mozilla.firefox) uses GMS Play Services for chrome casting and is still in f-droid?

**Comment by krt16s** [comment]
Firefox as in org.mozilla.firefox is not build from source, it's the last (full) binary left in FDroid. We provide it for legacy reasons, at least until org.mozilla.fennec_fdroid (or any other pure-floss Firefox build) is ready for primetime.

**Comment by pfent** [comment]
I just pushed branch 1.3.1-FOSS with the patchset in 396c92c3df2fa05c2d9cd9b8795f21e8b7678f92.
This removes the Google Play Service dependency, but unfortunately breaks things like chat and location services. Basic functions should work though.

I think we can push this branch to F-Droid?
Maybe even release it to the Amazon app store for the Kindle devices?

**Comment by brdvlps** [comment]
I think it would probably be better to deactivate the features that depend on gcm first (i.e. making them inaccessible for regular users) before releasing it anywhere.

**Comment by nilstk** [comment]
Yes, sounds like a plan, Ralf. 
Maybe you can even add a notification upon first run to that version that this version has a reduced functionality and that we recommend to install the other one from GPlay.

**Comment by pfent** [comment]
@brdvlps I'd like to keep the patchset as small as possible, to keep the FOSS version close to the PlayStore version.
I also don't see what things we should disable, Chat *should* work in theory (I didn't test it), just without push notifications. Location services just use the default behaviour, e.g. it doesn't use Google's WiFi positioning system.

I also wouldn't do a notification, since people usually use F-Droid / Amazon App store when they don't have access to the Google Play Store.

**Comment by TCA-Team** [comment]
@pfent  Well, the reason is sometimes that they don't want to use GPlay for privacy reasons. Nevertheless it should be underlined that they are missing the cool stuff in that case. Maybe use a card instead. Just that they are aware of it.

**Comment by kordianbruck** [comment]
As I don't see a way to maintain a separate branch without the Play services, this will be postponed until further notice.
