### ISSUE TITLE
Fourth price for Mensa meals do not get shown

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#227]
See screenshots:
![screenshot_2014-11-03-12-33-19](https://cloud.githubusercontent.com/assets/5686284/4882471/b5a0f014-6356-11e4-95e3-7b36df5420f0.png)
![screenshot_2014-11-03-12-33-35](https://cloud.githubusercontent.com/assets/5686284/4882472/b5a64e56-6356-11e4-9a74-cee6922ede53.png)

**Comment by kordianbruck** [comment]
@pfent have you noticed that this problem still exists?

**Comment by kordianbruck** [comment]
Guess thats a no. Thanks
