### ISSUE TITLE
Study rooms

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#231]
implement this somehow: https://campus.tum.de/tumonline/wbrisweb.status_mobile

more infos here: http://www.asta.tum.de/themen-projekte/lernraeume/

**Comment by brdvlps** [comment]
So ... any news about that api?

**Comment by kordianbruck** [comment]
@brdvlps I just asked about that again, but we might need to fall back to the good old fashion html parsing...

**Comment by brdvlps** [comment]
Sorry for being so quiet lately. Just a quick status update: I'm still working on this feature. It just needs some UI fixing (maybe also in other sections, we'll see) and should then be ready.
Will continue and hopefully finish my work the next weekend(s).
