### ISSUE TITLE
Room Schedule uses wrong parameter in url

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#236]
![unbenannt](https://cloud.githubusercontent.com/assets/298860/5672632/738e6ab0-9792-11e4-86fb-683d5f7ba93a.png)

room tested with: 00.08.055

**Comment by pfent** [comment]
The `undefined` value comes from the server response, i.e. compare:
http://vmbaumgarten3.informatik.tu-muenchen.de/roommaps/room/search?s=00.08.055&

The server is broken right now, so we should probably disable the Roomfinder for the next release

**Comment by kordianbruck** [comment]
I'm guessing this is fixed or obsolete as of #329
