### ISSUE TITLE
Kill-switch: stop specifc TCA versions from sending out requests

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#239]
A recent, severe problem seems to affect lots of actual or previous versions of the TCA. Unfortunately it's affecting our servers and the load is getting too high.

So far we can only kindly ask the users to update (if auto-update is disabled / usage of fdroid version etc.) via facebook maybe. In the current case an upcoming update has to be actually enforced (or the usage of the TCA blocked). 

For these (very special) cases we need an option to stop all running TCA services and block the actual usage of the TCA to force the users to update. An information message should be displayed, too. Of course, we should be able to select the affected version.

Any further ideas?

**Comment by kordianbruck** [comment]
Let's wait for the notification api which will make this a lot easier to implement on client side.

Depends on: #286, #262

**Comment by kordianbruck** [comment]
Currently we have not encountered a similar bug in a long time. The effort of implementing this is not worth it.
