### ISSUE TITLE
Chat: Multiple instances of the chat activity opened when clicking on a notification

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#244]
using the back button you should directly get back to the room list not the other chat window

**Comment by kordianbruck** [comment]
Activities are singleTop already, but still sometimes the back button does some funky stuff...

**Comment by DreierF** [comment]
Have you tried giving the pending intent a back stack argument? This way you can specify what activity opens when you close the top activity.

**Comment by kordianbruck** [comment]
Thanks yes, that was the right hint. Now when the notification is opened from anywhere in or outside of the app, it will always have the correct path back to the homescreen.

closed in https://github.com/TCA-Team/TumCampusApp/commit/35294b85ca0d78897c987d0cc48fe60ead82d552
