### ISSUE TITLE
MVV: Switch to mvv route planing

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#245]
Current mvg live thingy is not working anymore

http://efa.mvv-muenchen.de/xhr_departures?locationServerActive=1&stateless=1&type_dm=any&name_dm=1000460&useAllStops=1&useRealtime=1&limit=20&mode=direct&zope_command=enquiry%3Adepartures&itdDate=20150209&itdTime=1453

Garching hochbrück: 1000480

**Comment by pfent** [comment]
Maybe use a submodule: https://github.com/schildbach/public-transport-enabler

**Comment by kordianbruck** [comment]
@Carlinho89 @arash-a2k @enricogigantiello will work on this issue together
