### ISSUE TITLE
Calendar not working (Token set)

### ISSUE THREAD

**Issue by LittleHuba** [TCA-Team/TumCampusApp#247]
Calendar not working on Android 5.0.2 (CyanogenMod) 

Toast on retry: "Anfrage lieferte ein fehlerhaftes Ergebnis"

**Comment by DreierF** [comment]
I can confirm that it does not work on CyanogenMod.

**Comment by kordianbruck** [comment]
Currently the calender Webservice is down because of some issues @tumo. Should be back next week.

**Comment by DreierF** [comment]
The calendar is not working because of an software error in TUM Online service and will not be accessable until mid of February.
