### ISSUE TITLE
Samsung: NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#248]
User asked about this on FB, it's a known issue with appcompat v21:

https://code.google.com/p/android/issues/detail?id=78377
http://stackoverflow.com/questions/24809580/noclassdeffounderror-android-support-v7-internal-view-menu-menubuilder/26641388#26641388

**Comment by DreierF** [comment]
Bug in support-v4:21 library.
Fix: http://stackoverflow.com/questions/24809580/noclassdeffounderror-android-support-v7-internal-view-menu-menubuilder/26641388#26641388
