### ISSUE TITLE
IndexOutOfBoundsException in ChatHistoryAdapter.getItem

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#250]
A stacktrace from the newest beta indicates a missing range check in the getItem Method

relevant snippet of the stacktrace:
>java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
>at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
>at java.util.ArrayList.get(ArrayList.java:308)
>at de.tum.in.tumcampus.adapters.ChatHistoryAdapter.getItem(ChatHistoryAdapter.java:71)
>at de.tum.in.tumcampus.activities.ChatActivity.onItemLongClick(ChatActivity.java:508)

**Comment by pfent** [comment]
Looking at the relevant stacktraces shows:
All traces are like:
>Invalid index <NUM>, size is <NUM>

Is this a off-by-one error?

**Comment by kordianbruck** [comment]
Reproducable: only happens when the full history is not yet loaded, then the position is indeed one above the one requested.
