### ISSUE TITLE
StringIndexOutOfBoundsException in OpenHoursManager.getHoursByIdAsString

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#251]
The Method crashes in all versions.

this is probably due to calculating with String.indexOf() without prior checking for -1

relevant snippet of the stacktrace:
>java.lang.StringIndexOutOfBoundsException: length=0; index=2
>at java.lang.String.indexAndLength(String.java:579)
>at java.lang.String.substring(String.java:1438)
>at de.tum.in.tumcampus.models.managers.OpenHoursManager.getHoursByIdAsString(OpenHoursManager.java:105)
>at de.tum.in.tumcampus.fragments.CafeteriaDetailsSectionFragment.showMenu(CafeteriaDetailsSectionFragment.java:66)
>at de.tum.in.tumcampus.cards.CafeteriaMenuCard.getCardView(CafeteriaMenuCard.java:70)
>at de.tum.in.tumcampus.adapters.CardsAdapter.getView(CardsAdapter.java:41)

**Comment by kordianbruck** [comment]
![location_hours](https://cloud.githubusercontent.com/assets/298860/6171704/8d91fd54-b2dc-11e4-8bae-87436ce517e3.png)

We need a better parsing algo than this:
        String interval;
        if (result.startsWith("Mo-Do") && dayOfWeek <= Calendar.THURSDAY) {
            interval = result.substring(result.indexOf("Do") + 3, result.indexOf(","));
        } else {
            interval = result.substring(result.indexOf("Fr") + 3);
        }
        String[] time = interval.split("-");

**Comment by kordianbruck** [comment]
Regex testing here: http://myregexp.com/
Sample data: 
Mo-Fr 8-17
Mo-Fr 7-19
Mo-Fr 11.30-14
Mo-Fr 11-14
Mo-Fr 11-14
Mo-Fr 11-14
Mo-Fr 11-14
Mo-Fr 11-14
Mo-Fr 11-13.30
Mo-Fr 11-13.30
Mo-Fr 10.30-14.30
Mo-Do 9-21.30, Fr 9-18
Mo-Do 9-16.30, Fr 9-15.30
Mo-Do 9-16.15, Fr 9-15.15
Mo-Do 7.45-16.30, Fr 7.45-14.30
Mo-Do 7.45-16, Fr 7.45-14.30
Mo-Do 11-23.30, Fr 11-22
Mo-Do 11-14.30, Fr 11-14
Mo-Do 11-14.30, Fr 11-14
Mo-Do 11-14.30, Fr 11-13.45
Mo-Do 11-14.15, Fr 11-14
Mo-Do 11-14, Fr 11-13.45
Mo-Do 11-14, Fr 11-13.45
Mo-Do 11-14, Fr 11-13.30
Mo-Do 11-14, Fr 11-13.30
Mo-Do 11-14, Fr 11-13.30
Mo-Do 11-14, Fr 11-13.30
Mo-Do 11-14, Fr 11-13.15
Mo-Do 11-13.45, Fr 11-13.30
Mo-Do 10.30-14.30, Fr 10.30-13.45
Mo-Do 10-16, Fr 9-15

**Comment by pfent** [comment]
Maybe just create a "real" datamodel with separate weekdays?

**Comment by kordianbruck** [comment]
I've implemented a fix with a proper Regex matching. As this data comes from the database I really don't know where it originates. Best of course would be to save it in a proper table then you can directly select the day you need but I feel like this would be overkill for what it is actually used for.
