### ISSUE TITLE
Integrate TUM RoomFinder

### ISSUE THREAD

**Issue by TCA-Team** [TCA-Team/TumCampusApp#255]
The current version of the TUM RoomFinder is old and needs an update. 
The idea is to integrate certain features of that app into the TCA.

The published app "TUM RoomFinder" was removed from PlayStore on 02/19/2015. It's not working anyway anymore.

**Comment by kordianbruck** [comment]
@thomasmauerer @qa-mhesse will work together on this issue

**Comment by thomasmauerer** [comment]
done in #292
