### ISSUE TITLE
Force close due to missing location information in calendar entries

### ISSUE THREAD

**Issue by brdvlps** [TCA-Team/TumCampusApp#257]
I noticed a force close when:
* viewing a non-empty day in the calendar section
* tapping on a date of an event which appears on the main/card section

After some debugging, I found out that the reason for this is a NullPointerException. It happens when the app tries to access the location of an event with an empty location field from the local database.
From my logcat:
```
de.tum.in.tumcampus E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-1749
    Process: de.tum.in.tumcampus, PID: 30386
    java.lang.NullPointerException
            at de.tum.in.tumcampus.auxiliary.calendar.Event.generateEventFromCursor(Event.java:110)
            at de.tum.in.tumcampus.auxiliary.calendar.LoadEventsRequest.loadEvents(LoadEventsRequest.java:71)
            at de.tum.in.tumcampus.auxiliary.calendar.LoadEventsRequest.processRequest(LoadEventsRequest.java:42)
            at de.tum.in.tumcampus.auxiliary.calendar.EventLoader$LoaderThread.run(EventLoader.java:174)
```

I also had a look on the database the app uses. There weren't any dates with available location info, which is probably not the way the calendar table should look like.

Are there any other people with problems of that kind?
I'm using an OnePlus One, running CM11S (Android 4.4.4).

**Comment by pfent** [comment]
Can reproduce this with the title field being null

**Comment by pfent** [comment]
The TUMOnline calender response XML does apparently not contain a location tag anymore.

I think somebody needs to speak to the TUMOnline staff, if this is intended.

**Comment by kordianbruck** [comment]
I've written to our contact at the LRZ, maybe hes able to restore the missing tag in the response. Meanwhile thanks for the report @brdvlps and for the fix @pfent

**Comment by brdvlps** [comment]
@pfent The fix is not working for me, as the event information is fetched directly from the database. I guess these dummy values have to be used in place. (see #258 )

**Comment by pfent** [comment]
Oh, my bad, I should probably had warned you, that this does not implement correct null pointer checks, but fixes the null-entries in the database.

In order to get my fix working, you need to repopulate your database manually, aka go to Settings -> Clear Cache, since we cache the calendar entries for 5 days.
