### ISSUE TITLE
Missing Translation in Lecture Overview

### ISSUE THREAD

**Issue by woodpecker2010** [TCA-Team/TumCampusApp#260]
While using the english language in the android app, the activity displaying my chosen lectures uses non-translated text.
The word "Sommersemester" (and probably "Wintersemester" as well) is not translated, but displayed in german.
![screenshot_2015-04-14-16-04-06](https://cloud.githubusercontent.com/assets/11944529/7138401/7ab57de6-e2c0-11e4-9109-1ea67597dd2b.png)

To be checked for other languages.

**Comment by pfent** [comment]
"Sommersemester" and "Wintersemester" come directly from TUMOnline.

We should probably do this on our own in LecturesSearchRow.

**Comment by kordianbruck** [comment]
Might as well hard code a manual translation with a switch/case statement. Should we write a special translation assistance class for these kind of cases?

**Comment by pfent** [comment]
I'm looking into a ReplaceAll "Sommersemester" and "Wintersemester" with actual translated Strings

**Comment by kordianbruck** [comment]
Exactly, but I would suggest to do this in a dedicated 'translation' helper class, in case this might be needed in other places as well.

**Comment by pfent** [comment]
It's all yours ;-)
