### ISSUE TITLE
Update notifications / in-App Updates

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#262]
Notify users not using the play store when a new version is available. Automatically download the apk and offer the option to install it directly from the app.

**Comment by kordianbruck** [comment]
The latest APK can be fetched directly from github: https://api.github.com/repos/TCA-Team/TumCampusApp/releases/latest

**Comment by thellmund** [comment]
Still relevant, @kordianbruck?

**Comment by kordianbruck** [comment]
@thellmund well, the question is, if we want to let the user know of a new release for their version - what do you think?
