### ISSUE TITLE
integration of barrier-free information

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#266]
external idea by VS 
The idea is to integrated barrier-free information in the maps like restrooms for disabled persons, special entrance possibilties for them or special locations e.g. baby-change spaces.

There is an app available, which offers some information, but lacks information like entrances maybe.
https://www.vmi.ei.tum.de/publikationen/apps/vmi-diversity.html
https://play.google.com/store/apps/details?id=de.tum.ei.vmi.diversity

**Comment by pfent** [comment]
done in  #470
