### ISSUE TITLE
MVV Widget

### ISSUE THREAD

**Issue by enricogigantiello** [TCA-Team/TumCampusApp#269]
when the mvv research will be working( #245) it would be nice to introduce a widget to display needed timetables.

**Comment by kordianbruck** [comment]
@enricogigantiello please use the v14 branch when creating the PR

**Comment by Carlinho89** [comment]
Done. Pull request #293

**Comment by kordianbruck** [comment]
Done.

**Comment by mammuth** [comment]
:tada:
