### ISSUE TITLE
Next lecture card - show room

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#276]
Feedback via Mail:

"Auf der Hauptseite werden die nächsten Vorlesungstermine mit Uhrzeit 
angezeigt. Wenn hier zusätzlich noch der Raum/Hörsaal zu sehen wäre, 
müsste man den Umweg über den Kalender im täglichen Nutzen nicht nehmen."

**Comment by Biart95** [comment]
Isn't it already implemented? I suppose, the issue can be closed.
