### ISSUE TITLE
MVV card broken

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#299]
In the develop branch, clicking on the MVV cards yields no information of the station, but selecting it from the MVVActivity does.

Broken MVV Card
![screenshot from 2015-07-20 11-33-05](https://cloud.githubusercontent.com/assets/5686284/8773273/4124fdf4-2ed3-11e5-9208-3c631fb50951.png)

Blank screen without any error / reasoning
![screenshot from 2015-07-20 11-33-15](https://cloud.githubusercontent.com/assets/5686284/8773276/412b62c0-2ed3-11e5-9535-2a9686524a16.png)

MVV Activity works
![screenshot from 2015-07-20 11-33-42](https://cloud.githubusercontent.com/assets/5686284/8773275/412aba1e-2ed3-11e5-9c9b-99c7c6dbf2e1.png)
![screenshot from 2015-07-20 11-33-44](https://cloud.githubusercontent.com/assets/5686284/8773274/412912c2-2ed3-11e5-9657-ff1f58411dd6.png)

**Comment by ibhh** [comment]
Can the reason be, that an empty list is returned if an error occurs?
See https://github.com/TCA-Team/TumCampusApp/commit/a9ffe9572872ec1fc9b4905c0d47fe6f209c74bd

**Comment by arash-a2k** [comment]
The reason is thaz the mvv card is connected to the old mvv activity i
assume! Called transportation activity! I think it should be changed to
have a connection to mvv activity
Transportation activity is not needed anymore
