### ISSUE TITLE
No room information in Calender

### ISSUE THREAD

**Issue by thomasmauerer** [TCA-Team/TumCampusApp#300]
When you click on a calender entry, the app crashes because the RoomFinder class receives an empty intent with no information about the room.
Look in the sqlite db. The location in calender table is always empty.

**Comment by pfent** [comment]
see #257
probably needs some more null checks

**Comment by thomasmauerer** [comment]
Sorry, I did not recognize there was already an issue about this. Null checks will prevent the app from crashing but will not solve the problem that no map is shown...

as described in #257 : Did you get an answer from LRZ?

**Comment by DerGenaue** [comment]
Just to make sure it won't be forgotten:
Is there any progress?

(Just checked: the location tag is still missing)

**Comment by pfent** [comment]
I believe @kordianbruck was in contact with the TUMOnline staff...

**Comment by kordianbruck** [comment]
Yes, we have a solution and it most probably will be ported to the main system this/next week.

**Comment by shookees** [comment]
Will the fix go online any time soon?

**Comment by kordianbruck** [comment]
There is currently a problem with the fix as it would change the returned api parameters. The LRZ is working on it.

**Comment by kordianbruck** [comment]
Update from the LRZ: an update was made to the APIs so that we now have the room information back.
