### ISSUE TITLE
Integrate entrance solution

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#303]
From last semester we have a excellent entrance solution which is already working. 

Some things need to happen so we can integrate this with the TCA and our PKI:
- [ ] Find smaller devices which we can use in the doors more easily. Current solution is really bulky
- [x] Simplify the setup process in the TCA #302
- [ ] Integrate the GetInTum Token Setup 
- [ ] Integrate the NFC Component into the TCA

**Comment by thellmund** [comment]
Still relevant, @kordianbruck?

**Comment by kordianbruck** [comment]
Not for now. StudiTUM actually will use the StudentCard for Access Control
