### ISSUE TITLE
Usage of translation APIs for external (German) inputs

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#307]
While the TCA supports English etc. , there is no solution for external inputs (Mensen etc.) and results are shown in German instead. Maybe we can integrate/use a free translation service to provide international users the corresponding translation here.

**Comment by kordianbruck** [comment]
Offered by Google Translate: https://thenextweb.com/google/2016/07/07/googles-now-tap-can-translate-text-android-screen/
