### ISSUE TITLE
Use Eduroam AccessPoint-IDs as "low quality positioning system" / Indoor navigation

### ISSUE THREAD

**Issue by DerGenaue** [TCA-Team/TumCampusApp#313]
The idea would be to gather data about room / wifi-access-points - correlation (on a server) to determine (on phone) when someone is e.g. leaving early and improve silence service.
see also #285

**Data gathering:**
- Integrated into some service
- When person probably is in a certain room (only 1 current lecture; midway; requires #300 to be solved), gather Wifi-Data of selected Networks
- Send Room ID and Wifi-Data to Server

**Server-Side:**
- Maintain a Table of Room IDs and Access-point-strengths plus input time
- Calculate Average of the _latest_ Data => Get Typically Receivable Access-points per Room (_TRA_)
- Provide API to upload Data and get the TRAs for a room

**Data usage:**
- When user should currently be at a certain room, get TRAs for this room from server
- Compare list to actual situation
- If correlation is small, assume user is not attending lecture; deactivate silence-mode

Some thoughts:
- Selected Networks would only include _eduroam_, _lrz_, etc... to improve privacy
- actual comparison on phone => improve privacy
- wrong data should not influence the average TRAs
- as old data gets dropped, any changes to the network should be reflected by the network pretty quickly
- the usual wifi outage could be problematic

What do you guys think?

**Comment by kordianbruck** [comment]
Ok, so it won't work with only the SSIDs but rather you would need to gather the MAC IDs of the Access Points, then you can correlate that to an approximate position. Privacy is a big concern but comparison on the phone would create a lot of unneeded traffic. 

I am kinda lacking the use case for this kind of thing. We currently use the coarse location, which uses the cellular network and is much less error prone. I don't think that this single use case really justifies this amount of work which would be needed. Nice idea though, if we combine it with #285...

**Comment by DerGenaue** [comment]
I just tested this, I can easily get the BSSIDs (which is equal to MACs) even back down on Android 2.0.

I think there will be almost no traffic as only maybe once in a lecture a data-update is pushed to the server and once per lecture a TRA-request is send for the room. (gets cached).

This idea only uses the data to determine whether a user is in a certain room; not to locate him on a map.
(Maybe the title is a bit misleading)

**Comment by DerGenaue** [comment]
I think it wouldn't be that much work.
Yes, there is a server-side backend involved but most of it is just basic filtering.
So although there are no implementations to build upon (in this app) I think that e.g. the Integration of the roomfinder was more work

**Comment by kordianbruck** [comment]
Alright, you want to suggest the API calls and the data structure (json) then I will implement the server side right away...

**Comment by DerGenaue** [comment]
I would suggest a sql-table containing id (primary, auto_increment); ROOM_ID (whatever the room-ids from tumOnline are like); SSID (Varchar); BSSID (varchar); strength (float)

some sort of pushData?roomId=[id]&signals=[signals]
where [signals] is just a CSV of [SSID]/[BSSID]/[strength];[SSID]/[BSSID]/[strength];[SSID]/[BSSID]/[strength];

and some sort of getTRAs?roomId=[id]
which would just perform something like (pseudo-sql)
`SELECT ssid, bssid, SUM(strength) AS prio FROM table WHERE roomId = "[id]" LIMIT 1000 GROUP BY bssid ORDER BY prio ASC LIMIT 10`
(i've got no idea whether this works but the idea would be to take the 1000 most recent entries for our room; group them by their bssid, add up the strengths and output the 10 strongest ones. This is the part that "averages out" the wrong data)

Does this make sense to you?
In this case, the output would just be a simple csv, but that can be changed easily to json or whatever.

I would probably do most of the stuff in the silence service.
This would mean that when a lecture gets "important" to the silence service, it requests the data and caches it. After that it would simply compare the current list of networks to the cached one

**Comment by kordianbruck** [comment]
As mentioned in #353 we can use this to also provide some indoor navigation help.

**Comment by kordianbruck** [comment]
We are talking to https://www.navvis.com/ in order to use their SDK to navigate inside of TUM. We recently ran a test and it is much harder than it seems. GPS can not be used indoors and WiFi is super inaccurate. This would need a previous scan of all the wifi hotspots and its rather out of the scope of this app.

We can surely go about this in a separate project if anyone feels motivated.
