### ISSUE TITLE
Study Plans: error 404

### ISSUE THREAD

**Issue by eidens** [TCA-Team/TumCampusApp#335]
using version 1.2.5, downloaded from Play Store.

left sidebar menu -> Study Plans -> click on one of these:
* "Bioinformatik"
* "Bioinformatik WS0708"
* "Informatik"

these 3 show error 404, all others are fine.

**Comment by eidens** [comment]
The curricula-API returns invalid URLs.

Currently:
* "Bioinformatik": https://www.in.tum.de/fuer-studierende/master-studiengaenge/bioinformatik/studienplan/ws-20072008.html
* "Bioinformatik WS0708": https://www.in.tum.de/fuer-studierende/bachelor-studiengaenge/bioinformatik/studienplan/ws-20072008.html
* "Informatik": https://www.in.tum.de/fuer-studierende/master-studiengaenge/informatik/studienplan/fpo-2007-und-fpso-2012.html

Correct links (no guarantees):
* "Bioinformatik": https://www.in.tum.de/fuer-studierende/master-studiengaenge/bioinformatik/pruefungsordnung-modulkatalog/fpso-2013.html
* "Bioinformatik WS0708": ?
* "Informatik": https://www.in.tum.de/fuer-studierende/master-studiengaenge/informatik/studienplan/fpo-2007-und-fpsos-seit-2012.html

**Comment by pfent** [comment]
We are updating these curricula from the [tumcabe API](https://tumcabe.in.tum.de/Api/curricula) asynchronously.

@kordianbruck can you update those? I suspect I would need access to the tumcabe database ;-)
```
$ grep -r curricula
App/Modules/Api/Main.php:        $this->core->router->get($p . '/curricula/?', array($this, 'curricula'));
App/Modules/Api/Main.php:    public static function curricula() {
App/Modules/Api/Main.php:        return Core::$instance->db->prepare('SELECT curriculum,category,name,url FROM curricula ORDER BY name ASC')->execute()->fetchAll();
```


@eidens you won't see immediate changes in the App, since we have a cache validity of 1 month for the curricula.
You can still go to ```Settings -> Clear data``` to force the app to update the curricula once we fixed this issue, if you don't like waiting

**Comment by kordianbruck** [comment]
I removed the old Bioinformatik, by now anyone from 0708 should have graduated.
The link for Informatik master I updated but it is actually the same which was already in the database.
