### ISSUE TITLE
Update MVV/MVG Plans

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#336]
From following [Google Play review](https://play.google.com/store/apps/details?id=de.tum.in.tumcampus&reviewId=Z3A6QU9xcFRPRmJlUHN4V3JEdzMzVHMzNy1yZU1GY3Y4WHlLc1o3NTJxRTRDRjl2MDlVMjV5Rl9RSjVUNGpQWl9jaGZqQlBDc2dsMFVRcU1oS3A1UGFleGc):

The current MVV / MVG plans are from 2013 and outdated. We should update them to the latest versions. Maybe we can even fetch the latest version from https://www.mvg.de/ ?

**Comment by kordianbruck** [comment]
So by Plans you mean the maps and not the plans which show when a bus leaves, right?

**Comment by pfent** [comment]
Plans, like in German "Netzpläne", compare [this](https://www.mvg.de/dam/mvg/plaene/liniennetzplaene/schnellbahnnetzplan.pdf)
