### ISSUE TITLE
iOS Version

### ISSUE THREAD

**Issue by mathiasquintero** [TCA-Team/TumCampusApp#342]
I really think we should work on an iOS version! I can start but would like to know who wants to be a part of it. Plus I'm not sure of everything this app does, so I need someone to tell me everything before I start coding...

Who's with me?

**Comment by kordianbruck** [comment]
The major problem is, that we don't have an Developer License or a Mac to work on. I would be happy to work on a iOS version. Meaning that we have no means to bring the app to the store.

If you just need support with the APIs and stuff I can surely help you. Want me to create a separate repository for iOS so you can start?

**Comment by mathiasquintero** [comment]
Yeah! I have no problem. I'm really looking more for support, since I think it's a project that will require more than one person. I do have a mac and can run everything on my device for now. As for licensing, perhaps we can look into it sometime later.

**Comment by kordianbruck** [comment]
See https://github.com/TCA-Team/iOS

Any other collaborators please let me know, I can add you.

**Comment by mathiasquintero** [comment]
Thanks. Let me take a look at this app to have an idea on how to port it...

**Comment by mammuth** [comment]
@kordianbruck, I currently don't have the time spending a big amount of
time in properly learning how iOS works.

**Comment by kordianbruck** [comment]
"how iOS works" - it doesn't.

**Comment by nilstk** [comment]
Instead of developing a separated version for single OS you might want to think about developing a platform-independent version in parallel. I guess it requires too much efforts to port the whole TCA to a such a solution now (assuming some limitations and different programming in general), but you might create a light version of the TCA this way with the most interesting features that may be available to iOS, Windows and even Android itself again.

A popular tool for this purpose might be Codename One as suggested in one of our research works.
http://www.os.in.tum.de/fileadmin/w00bdp/www/Lehre/Abschlussarbeiten/Mahlert-Masterarbeit.pdf
Link to the tool: http://www.codenameone.com/

**Comment by mathiasquintero** [comment]
We would have to port most of it anyway. And I'm guessing this tool probably like most of the other tools comes with a drop in performance...

**Comment by nilstk** [comment]
No, it performs even better than iOS' own objective-C with the further advantage to provide TCA to Windows phones, too. In addition CN1 uses Java and most code may be ported easily. A huge German company decided to use CN1 to provide its apps to all platforms. CN1 is not comparable with anything you might know and even allows the development of iOS Apps on Windows PCs, while compiling everything in the cloud..

From their FAQ:
"Codename One is fast. Simple benchmarks show it beating Objective-C and approaching C performance on iOS on other platforms Codename One uses the native VM where possible to achieve similar results. Graphics rendering is implemented with the gaming API's (e.g. OpenGL) hence providing game like performance. In the new Codename One VM we also implemented a non-blocking concurrent GC which completely eliminates any GC stalls", Ref. http://www.codenameone.com/faq.html

Further details:
http://codenameone.blogspot.co.il/2012/12/codename-one-benchmarked-with-amazing.html

**Comment by kordianbruck** [comment]
@nilstk I don't think that is a real option. I've just played around with the basic Poker Demo and Netbeans. They limit the free accounts to 1MB in Size. Currently the TCA has 10MB and thats with all the Progruad optimizations in place. The poker demo project is only 300 LOC plus graphis, so I guess the total size of all elements counts. Altogether its a nice concept, the pricing is just insane and there are no opensource/academic licences. 

(The simulator is kinda not really working nicely on linux...)

**Comment by nilstk** [comment]
Thanks for the input. I was not aware of a build-size limit here. The student (doing his master's thesis) was amazed by this tool, but used the enterprise license. Well, the free version is obviously not sufficient for our purposes then. That't too bad. Unfortunately even the basic license is too expensive. In general we have no interest in supporting iOS or Windows (cf. Android Praktikum) and won't be able to fund it. That's up to other TUM divisions like "iOS Praktikum" maybe. I'd suggest to contact them. On the one hand they have the students to fulfull the tasks and probably the required tools/licenses, too. Both OSs have a market share of about 10-13% right now. Therefore I'd still suggest the platform-independent way to support both of them (cf. http://www.statista.com/statistics/461959/smartphone-os-sales-volume-share-germany/ ).

**Comment by mathiasquintero** [comment]
@nilstk I was part of the iOS Praktikum last semester. And I'm still technically part of the Development team since they haven't shut down my account yet. And I'm looking into some friends who can help me with this. But I wouldn't go with a Platform independent version. I've tried some and they're way too buggy.

**Comment by kordianbruck** [comment]
@mathiasquintero alrighty. Everything else can be discussed in the other repository. Closing this for now.

**Comment by nilstk** [comment]
Okay, the newest update here:
Codename One offers us a special discount with 50% off their regular license fees. The ITSZ would be interested in a ported version for Windows and iOS devices. Therefore they would be able to fund it.
Nevertheless there needs to be someone, who is interested in porting the app using Codename One within a year. In theory this might be a nice job for a master's thesis. Unfortunately we don't have any free resources to supervise it right now and I need to focus on my dissertation. If you are interested, please try to find a supervisor first and contact the TCA Management afterwards.

**Comment by nilstk** [comment]
side-note: one of the most important features to be ported might be the alarming function that we will roll out to all Android devices by December 2015. If there is anyone, who likes to develop a minimal TCA version supporting that feature for iOS or Windows Phone asap, we would highly appreciate your support here. My recommendation would be to include 1-2 fancy features of the current TCA in that ported version already, too. The main goal is to get the alarming function to these devices asap and migrate the whole app over time. Again, a platform independent approach as presented above is preferred.

**Comment by mathiasquintero** [comment]
@nilstk I'm sort of short on time. I think I can more or less start but we still have a problem concerning deployment. Are there any specific features you'd like me to port first. And what version of the sdk is needed for the Android, version. I still can't run it in the simulator to see what I have to port

**Comment by pfent** [comment]
@mathiasquintero minSDK for the Android version is 10. So that's Android 2.3.3. The Android app should work on pretty much any emulator you can get your hands on.

If you just want to try the app, I'd suggest you install Chrome with the [ARCWelder](https://chrome.google.com/webstore/detail/arc-welder/emfinbmielocnlhgmfkkmkngdoccbadn) extension.
Within ARCWelder, you can then add the [latest release APK](https://github.com/TCA-Team/TumCampusApp/releases/download/1.3.2/app-release.apk):
![screenshot from 2015-12-01 15-16-47](https://cloud.githubusercontent.com/assets/5686284/11503060/cf94016e-983e-11e5-89ad-329ae7d7ca0f.png)

You then should be able to start the App within the Chrome Android Runtime with almost native performanc.
![screenshot from 2015-12-01 15-19-13](https://cloud.githubusercontent.com/assets/5686284/11503110/ff89a14e-983e-11e5-870e-8e10723da877.png)

**Comment by mathiasquintero** [comment]
@pfent  Thanks! I was just trying exactly that, but didn't find the latest apk.

**Comment by mathiasquintero** [comment]
@pfent @nilstk @kordianbruck for this I would need someone to explain me the Architecture (I sort of get the idea by looking at it but it's not clear if you're not familiar with the Android SDK) Most importantly on how you connect to TumOnline. I see some implementation of an SQLite DB but seems to run locally, or am I wrong? Perhaps someone can meet me this week and walk me through the API's?

**Comment by pfent** [comment]
You can pretty much ignore all the SQL stuff, that's mainly for local caching. We also have to initially fetch the data from remote.

For the connection to TumOnline, you probably want to have a look at the [tumonline package](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampus/tumonline/), esp. the [TumOnlineRequest](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampus/tumonline/TUMOnlineRequest.java). Mapping to the various Models is being done in [TUMOnlineConst](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampus/tumonline/TUMOnlineConst.java) and these Models are located in the [models package](https://github.com/TCA-Team/TumCampusApp/tree/master/app/src/main/java/de/tum/in/tumcampus/models)

**Comment by nilstk** [comment]
@mathiasquintero 
I posted the following link on our facebook page a few days ago. It's probably perfect to get an impression on the app and may even allow the usage on desktop computers or IPhones for demo purposes (wlan required) - https://appetize.io/app/h6ywavgfgye3ukcke6nnhc7juc
On your desktop computer you may use emulators like Bluestacks to try out the app. The preferred way might be to use Android Studio, download the source and use their emulator or a connected device.

Thinking about the architecture you may want to talk to @pfent for general questions and @kordianbruck  for the alarming feature. Unfortunately there is no documentation for current versions anymore. You may want to provide us your questions so that we can follow up creating the documentation for future developers, too.  (cf. https://github.com/TCA-Team/TumCampusApp/issues/347  )

**Comment by nilstk** [comment]
@mathiasquintero any news here? What's your newest status? 

Right now one of your fellow students might be interested in this porting task (independent approach). In general that topic is available for anyone looking for a bachelor's thesis or master's thesis starting in February.

**Comment by mathiasquintero** [comment]
@nilstk I'm still working on it. Haven't done much since the new year. But it is working. It already has cards and separate views for the cafeterias, the TU Film, lectures, search, people, calendar, rooms and tuition fees.
![img_7297](https://cloud.githubusercontent.com/assets/13184158/12377760/db734292-bd28-11e5-8c06-e600e102514b.PNG)

For the code check out the repository: https://github.com/TCA-Team/iOS
Although all the files are in one folder, the project is a bit better organised, trust me :D

**Comment by kordianbruck** [comment]
I think we should be able to publish a first version beginning of next semester.  Would be nice to already have the alarm/notification system going by then - is that reasonable? @mathiasquintero 

@nilstk have you heard back from the people from the iOS practical course?

**Comment by nilstk** [comment]
@kordianbruck  No.
@mathiasquintero  Good job. Great progress anyway. If you are ready to release an alpha version, please get back to me and we will forward it to the ITSZ for assistance and release (Dev-Account). It would be preferred to include the alarming feature, too.

Also I will keep you posted on our cross-platform approach. Again, it's an official possibility for a bachelor's- (preferred) or even master's thesis. The topic is available and not reserved (yet).

**Comment by mathiasquintero** [comment]
@nilstk would you prefer if I contact the guys from the Practical Course. I will be working with them next semester anyway. But I'm not sure if they can publish, though...
@kordianbruck I do think I can have that by then. It might still be buggy, but it should. 
Can you send me a few screenshots of how it looks? Since I haven't been able to use it in the simulator

**Comment by kordianbruck** [comment]
Sure, I'll open up an issue in the iOS project

**Comment by kordianbruck** [comment]
@mathiasquintero Sure, I'll open up an issue in the iOS project

We have already talked to them about this and they said it would be possible. But I'm not sure if it is the best option as they are hard to reach sometimes... We really need someone who has an interest in this project and is willing to invest some time into going through the publishing route - also we need to assure that the fee is paid for lets say the next five years.

**Comment by nilstk** [comment]
For information: We will proceed with the idea of a platform independent approach using Codename One starting in Februar 2016. In theory the result would be the same codebase for an Android-, iOS- and Windows-App as well as native apps for all three platforms. Depending on the results (future benchmarks) we can decide weather current native approaches should be continued or the CN1 approach (cf. costs). Therefore @kordianbruck @pfent may continue on the Android branch as well as @mathiasquintero  on the iOS version for the moment as usual, too. It would be interesting to compare them in the end to our platform-independent app. A great benefit is that we can bring our app to desktop computers this way, too.

**Comment by TCA-Team** [comment]
@mathiasquintero for information: https://apps.wiki.tum.de/file/view/Apple_iOS_Developer_Program_Ablauf.pdf/388855284/Apple_iOS_Developer_Program_Ablauf.pdf

**Comment by mathiasquintero** [comment]
@TCA-Team Perfect!

**Comment by kordianbruck** [comment]
@mathiasquintero we are working right now to setup a system on how to sign and publish the app via the ITSZ (like in the manual). @pfent got something going for that, so no need for you to go through the troubles :+1:

**Comment by mathiasquintero** [comment]
@pfent Sounds great! Sounds like a great Continous Delivery Idea. If you want any help, just ask...
But you know, after the exams... :D

**Comment by nilstk** [comment]
Especially after the bachelor's theses ;-) ...

**Comment by nilstk** [comment]
@mathiasquintero any news regarding your version? We completed a reduced version using CN1 and will publish that one soon. Nevertheless, please feel free to publish your version as well, if it provides more options maybe. Our main goal is and was to bring the alarm feature to iOS as well as basic TCA functions. Everything else is up to future development and ultimately to the results presented by Gabriel when thinking about using CN for developing purposes. From the current point of view, we will stick to the native versions probably and do not replace it by CN1 in general.

**Comment by mathiasquintero** [comment]
@nilstk I haven't had any time this entire semester. But I would really like to get something working soon. Let me see if I can get some help... Perhaps if you could tell me what core functionality you want implemented first?

**Comment by nilstk** [comment]
Well, including the alarming feature might be reasonable and quite important maybe. All other features are nice, but less important. Furthermore Kordian has statistics on most used features. You probably want to review our upcoming July release to make decisions or you just pick the ones you prefer.

@kordianbruck please comment statistics

**Comment by kordianbruck** [comment]
@mathiasquintero throughout the current stats I have, the most important things are the following: notification API / GCM, Mensa, Vorlesungen & Nächste Vorlesung, Studibeitrag.

Things like the TU Kino are popular, but not required in any way for a first release.

**Comment by kordianbruck** [comment]
Closing this issue, as we can discuss anything else in the other repo.
