### ISSUE TITLE
Check bug reporting

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#343]
Since 1.3.X no bug reports were reported back to our system. Check why this happens and release fix asap.

**Comment by pfent** [comment]
probably related to the networking changes from #305…

**Comment by pfent** [comment]
hm, debugging the ExceptionHandler.submitStackTraces() gives me a weird Exception trying to establish the connection:

javax.net.ssl.SSLHandshakeException: Handshake failed
SSL handshake aborted: ssl=0xaec37600: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xaba61c4d:0x00000000)

Why is it using SSLv3 here?

**Comment by pfent** [comment]
HTTP request seemed to work fine…
We might have a SSL configuration mismatch here

**Comment by pfent** [comment]
when using OkHttp I'm getting:
```
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xaec39200: Failure in SSL library, usually a protocol error
SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert inappropriate fallback (external/openssl/ssl/s23_clnt.c:770 0xaba61c4d:0x00000000)
     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
	 ... 21 more
```

**Comment by kordianbruck** [comment]
SSLv3 is deactivated on the server. It should at least use TLSv1.0

Check https://www.ssllabs.com/ssltest/analyze.html?d=tumcabe.in.tum.de&latest

**Comment by pfent** [comment]
Can we somehow verify, that we now receive these bug reports?

Plus we should somehow handle, that if the ExceptionHandler fails to submit the stacktraces, it tries to resubmit then.

**Comment by nilstk** [comment]
Yes, just add a debug function somewhere hidden in the menu of the TCA that divides by zero, which will crash the app and should trigger such a report.

**Comment by kordianbruck** [comment]
@pfent try to access the toString of a null string somewhere. On next startup the bugreport will be transmitted and should showup in the UI. Worked for me when I tested it.

Yeah we could save the reports for later, we just need to make sure, that we don't flood the storage space with those reports.
