### ISSUE TITLE
Less lax rounding at "Next lecture in ...hours"

### ISSUE THREAD

**Issue by woodpecker2010** [TCA-Team/TumCampusApp#346]
**Steps to Reproduce**
- connect your TumOnline Calendar to the App
- wait until exact 2h before a lecture starts
- wait one minute

**Expected Result**
- App tells me, my lecture starts in 1h and 59min or
- App tells me,  my lecture starts in about 1h 45min

**Actual Result**
- App tells me, my lecture starts in 1h (compare attached Screenshot)

**Problem**
This is unfortunately pretty much missleading, as I'm mostly checking the time until the next lecture by having a quick look on "lecture starts in..h". And telling that the lecture starts in 1h even though it starts in 1h and 59min is simply wrong.
Btw: this issue appears every hour.

:sparkles: **Suggested Enhancement**:sparkles: 
- round time until next lessons up to minutes or
- round time up to 15min and set an "about" or "~" in front

**Environment**
Phone: Xiaomi RedRice S1
OS: Cyanogenmod 12.1
TUMOnline App: v1.3.2 
Language: english (I'm serious. it just appears to be german as lots of stuff isn't translated)

![screenshot_2015-10-21-09-32-17](https://cloud.githubusercontent.com/assets/11944529/11498864/4ff9f84e-9822-11e5-9fde-eef23df57ede.png)

**Comment by pfent** [comment]
We are currently using [DateUtils.getRelativeTimeSpanString()](https://developer.android.com/reference/android/text/format/DateUtils.html#getRelativeTimeSpanString(long)) without further logic to display this String.

BTW: This also results to slightly incorrect results with past lectures, where my lecture is 2:46 minutes ago, but the lecture started almost 3 hours ago.
![screenshot from 2015-12-01 14-47-04](https://cloud.githubusercontent.com/assets/5686284/11502430/192c447a-983b-11e5-92bf-a382065ba2ab.png)

So, should we:
* open a bugreport on the Android bugtracker?
* switch to a better DateTime library, that gets this right?
* implement it on our own? (PRs welcome)

IMHO our solution is "good enough"

**Comment by kordianbruck** [comment]
@pfent We can use JodaTime, which is the go to solution to replace the crappy Java Date Apis. [Check this example](http://stackoverflow.com/questions/27981071/display-relative-time-with-one-number-with-joda-time-java)

With that we can easily add more than one unit to show and don't have to mess around with language and other things.

**Comment by pfent** [comment]
JodaTime looks good to me.
Let's see, if I have some spare time to play around with it…

**Comment by kordianbruck** [comment]
Also an Issue in Mensa Opening Times, like this feedback shows

"Die Zeitangabe, wann die Mensa öffnet uns schließt ist nicht genau. Es wird immer nur in 1h oder 30min Schritten anzeigen."

**Comment by pfent** [comment]
Fixed in #433
