### ISSUE TITLE
Update developer documentation

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#347]
Since the developer documentation was not updated for a while, we should make sure to update existing technical documents to the most recent TCA version, noting down all links and sources (e.g. TUMonline API etc.).

Newbies: Please collect in this issue all questions and mention any problems so that we can address them in the new documentation.

**Comment by kordianbruck** [comment]
Is there any developer documentation? Thats news to me. If so, please let us know where this can be found, so we can work with that instead of starting from scratch

**Comment by nilstk** [comment]
Well :) ...
You created the most recent version during the summer term practical course. Best approach might be to ask new developers for their questions and provide answers besides the typical stuff (diagrams, explanations on start-up etc.)

**Comment by kordianbruck** [comment]
Developer Docs will be updated here in the Wiki on a regular ongoing basis. The current team is also working on this.
