### ISSUE TITLE
Settings: sub pages are missing the action bar 

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#348]
also some activities are missing a parent activity and in such don't show the return button.

**Comment by kordianbruck** [comment]
Research:
https://code.google.com/p/android/issues/detail?id=179637
https://code.google.com/p/android/issues/detail?id=170066

It really seems to be an issue with library we are using for the settings: 
https://github.com/Machinarius/PreferenceFragment-Compat/

**Comment by pfent** [comment]
The support-v7 library recently added a new PreferenceFragmentCompat: (https://developer.android.com/reference/android/support/v7/preference/PreferenceFragmentCompat.html)

We probably won't have to use the external library anymore

**Comment by kordianbruck** [comment]
@pfent thanks, I was looking for this but somehow it didn't show up when searching for PrefrenceFragment and Appcompat.

Please checkout https://github.com/TCA-Team/TumCampusApp/tree/feature-prefrence-appcompat which has already most changes done. The nested preferences are not working yet.

**Comment by kordianbruck** [comment]
Actually found a solution: http://stackoverflow.com/questions/32487206/inner-preferencescreen-not-opens-with-preferencefragmentcompat
