### ISSUE TITLE
Rework GCM registration

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#349]
Our current approach to registering the App to GCM is handled in the ChatRoomsActivity, so users that did not start this Activity once are not registered. We probably should do this in the StartupActivity.

Furthermore, the GoogleCloudMessaging.register() method is deprecated since May 2015 and we should switch to the new Instance ID API (see: https://developers.google.com/cloud-messaging/registration and
https://developers.google.com/cloud-messaging/android/legacy-regid)

**Comment by kordianbruck** [comment]
We should preferrably implement a method that does not make it too hard to maintain the FOSS branch: https://github.com/TCA-Team/TumCampusApp/tree/1.3.1-FOSS

I was thinking of simply putting everything into a wrapper class, which we can then simple delete for the FOSS. Ideally we setup GCM with the app loading right away in the StartupActivity. 

Any thoughts?

**Comment by kordianbruck** [comment]
Storing the ID in the backend still requires some work. Otherwise it should be all set.
