### ISSUE TITLE
Present TCA at 33C3

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#354]
Requirement: full / better documentation

The idea is to present the app and its functionalities at the LT session of 33C3, since other universities might be interested in similar features and may reuse our code for their purposes. The TCA offers a great foundation to offer similar services at other universities, since they often don't have the resources for development.

**Comment by kordianbruck** [comment]
Puhhh, I don't have time to prepare this. The only benefit I see, is that one would maybe get some feedback from a security perspective, but apart from that, I'm not really sure if this makes sense. 

One can still do this LT spontaneously, will close the issue for now.
