### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#356]
We should think about implementing some more checks than just lint:

https://github.com/stephanenicolas/Quality-Tools-for-Android

Code duplication and other code smells are not handled in lint. Check this thesis for a comparison: 
http://repository.tudelft.nl/assets/uuid:bcba7e5b-e898-4e59-b636-234ad3fdc432/thesis.pdf

Also: some best practices:
https://github.com/futurice/android-best-practices#put-passwords-and-sensitive-data-in-gradleproperties

**Comment by kordianbruck** [comment]
So I will split this up into multiple sub issues.

**Comment by psukys** [comment]
So it's more about operational side rather than improving code quality (unit tests, fixing deprecated usage, etc.)?

**Comment by kordianbruck** [comment]
@psukys both. If you prefer to do more unit tests and fix decreprecation, I also welcome it. Together with those tools you can then verify and show what improvements you have delivered to the app with those additional unit tests. (Test Gaps, Code Coverage, etc.)

=> Fancy graphs for your final presentation.
