### ISSUE TITLE
Organisation

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#361]
The current implementation of the TCA's organisation feature does not provide useful information (actual name of person). It's required to modify gathered parameters according to the information provided in A. Bernhofer's email from Feb. 26th.

**Comment by Shifuddin** [comment]
Hi Kordian,
We have started another part of our project that is to improve organizational data part of TCA. I have found that TCA gather information from tum online to show organizational data. But for some parameter, it fails to acquire information like name of the person. At the same time for some organizational part like TUM Board of Trustees, TCA can acquire all information. My question is, should we rely on this process that to fetch data from tum online or we should fetch from other sites also like http://www.tum.de/en/about-tum/our-university/tum-board-of-management/. If we fetch from third party sites other than tum online then there will be a question of integration also. 

There is a java file named OrgDetailsItem which has some get methods which returns name, identifier and other information like mail address etc to OrganizationalDetails Activity. Should we modify the get methods like getContactEmail() by checking identifier there and if it does not contain proper value, fetch information from third party sites and then return the value?

**Comment by pfent** [comment]
Hi @Shifuddin,
I think the idea was to first identify and document for WHICH parameters WHAT information is missing / not avaidable, so this can be fixed in the TUMOnline webservice.

We currently have implemented the TUMOnline webservice (documented [here](https://wiki.tum.de/display/tumonlineappdevndoc/home)) via TUMOnlineRequest, which can be found in the tumonline package.

**Comment by nilstk** [comment]
I forwarded it to Andreas, who is on vacations right now.
In theory TUMonline provides the information (AFAIK) and you just need to fetch/correct the querries.
I hope he will follow up soon.

**Comment by Shifuddin** [comment]
Hi All,
According to the suggestion of Philipp, I have started to find out parameters which are missing for which organizations. Before going there I like to mention, I can't access the documentation link provided by Philipp which is not available now by showing Page Not Found error. 

Following are the parameters available in TCA.
•	Nr - Organisation Identification Number, getCode()
•	Name - Organisation Name, getName()
•	Contact name - Contact Name of Organisation, similar to Organisation name, getContactName()
•	Address- getContactStreet()
•	Homepage - getContactLocationURL()
•	Mail - getContactEmail()
•	Phone - Phone Number, usually to the secretary of the organization, getContactTelephone()
•	Fax - getContactFax()
•	Secretary - getContactLocality()
•	Extra Caption - getAdditionalInfoCaption()
•	Extra - getAdditionalInfoText()
•	Bib - getContactLocality()

I have a query regarding name. It is documented that it will show name of the organization or position. In case of president under TUM Board of Management what will it show just 'president' or 'TUM Board of Management' or name of the president?

Following are the Organizations available in TCA.

•	TUM Board of Management
•	Gremien
•	Functional Units
•	Zentrale Verwaltung
•	Mathematics
•	Physics
•	Chemistry
•	TUM School of Management
•	Civil, Geo and Environmental Engineering
•	Architecture
•	Mechanical Engineering 
•	Electrical and Computer Engireering
•	Informatics
•	TUM School of life Sciences Weihenstephan
•	TUM School of Medicine
•	Sport and Health Sciences
•	TUM School of Education
•	Political and Social Sciences
•	Integrative Research Centers
•	TUM Graduate School
•	Central Scientific Institutions
•	Research Projects
•	Officers and Representatives 
•	Institution close to the University
•	Bavarian School of Public Policy

Among the mentioned list I made a availability table for TUM Board of Management which is attached as file -
[TUM Board Of Management.docx](https://github.com/TCA-Team/TumCampusApp/files/339711/TUM.Board.Of.Management.docx)

Am I on the right track? Should I proceed to create availability list for all other organizations?

**Comment by pfent** [comment]
The link works for me - did you log in with your TUMID? I don't know the TUM Wiki very well, but you should definetly have access there, maybe @nilstk can help?

For the other things, you probably need to dive deeper into the code and identify, which API endpoints return what information and precisely identify, what is missing in the API **responses** and how we can fix the problems. E.g.:

- API Request:
https://campus.tum.de/tumonline/wbservicesbasic.orgBaum
- Expected:
The TUM organizations tree
- Result:
"Token ist nicht bestätigt oder ungültig!"
- Fix:
Include the token in the URL

**Comment by Shifuddin** [comment]
Hi,
What I understood , I need to change the access token to see whether the service returns proper information. For example for tum president "https://campus.tum.de/tumonline/wbservicesbasic.orgDetails?pOrgNr=20208&pToken=61E5E653BCE4CFB24F3F1E9D3F138AD0&" returns the following output 

<?xml version="1.0" encoding="UTF-8"?>
-<rowset>
-<row>
<nr>20208</nr>
<name>Präsident</name>
<kennung>TUPRAES</kennung>
<ansprechpartner isnull="true"/>
<adresse_text isnull="true"/>
<www_homepage isnull="true"/>
<email_adresse isnull="true"/>
<sekretariat_info isnull="true"/>
<fax_nummer isnull="true"/>
<telefon_nummer isnull="true"/>
<bibliothek_info isnull="true"/>
<zusatz_info isnull="true"/>
<zusatz_info_name isnull="true"/>
</row>
</rowset>

I think the nr will remain same for a particular organization but I need to vary the token according to the guideline. But still I didn't get the access to the document. I am attaching the screen shot after I logged in to there.
![tumaccess](https://cloud.githubusercontent.com/assets/17300321/16517036/a77fe12c-3f7b-11e6-9896-98f4732d2d6c.png)

If this is only a pdf file, I will request you to attach herewith if possible. Thanks in advance.

**Comment by pfent** [comment]
For your orgDetails API access:
now, you are on the right track. From those requests, you can hopefully figure out on your own, what info is missing for the organisation feature to be useful.

In the API documentation, there are several other API endpoints mentioned, that could get the specific information, that's missing here:
- This one seems promising for the specific missing information you mentioned
https://campus.tum.de/tumonline/wborggruppen.gruppen_anonym_xml?pOrgNr=20208
- Those should in theory export organization details (although I'm only getting "unauthorized resource access" with my personal token)
https://campus.tum.de/tumonlinej/ws/webservice_v1.0/cdm/organization/persons/xml?orgUnitID=20208&token=TODO
https://campus.tum.de/tumonlinej/ws/webservice_v1.0/cdm/organization/xml?orgUnitID=24633&token=TODO

**Comment by Shifuddin** [comment]
Hi,
@pfent   Thanks for providing such important information. For me also last two links don't work. For some organizations first api access link works for me.

I have investigate almost half of the organizations from TUM Board of Management to Architecture with organization id. The number of organizations where is no useful information is 63. Among those 63 organizations only 7 are showing some useful information using the new api access link- https://campus.tum.de/tumonline/wborggruppen.gruppen_anonym_xml

[Android Organizational Report.docx](https://github.com/TCA-Team/TumCampusApp/files/344546/Android.Organizational.Report.docx)

Should I use this API access link in the development or there any other solutions. Moreover new response xml format is different from previous response format. Also the new one is not ready to go format having some nested structure. 

If I have to use new API access link in the development then do you have any suggestions for me like how to improve code to parse both format is an eassy way?

**Comment by pfent** [comment]
You can probably just reuse the [TUMOnlineRequest](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/tumonline/TUMOnlineRequest.java)
To do so, you have to create some models for the data in ```de.tum.in.tumcampusapp.models```. For this I suggest, you familiarize with SimpleXML and the Annotations used to describe how the XML data is parsed.

Afterwards, you can create a new TUMOnline API entry in [TUMOnlineConst](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/tumonline/TUMOnlineConst.java)

**Comment by Shifuddin** [comment]
Hi,
Thanks for the suggestion. I have faced an issue while working with this https://campus.tum.de/tumonline/wborggruppen.gruppen_anonym_xml?pOrgNr=46175  API access link. The output of the API call is not correct. All the xml validator and also simplexml framework which is used in TCA detect an error in that output. Problem is in the first line.

<?xml version="1.0" encoding="UTF-8" standalone="true"?>
Error Statement: The standalone document declaration value must be "yes" or "no", not "true". 

That's why I can easily parse other documents using the framework and obtain values but our desired document is not working.

**Comment by pfent** [comment]
@kbruck can you fix this?
@Shifuddin You probably should be able to work around this by replacing the line in question, so you can continue working until this is fixed in the API?

**Comment by kordianbruck** [comment]
Yes, I will take a look at fixing this in TUM Online tomorrow. @Shifuddin please fix the error yourself till this issue is resolved using a string replacement.

**Comment by kordianbruck** [comment]
@pfent @Shifuddin we took a look at the XML and the value of standalone is already "yes" - I don't know how you get true from the webservice. Must be modified somewhere along the way?

**Comment by Shifuddin** [comment]
Hi,
I think it could be for Microsoft Edge browser. Still I open the link "https://campus.tum.de/tumonline/wborggruppen.gruppen_anonym_xml?pOrgNr=20208" in mircrosoft edge and get true instead of yes. Thank you.

**Comment by Shifuddin** [comment]
Hi,
I have completed the task. Now it's possible to extract information from that alternate link if information is not available from regular request. @pfent I have tried to follow your suggestions during development. But since the xml content from that link is so nested several times e.g. for some links it's nested 5 times. That's why, I found simplexml is not the right package. I used normal xml parser which is very effective in such situation. Another restriction was that I couldn't move to another activity but use a java class to retrieve information and use in the current activity. For this I couldn't also reuse activityforaccessingtumonline.

I implemented a simple java class which retrieves information from alternate link if normal way does not retrieve proper information and have getter methods which are used in the OrginasationDetailsActivity.

**Comment by pfent** [comment]
Nested data shouldn't pose a problem to simplexml, especially with the [@Path annotations](http://simple.sourceforge.net/download/stream/doc/tutorial/tutorial.php#xpath), utilizing XPath queries. 

Nevertheless, I'm looking foreward for your pull request. Since the APC deadline is appraching quickly, you probably should open one immediately.

**Comment by Shifuddin** [comment]
Hi,
I am ready to submit the code. I actually I don't have any experience with pull request as it's my first. Can you please instruct me how can I do this. Thanks.

**Comment by pfent** [comment]
Contributing is explained in [the wiki](https://github.com/TCA-Team/TumCampusApp/wiki#how-to-contribute) briefly.

The process to create your first pull request is described in detail in the second link: https://guides.github.com/activities/forking/

**Comment by kordianbruck** [comment]
Might be smart to read trough a HowTo first: http://readwrite.com/2013/09/30/understanding-github-a-journey-for-beginners-part-1/

**Comment by Shifuddin** [comment]
Hi, I have opened a pull request. Thanks.

**Comment by kordianbruck** [comment]
This feature has been removed by @pfent
