### ISSUE TITLE
Gather further statistical data

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#365]
Since https://github.com/TCA-Team/TumCampusApp/issues/359 collects the user's major already, we may want to use it to obtain further information on general TCA users, which can be used to improve marketing actions to increase the distribution in a particular area. Furthermore it's of interest to us and in terms of the alarming feature (cf. coverage).

The major may be obtained and transfered during the initial setup once, while submitting it from upgraded apps once, too.

**Comment by kordianbruck** [comment]
We are collecting information about which activity is being used how often. Based on the lectures we are able to see which majors use the app more often. The major selection has been removed once again, as barely anyone actually selected it.

As long as its not possible to receive it in an automated fashion, this will not be feasible. Furthermore, we actually don't want to collect this personalized data in any case.
