### ISSUE TITLE
Add PDF Viewer to App

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#368]
As suggested by pfent in https://github.com/TCA-Team/TumCampusApp/pull/367 we should add a PDF viewer for the PlansActivity to directly display all the plans in the App. 

"Also, an inline display for the PDFs would be nice to have. There is a [PDFRenderer](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer.html) available for API 21+, even with an exhaustive [example on GitHub](https://github.com/googlesamples/android-PdfRendererBasic). Then you can use the fileprovider as a fallback for lower APIs."

**Comment by t2m4k1** [comment]
So after reading a little bit, the task seems to be to implement a fragment containing a pdf renderer and then depending on the client's api version either continue the way we currently do it or redirect the newly downloaded file to the pdf-fragment.

**Comment by kordianbruck** [comment]
@t2m4k1 exactly! Maybe you can even find a lightweight solution for older android versions.

**Comment by t2m4k1** [comment]
Ok I'll see what I can do. Maybe a simple integrated webview is supported by older android versions. Would that be sufficient? Btw. which android version are we referring to as the minimum supported? API16?

**Comment by kordianbruck** [comment]
min is 24 currently: https://github.com/TCA-Team/TumCampusApp/blob/master/app/build.gradle

**Comment by t2m4k1** [comment]
These issues seem to be fixed in:
https://stackoverflow.com/questions/2456344/render-a-pdf-file-using-java-on-android/21383356#21383356

**Comment by t2m4k1** [comment]
For documents stored online like the plans' pdfs I've had success in opening them by using a url which redirects to google-drive pdf viewer. For this purpose its not even necessary to use any external libraries. Is that sufficient for now?
```        webView.loadUrl("https://docs.google.com/gview?embedded=true&url=" + path);
```
Also for the fragments to work, I'm currently turning the plans activity into two separate fragments (list and pdf).

**Comment by kordianbruck** [comment]
Can you zoom and pan around on that webview then? I mean I'm all in for nice and easy solutions!

**Comment by kordianbruck** [comment]
Done
