### ISSUE TITLE
TCA und TCAport issue

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#372]
Users having installed the Android version as well as the new TCAport (portable / platform independent version) will receive the following installation error upon updates of TUM Campus App. Maybe TCAport can use different names instead. 

06-10 22:41:12.691 E/Finsky  (26840): [1] com.google.android.finsky.installer.ac.onReceive(2624): Error -505 while installing de.tum.in.tumcampus: INSTALL_FAILED_DUPLICATE_PERMISSION: Package de.tum.in.tumcampus attempting to redeclare permission de.tum.in.tumcampusapp.permission.C2D_MESSAGE already owned by de.tum.in.tumcampusapp

**Comment by gapsh** [comment]
I already changed the package name for the port. So this should not be an issue anymore.

**Comment by kordianbruck** [comment]
@nilstk probably have to update to the latest CN1 version to get rid of this?

**Comment by kordianbruck** [comment]
@gapsh so it is fixed with the new release?

**Comment by gapsh** [comment]
@kordianbruck Yep, with the new release of the TCAport ;-)
