### ISSUE TITLE
MVV Integration 

### ISSUE THREAD

**Issue by larslue** [TCA-Team/TumCampusApp#380]
At the Moment the MVV widget shows next departures of a given station. But it does not state the direction. Please change it to a format such as "U6 - Klinikum Großhadern" or "234 - Garching Forschungszentrum".

**Comment by kordianbruck** [comment]
@larslue thanks for this. Somehow this must have been removed in a recent change. I'll check it out in the coming weeks, what went wrong exactly.

**Comment by pfent** [comment]
@kordianbruck I've rewritten the MVV parsing, that's probably what happened ;-)

currently we have a "Departure" class, that's located in the TransportManager. It already contains the direction, so probably it's just a display bug

**Comment by kordianbruck** [comment]
@pfent you're right, the wrong info is getting display, but its correctly parsed.
