### ISSUE TITLE
Jenkins: add FindBugs

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#385]
https://wiki.jenkins-ci.org/display/JENKINS/FindBugs+Plugin

**Comment by pfent** [comment]
I added plugins to [Jenkins](https://build.wdkk.de/job/TumCampusApp/) for FindBugs and PMD, to track our code quality

**Comment by kordianbruck** [comment]
Thanks! This will surely help :+1:
