### ISSUE TITLE
Survey - public results 

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#393]
By accident I replied a question by a different user recently. The results of that question would be of interested to me, too. 

So far there is no option to access the results to questions of others and we want to think about providing the results of all questions to all publicly or - alternatively - allow the person submitting the questions to make it available publicly by providing a checkbox (default: public).

Any comments? What about making everything public and display the questions & results on tumcabe (website)?

**Comment by mhmadayad** [comment]
@nilstk Yes this is quite  possible , but some users might be annoyed from others questions, and they will search for their questions in a list of 100's , this will be annoying right too?

**Comment by mhmadayad** [comment]
@nilstk or we can display user own questions first and then others questions. we can separate them.
What about making it an add-on to the multiple choice Survey ?

**Comment by nilstk** [comment]
Thinking about the app itself, it should display your own ones only, while there might be an option to view public question 'n results maybe.

Thinking about tumcabe, we may think about showing all public questions and their results, but providing such a webpage is optional, but allows easier access to a bunch of questions and results.

**Comment by Biart95** [comment]
I think I can tackle this issue as a first dive into the project. Adding a separate option in TCA to view public questions and their results must be not very hard.

**Comment by pfent** [comment]
surveys were removed in #720
