### ISSUE TITLE
Survey bug

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#397]
![tcabug](https://cloud.githubusercontent.com/assets/2790516/16707034/81529e70-45c2-11e6-9cf7-d156833c367d.png)

... when trying to submit this question:
Imagine that you downloaded a pirated app. Do you feel bad about it?

**Comment by mhmadayad** [comment]
@nilstk Just tried it, it worked. There should be no problem.

**Comment by kordianbruck** [comment]
Was there a internet connection? @mhmadayad what happends when you submit a questions while having no/bad connection?

**Comment by mhmadayad** [comment]
@kordianbruck we are handling not internet connection. We show the no internet layout, but in case of bad connection.
we should toast a message here
 public void failure(RetrofitError error) {
                                        Utils.log("Failure: " + error.toString());
                                          //toast }

**Comment by kordianbruck** [comment]
Might happen, that Retrofit throws an exception when it gets malformed data. So maybe you could handle that as well?

Also: Nils has a older version from the playstore, that does not contain your latest pull request. Maybe a related issue?

**Comment by mhmadayad** [comment]
@kordianbruck  Yes , this the second time that Nils ask to fix a bug knowing that we are sure that there shouldn't be any bugs.

**Comment by nilstk** [comment]
Yes, I have the version from the PlayStore on my phone. A months old probably.

@mhmadayad It's just for information ;-) - if there is no bug or you fixed it already, it's perfect. I just thought I want to notify you about it in time, since I was not aware that there is a new version available already.

**Comment by kordianbruck** [comment]
Probably fixed in newest version.
