### ISSUE TITLE
Migration to minSdkVersion 14

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#405]
Android 4.0 Ice Cream Sandwich, aka SDK 14 is now 5 years old, and almost all our users now use a more recent version of Android. @kordianbruck mentioned, there are only ~20 users left, that's <0,2%.

Here's a checklist what we can do, when upgrading to minSdkVersion 14:
- [x] Remove the NineOldAndroids library, that's been deprecated and not updated since 2014
- [x] Remove the usage of the deprecated ClipboardManager in InformationActivity
- [x] Remove the "@TargetApi" annotations in CalendarHelper, CalendarManager, MensaWidget, MensaWidgetService, MensaRemoteViewFactory, CardsWidget, CardsWidgetService
- [x] Remove the branch in OpenHoursListFragment.onCreate()
- [x] Remove the "@SupressLint("NewApi")" in MainActivity
- [x] Replace ActivityCompat.invalidateOptionsMenu() with Activity.invalidateOptionsMenu() in CalendarActivity, GradesActivity, MainActivity
- [x] Merge the differently flavoured AndroidManifests

**Comment by pfent** [comment]
https://android-developers.blogspot.de/2016/11/google-play-services-and-firebase-for-android-will-support-api-level-14-at-minimum.html

**Comment by kordianbruck** [comment]
We can also remove these right?
```
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:cardview-v7:25.0.1'
    compile 'com.android.support:preference-v7:25.0.1'
    compile 'com.android.support:recyclerview-v7:25.0.1'
    compile 'com.android.support:support-v4:25.0.1'
```
