### ISSUE TITLE
Chat message look really bad 

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#417]
On a Nexus 7 - 2013
![screenshot_2016-10-25-14-39-17](https://cloud.githubusercontent.com/assets/298860/19686558/f05da626-9ac1-11e6-8aca-d2367f19b833.png)

**Comment by pfent** [comment]
Fixed in  #420

**Comment by kordianbruck** [comment]
This is a issue with the message layout, not the editbox.
