### ISSUE TITLE
Token kann nicht aktiviert werden wegen Fehler in Chat-Registrierung

### ISSUE THREAD

**Issue by woladie** [TCA-Team/TumCampusApp#424]
mit Samsung S5, Android 6.0.1, auf TUM Online ist die Chat-Registrierung gesetzt, Token mit 5 aktivierten Rechten gesetzt,

Beim Starten der TUM App wird Token und Daten aktualisiert. Jedes mal Abbruch wegen Fehler in Chat-Registrierung. Keine weiteren Angaben zu Fehlern.

App kann nicht gestartet werden.

**Comment by pfent** [comment]
Momentan wird der Server der App umgezogen, daher wird es wohl noch bis morgen oder übermorgen zu Verbindungsproblemen kommen…

Ich kann leider nur empfehlen ein wenig Geduld zu haben, sorry! 😿 
http://www.downforeveryoneorjustme.com/tumcabe.in.tum.de

**Comment by kordianbruck** [comment]
Tweaked the server some more - should be working again until we move to the new instance and finally don't have to rely on apache any longer...

**Comment by kordianbruck** [comment]
Migration jetzt eigentlich abgeschlossen und server umgestellt auf nginx - sollte alles wieder klappen.
