### ISSUE TITLE
Room time table does not work

### ISSUE THREAD

**Issue by TheZoker** [TCA-Team/TumCampusApp#431]
The room time table does not work, no events are visible:
![screenshot_20161125-145356](https://cloud.githubusercontent.com/assets/1368405/20627248/1ed6bcd4-b31f-11e6-9ca0-030f7454a348.png)

On the campus website, everything works fine: https://campus.tum.de/tumonline/wbKalender.wbRessource?pResNr=12559&pDisplayMode=w&pDatum=

**Comment by kordianbruck** [comment]
Good question why this is not working - anyone volunteering to check the server? :stuck_out_tongue:

**Comment by Yakuky** [comment]
@kordianbruck 

Backend provides API in form of api/roomfinder/room/scheduleById/RoomId/yyyymmdd/yyyymmdd
And then it returns every schedule of this room between these 2 dates.

However, what frontend requests is api/roomfinder/room/scheduleById/RoomId/Epoch/Epoch

So the result is always empty.

Besides, frontend always requests 3 times for one room, which is not necessary.

Anyway, it is not a problem of server.

**Comment by kordianbruck** [comment]
@Yakuky thanks for debugging this. A fix would be much appreciated!
