### ISSUE TITLE
TUM Campus App Not Displaying Events

### ISSUE THREAD

**Issue by AetherV** [TCA-Team/TumCampusApp#435]
## Steps to Reproduce

1. Be Informatik Ersti
2. Take EiDI 1
3. Open TUM App's Calander
4. Observe missing class 

## Expected Result
EiDI 1 Should show up for the 11/30 and ~~12/07~~ Correction: 12/07 is Dies academicus so that is intended, sorry, 11/30 is still however class
## Actual Result
Does not show up
## Problem
The TUM Campus App seems to not be able to display the data for the 11/30 ~~and 12/07~~. There should be Einfuehrung in Die Informatik 1 appearing that day on my calendar, just like on TUM Online, however for those two weeks it is missing. 

Problem is confirmed by multiple people on the Telegram group (at least 4+ cases)
### Environment
* Phone: Samsung J7
* OS: 6.0.1 Android
* TUMOnline App: v1.4.5
* Language: English

**Comment by AetherV** [comment]
Interesting side note that I observed: The TUM Campus App's Calendar integration still allows the events to be shown on the phones / 3rd Party calendar apps (such as the Google Calendar App). It appears to be a bug involving the app itself.

**Comment by pfent** [comment]
Noticed a similar behaviour with a lecture on 31.10.
Seems to be an off-by-one error in the CalendarActivity…

**Comment by pfent** [comment]
Well, that was embarassing. `<` instead of a `<=`.

Thanks for reporting anyways!
