### ISSUE TITLE
404 on Cover-image URL of movies

### ISSUE THREAD

**Issue by mammuth** [TCA-Team/TumCampusApp#437]
The tumcabe server doesn't serve the cover images which url's it provides on the /kino api endpoint.
<img width="901" alt="bildschirmfoto 2016-12-16 um 16 28 32" src="https://cloud.githubusercontent.com/assets/3121306/21268009/20467e9e-c3ad-11e6-92f6-3adb338ea3ac.png">

## Steps to Reproduce

1. Open the "cover" attribute of any movie of the API response on[ /kino](https://tumcabe.in.tum.de/Api/kino/)

## Expected Result
No 404

## Actual Result
404

## Problem
404 is not nice

## Suggested Enhancement :sparkles:
dont do 404

### Environment
Chrome, iOS client

Related iOS issue: https://github.com/TCA-Team/iOS/issues/41

**Comment by mathiasquintero** [comment]
Awesome bug description is awesome. "Suggestion: Don't 404"

**Comment by mammuth** [comment]
> Awesome bug description is awesome. "Suggestion: Don't 404"

Issue & pr templates need to be followed!11!!! No matter how complex the reported issue is 😁

**Comment by kordianbruck** [comment]
I've implemented a redirect to a placeholder. For example: https://tumcabe.in.tum.de/File/kino/test.png

Is that what you wanted @mammuth ?

**Comment by mammuth** [comment]
Think that'll do it 👍
