### ISSUE TITLE
Mensa menu doesn't work (not showing self-serve)

### ISSUE THREAD

**Issue by JohannesAck** [TCA-Team/TumCampusApp#439]
## Steps to Reproduce

1.Open the App
2.Change your Mensa to "Arcisstraße".
3.See that Self-Service is missing

## Expected Result
Should show Self-Service as listed on here http://www.studentenwerk-muenchen.de/mensa/speiseplan/speiseplan_421_-de.html.

## Actual Result
Shows everyting listed on the website except for Self-Service.

### Environment
* OS: Android
* TUMOnline App: v1.4.7
* Language:  German

**Comment by pfent** [comment]
Can you elaborate, what you mean with "self-serve" and at which Mensa?
I can compare the menu from Mensa Garching in the App and on the [Studentenwerk Website](http://www.studentenwerk-muenchen.de/mensa/speiseplan/speiseplan_2017-01-10_422_-de.html) and they match perfectly. (Tough 4x "Saisonale Beilagensalate" seems to be wonky on their side)…

In general, we don't have a direct API for the meal plans but rely on parsing the website - anyhow I could try to contact the Studentenwerk, if you could elaborate what's wrong here?

**Comment by JohannesAck** [comment]
Certainly, I forgot to mention that I study in the "Stammgelände".
One of the lanes of Mensa Arcisstraße was recently converted to a "Self-Service" lane as you can see here: http://www.studentenwerk-muenchen.de/mensa/speiseplan/speiseplan_421_-de.html .
The things listed under Self-Service don't show up in the App, you can reproduce it by changing your Mensa to Arcisstr.

Essentially it would only need to be added to the function you use to scrape the website, however I couldn't find it in your code and I don't really know much about Java and even less about Android programming.

**Comment by pfent** [comment]
Ah, that's definetly a bug then. Thanks for reporting it!
We are currently using a webapp, that does all the scraping (http://lu32kap.typo3.lrz.de/mensaapp/exportDB.php).

Maybe @kordianbruck knows who runs this? Probably it's about time we do the scraping ourselves…

**Comment by xsrf** [comment]
Looks like the webservice fixed it ;)
`{"id":"439034","mensa_id":"421","date":"2017-01-26","type_short":"ss","type_long":"Self-Service","type_nr":"0","name":"Bio-Penne mit Bio-Soja-Bolognese-Sauce (f) [Gl,GlW,Kn,Mi,So]"}`

**Comment by pfent** [comment]
Hm, seems the parsing in the App is still borked…
Also, does anyone know what those `[Gl,GlW,Kn,Mi,So]` annotations mean, or should we just strip them?

**Comment by kordianbruck** [comment]
Found it: http://www.studentenwerk-muenchen.de/mensa/zertifikate-hg/allergenkennzeichnung/

**Comment by xsrf** [comment]
Just so you don't have to retype it all:

`		'1'	:	'mit Farbstoff',
		'2'	:	'mit Konservierungsstoff',
		'3'	:	'mit Antioxidationsmittel',
		'4'	:	'mit Geschmacksverstärker',
		'5'	:	'geschwefelt',
		'6'	:	'geschwärzt (Oliven)',
		'7'	:	'unbekannt',
		'8'	:	'mit Phosphat',
		'9'	:	'mit Süßungsmitteln',
		'10':	'enthält eine Phenylalaninquelle',
		'11':	'mit einer Zuckerart und Süßungsmitteln',
		'99':	'mit Alkohol',
		'f'	:	'fleischloses Gericht',
		'v'	:	'veganes Gericht',
		'GQB'	:	'Geprüfte Qualität - Bayern',
		'S'	:	'mit Schweinefleisch',
		'R'	:	'mit Rindfleisch',
		'K'	:	'mit Kalbfleisch',
		'MSC':	'Marine Stewardship Council',
		'Kn':	'Knoblauch',
		'13':	'kakaohaltige Fettglasur',
		'14':	'Gelatine',
		'Ei':	'Hühnerei',
		'En':	'Erdnuss',
		'Fi':	'Fisch',
		'Gl':	'Glutenhaltiges Getreide',
		'GlW':	'Weizen',
		'GlR':	'Roggen',
		'GlG':	'Gerste',
		'GlH':	'Hafer',
		'GlD':	'Dinkel',
		'Kr':	'Krebstiere',
		'Lu':	'Lupinen',
		'Mi':	'Milch und Laktose',
		'Sc':	'Schalenfrüchte',
		'ScM':	'Mandeln',
		'ScH':	'Haselnüsse',
		'ScW':	'Walnüsse',
		'ScC':	'Cashewnüssen',
		'ScP':	'Pistazien',
		'Se':	'Sesamsamen',
		'Sf':	'Senf',
		'Sl':	'Sellerie',
		'So':	'Soja',
		'Sw':	'Schwefeloxid und Sulfite',
		'Wt':	'Weichtiere'`
