### ISSUE TITLE
eduroam assistant should check secure configuration

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#441]
## Steps to Reproduce

1. setup "eduroam" by hand or using TCA <=1.4.7 in a not entirely secure way
2. open TCA

## Expected Result

TCA should offer "update eduroam profile to latest security standards" (it may also say "Your eduroam setup is NOT secure, please update" but we don't want users get crazy, right?)

## Actual Result

_imagine some tumbleweed passing by_

## Problem

Lots of users don't configure eduroam properly and put their credentials on risk without knowing. They should be made aware of that not every wifi is always a happy place.

## Suggested Enhancement :sparkles:

Check users eduroam profile (if exists) against latest security standards (root certificate match, server certificate subject match) and notify them if the profile is not secure.

### Environment
* Phone: Any
* OS: Android 4.x+
* TCA Version: 1.4.7

**Comment by pfent** [comment]
Absolutely! Seems like a good addition to our "setup eduroam" feature and would be an easy security upgrade for all our users.

**Comment by xsrf** [comment]
Oh btw. you might have users originating from another university whose profile you don't want to overwrite in this case...

If the username is within the radius zones mwn.de, *.mwn.de, tum.de, *.tum.de, mytum.de, ... or matches against "[a-z]{2}[0-9]{2}[a-z]{3}" you can be pretty sure that you know what a valid configuration should look like and check it.

If it doesn't, you might apply additional checks or just tell the user that a unknown configuration was found and ask if he is a TUM member and let him dismiss the warning.

I guess any secure eduroam configurations should do either:
* Any certificate validation + server subject match
* Validation against custom CA with or without server subject match

TUM configurations should do:
* PEAP (or TTLS)
* MSCHAPv2 (or PAP)
* Validate certificate against Telekom Root CA 2
* Server subject match against radius.lrz.de
* use anonymous identity

**Comment by pfent** [comment]
should be fixed with #449
