### ISSUE TITLE
Add Impulsiv RSS feed for the newsfeed

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#442]
There's a RSS feed for the MPI student newspaper avaidable [here](https://impulsiv.fs.tum.de/index.xml).

Can we add it to the list of feeds for the server?

**Comment by kordianbruck** [comment]
Its added, do you have an icon for it? 64x64px  #3070b3

Example: https://tumcabe.in.tum.de/File/news/sources/src_14.png

http://fa2png.io/

**Comment by kordianbruck** [comment]
The feed has been added.
