### ISSUE TITLE
Get rid of SQLite - Use Objectbox

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#443]
We should refactor our code and get rid of SQLite. It does introduce many problems with exceptions and migrations. We need to do better, for the simple data model that we have, the SQLite system is too volatile.

- http://greenrobot.org/announcement/introducing-objectbox-beta/
- http://greenrobot.org/objectbox/documentation/introduction/
- https://github.com/greenrobot/ObjectBox

**Comment by bkunters** [comment]
https://realm.io/products/realm-mobile-database/

**Comment by kordianbruck** [comment]
@bkunters http://kpgalligan.tumblr.com/post/133281929963/my-talk-at-droidcon-uk

realm is just like greenDAO (which is made by the same guys) - objectbox is a complete rewrite in native code.

**Comment by kordianbruck** [comment]
So this thing is still really unstable and segfaults at various occasions. I think this is too much of a change for this app for now. Might revisit soonish.
