### ISSUE TITLE
Mensa Garching not working properly 

### ISSUE THREAD

**Issue by AetherV** [TCA-Team/TumCampusApp#446]
## Steps to Reproduce

1. Open app
2. Look at Mensa Garching card
3. Also for following days

## Expected Result
Displaying only the menu
## Problem
http://m.imgur.com/A56kXb6
### Environment
* Phone: Samsung J7
* OS: 6.0.1 Android
* TUMOnline App: v1.4.7
* Language: English

**Comment by JohannesAck** [comment]
Looks similar in Stammgelände.

**Comment by xsrf** [comment]
fixed
