### ISSUE TITLE
App crashes when not able to download questions for the survey card

### ISSUE THREAD

**Issue by lnsp** [TCA-Team/TumCampusApp#453]
## Steps to Reproduce

1. Have no network connection
2. Fetch survey card questions
3. Crash and burn

## Expected Result
App should log the error and not display any survey cards.

## Actual Result
App crashes.

## Problem
Trying to get the size of a null-pointer list.

## Suggested Enhancement :sparkles:
Log and return when encountering an IOException in `getOpenQuestions()`.

### Environment
* Phone: Nexus 5
* OS: Android
* TUMOnline App: v1.4.8-dev
* Language: German

**Comment by kordianbruck** [comment]
Fixed in merged PR.
