### ISSUE TITLE
Google searching for Mensa menu

### ISSUE THREAD

**Issue by shayansiddiqui** [TCA-Team/TumCampusApp#458]
For every dish in the mensa menu we can give a search button which will direct to the google search of that dish (As people cannot select the text and search manually also. This very painful a for non german speaking student).

**Comment by kordianbruck** [comment]
@TCA-Team/android guys we need some feedback here - what do you think?

**Comment by mammuth** [comment]
Could be valuable. 
However I think it's important that this feature is not added too prominently to the UI, since it probably isn't valuable at all for most German speaking users.

**Comment by shayansiddiqui** [comment]
Ok. so instead of adding something to the UI we can make the text selectable so that users can manually search or translate it

**Comment by pfent** [comment]
I'm not a fan of search buttons 👎 

Probably the most idiomatic way on android would be to enhance the Google Now on Tap / Google Assistant capabilities.
This already somewhat works:
![googlenow](https://cloud.githubusercontent.com/assets/5686284/26378304/42803d40-4014-11e7-8c42-2771f6bbb99a.gif)


I'd love to someone implement the [Assistant API](https://developer.android.com/training/articles/assistant.html#assist_api), so we can have actually good results for this feature.

**Comment by tejaskale** [comment]
I suggested setting the text to selectable because I thought this would be the most painless way to integrate Google assistant. You can even directly do a translation or a websearch from the copy paste menu.

**Comment by kordianbruck** [comment]
@tejaskale did you look into the Google Assistant API?

**Comment by pfent** [comment]
But, yeah. Feel free to set the text selectable at any time. Just open up a PR for this. Maybe this even enhances Google Assistant enough to be useful

**Comment by kordianbruck** [comment]
Now on tap already solves this problem, but I've also made the text selectable - so double win.
