### ISSUE TITLE
Add PDF Viewer to App

### ISSUE THREAD

**Issue by t2m4k1** [TCA-Team/TumCampusApp#462]
Feature request disappeared. TCA app requires a PDF viewer, e.g. for the plan activity.

**Comment by kordianbruck** [comment]
Its back: https://github.com/TCA-Team/TumCampusApp/issues/368

Sorry, forgot to tell you guys. All the other issues are also visible again. Github fixed the issue.

**Comment by t2m4k1** [comment]
Oh thats nice! Could you provide Artem and me with backend access? I think thats the only thing left at the moment.

**Comment by kordianbruck** [comment]
Yea, I'm working with github to get a private organization repo. Hopefully they will reply soonish.

I didn't forget ;)
