### ISSUE TITLE
Campus Facilities Locator

### ISSUE THREAD

**Issue by shayansiddiqui** [TCA-Team/TumCampusApp#465]
At present TCA has a feature to locate rooms within various buildings of TUM campus however
there is no such functionality to locate other available facilities such as basketball courts, Fußball
table, table tennis, cafes, theatres, ATMs and library etc. present across the campus. Rather than
physically searching through the entire campus it will be helpful for the students to have such a
feature in the TCA itself.

This can achieved by letting the students tag locations across the campus and then others can find the same.

**Comment by shayansiddiqui** [comment]
Can we use the roomfinder to tag new locations as well or do we need to use google maps instead?

**Comment by kordianbruck** [comment]
You can do either. Google maps will be easier as you can rely on LAT/LON for the markers. For the custom maps you will need to save the pixel position in the image or you can come up with some other smart idea how to do this. 

I would prefer to have the Roomfinder maps, as they are more detailed in house.

**Comment by pfent** [comment]
archiving this @https://github.com/TCA-Team/TumCampusApp/releases/tag/stale%2FCourseRating
