### ISSUE TITLE
Search input / focus unclear

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#476]
## Steps to Reproduce

1. Tap Menü
2. Tap Roomfiner/Personensuche/MVV
3. (Tap "Search-Icon")

## Expected Result

There should be a visible / recognizable text input field with visible focus (e.g. flashing cursor)

## Actual Result

White screen with heading

## Problem

Instructions unclear

## Suggested Enhancement :sparkles:

Add flashing cursor / border on focus for search input

### Environment
* Phone: Nexus 5X
* OS: Android 7.1.2
* TUMOnline App: v1.4.8
* Language: de

**Comment by kordianbruck** [comment]
Yea, the cursor had the same color as the toolbar and was not visible :stuck_out_tongue:
