### ISSUE TITLE
Roomfinder: No result for N1190 and more

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#477]
## Steps to Reproduce

1. Tap "Menu"
2. Tap "Roomfinder"
3. Type "n1190"
4. Typ "go"

## Expected Result

A result

## Actual Result

No result

## Problem

Search not working for all rooms.
Also not working: "n1189", "n1070"
Working: "n1140", "1200"

## Suggested Enhancement :sparkles:

Since these rooms actually exist, giving a result would be nice

### Environment
* Phone: Nexus 5X
* OS: Android 7.1.2
* TUMOnline App: v1.4.8
* Language: de

**Comment by Yakuky** [comment]
It works when you type "1190" instead of "N1190"

**Comment by kordianbruck** [comment]
Works now. Fixed implemented on server.
