### ISSUE TITLE
eduroam setup suggested with wifi turned off

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#478]
## Steps to Reproduce

1. Setup "eduroam" with TCA
2. Disable Wifi on your device (location services must be allowed to use wifi)
3. Move to an area where "eduroam" is present

## Expected Result

nothing

## Actual Result

TCA suggests to setup "eduroam"

## Problem

TCA does not recognize that "eduroam" is already configured properly when wifi is turned off

## Suggested Enhancement :sparkles:

fix issue

### Environment
* Phone: Nexus 5X
* OS: Android 7.1.2
* TUMOnline App: v1.4.8
* Language: de

**Comment by kordianbruck** [comment]
Wait, are we talking about the notification or about the card on the start page?

**Comment by xsrf** [comment]
both

**Comment by kordianbruck** [comment]
Impossible: https://github.com/TCA-Team/TumCampusApp/commit/0b8b6706740ce035df6d7d4b30c67836784111c7

I've fixed it pre release. Verified it today - I got it shown on the startpage but not as notification

**Comment by xsrf** [comment]
okay okay, the last time I've seen the notification was last week, today I've only seen it on the start page ... haven't noticed the update ;)

**Comment by kordianbruck** [comment]
So you think we should remove it on the start page as well?

We have two cards. EduroamCard and EduroamFixCard - which one was shown?

**Comment by kordianbruck** [comment]
Add implementation on https://github.com/TCA-Team/TumCampusApp/tree/feature/478-hide-card

Waiting for feedback...

**Comment by xsrf** [comment]
How am I supposed to know how you name the cards? ;)
The card should never be shown when eduroam is already configured (correctly). Since you're unable to tell if eduroam is configured correctly when wifi is turned off (at least I think that is the cause of the problem), the card should never show up when wifi is turnd off.

**Comment by kordianbruck** [comment]
mimimimim.

Done.
