### ISSUE TITLE
Link "Studienfinanzierung" dead

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#479]
## Steps to Reproduce

1. Tap "Menu"
2. Tap "Rückmeldung"
3. Tap "Studienfinanzierung"

## Expected Result

Website should open?!

## Actual Result

nothing happens

## Problem

see above

## Suggested Enhancement :sparkles:

see three above

### Environment
* Phone: Nexus 5X
* OS: Android 7.1.2
* TUMOnline App: v1.4.8
* Language: de

**Comment by kordianbruck** [comment]
Fixed
