### ISSUE TITLE
Plans outdated

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#481]
## Steps to Reproduce

1. Tap "Menu"
2. Tap "Pläne"

## Expected Result

List of valid up to date plans

## Actual Result

"MVV Schnellbahnnetz" is outdated
"MVV Nachtliniennetz" is outdated
"MVV Tramnetz" is outdated
"MVV Gesamtnetz" says "Invalid file format, contact admin..."
"Stammgelände" is missing Bus-Lines 100/150. 53 should be 153/154, Tram 27 is 27/28; Südgelände was broken down almost 10 years ago.

## Problem

plans outdated

## Suggested Enhancement :sparkles:

update plans

### Environment
* Phone: Nexus 5X
* OS: Android 7.1.2
* TUMOnline App: v1.4.8
* Language: de

**Comment by kordianbruck** [comment]
For future reference: 
```
convert *.jpg -evaluate-sequence median OUT.jpg
```

to remove the markers, take three different versions of the same map with each having markers for other rooms. Then use the above command to remove the marker from the map.
