### ISSUE TITLE
Reminder Service for the tuition fees

### ISSUE THREAD

**Issue by bkunters** [TCA-Team/TumCampusApp#482]
we can build a reminder service so that the students are notified after a specific time,if a fee has to be paid until a deadline.
**Why might we need it ?**
The students are concentrated to their studies and the payment can be overlooked as the students are not notified by the campus tum through an email.

**Comment by kordianbruck** [comment]
Good idea! We already have the Card on the start page, but it would be smart to have some notifications as well. Like 14, 7 and 3 days before the due date or something.

**Comment by pfent** [comment]
This is worked on by @thellmund in #879

**Comment by thellmund** [comment]
Implemented in #879.
