### ISSUE TITLE
Not Talkback friendly

### ISSUE THREAD

**Issue by Yakuky** [TCA-Team/TumCampusApp#483]
## Steps to Reproduce

1. Open Talkback
2. Open setting menu
3. Open a subsetting menu
4. Tap somewhere where exists an item in the previous screen

## Expected Result
Talkback read the current item in current screen.

## Actual Result
Talkback read the item in the previous screen.

## Problem
It seems that talkback also selects invisible items.

### Environment
* Phone: 
* OS version: 
* TUM Campus App version: v1
* Language:

**Comment by Yakuky** [comment]
@kordianbruck 
This problem is already fixed by my previous PR.
You can close this one.

**Comment by kordianbruck** [comment]
@Yakuky thanks!
