### ISSUE TITLE
eduroam setup focus on pw input

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#484]
## Steps to Reproduce

1. Use TCA without TUM Account associated 
2. delete eduroam configuration if already present
3. Tap TCAs eduroam wizard 

## Expected Result

First input field (TUM-Kennung) should have focus

## Actual Result

Second field (Passwort) has focus

## Problem

That's confusing

## Suggested Enhancement :sparkles:

Set focus to first empty field (TUM-Kennung, if no TUM-Kennung is present).

### Environment
* Phone: Nexus 5X
* OS version: 7.x
* TUM Campus App version: v1.4.8
* Language: de

**Comment by kordianbruck** [comment]
Implemented. Will be releases soonish.
