### ISSUE TITLE
eduroam setup should validate inputs

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#485]
## Steps to Reproduce

1. Use eduroam setup
2. Type "some crap@stupid.domain" into "TUM-Kennung"
3. Tap "Einrichten"

## Expected Result

Inputs should be validated and an error message should be shown

## Actual Result

Setup says "Eduroam erfolgreich eingerichtet" regardless what crap u enter into the input fields. They even may be empty.

## Problem

Bad user experience

## Suggested Enhancement :sparkles:

- Validate TUM-ID against [a-z]{2}[0-9]{2}[a-z]{3} 
- Check that password is present

### Environment
* Phone: Nexus 5X
* OS version: 7.x
* TUM Campus App version: v1.4.8
* Language: de

**Comment by kordianbruck** [comment]
You are probably right, that this would be a good addition.

**Comment by kordianbruck** [comment]
Implemented. Will be released soonish.
