### ISSUE TITLE
update eduroam anonymous identity

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#488]
## Problem

eduroam fails to connect on some Access-Points since mid June with anonymous identity "anonymous@mwn.de", which results in bad connectivity on places where affected Access-Points are around (suspectedly Alcatel brand APs).

## Suggested Enhancement :sparkles:

Update eduroam configuration to "anonymous@eduroam.mwn.de" for anonymous identity, which is the recent official configuration anyway.

**Comment by kordianbruck** [comment]
Implemented. Should be released soonish
