### ISSUE TITLE
Eduroam setup does not detect PIN

### ISSUE THREAD

**Issue by jvanbruegge** [TCA-Team/TumCampusApp#489]
## Steps to Reproduce

1. Open Eduroam setup
2. Enter credentials
3. Hit ok

## Expected Result
Eduroam setup completes
## Actual Result
Error: No PIN
## Problem
I have a Pin configured already

### Environment
* Phone: OnePlus 3
* OS version: Android CM 6.0.1
* TUM Campus App version: v1.4.8
* Language: German

**Comment by kordianbruck** [comment]
Thanks for the report. Do you already have the eduroam profile configured? If yes, please delete it prior to creating the new one.

**Comment by jvanbruegge** [comment]
This did the trick. Maybe mention that in the text?

**Comment by kordianbruck** [comment]
Done. Thanks!
