### ISSUE TITLE
Add eduroam setup to menu

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#493]
## Problem

After having changed the TUM accounts password, eduroam fails to connect, but I have no ability to re-configure the new password (except manually deleting the profile and start over again).

Sometimes I also feel like I would like to configure eduroam at home, where no eduroam wifi is around.

## Suggested Enhancement :sparkles:

Add eduroam setup to the menu, so eduroam can be (re-)configured whenever I want to.

### Environment
* TUM Campus App version: v 1.4.9

**Comment by kordianbruck** [comment]
I mean yea. Problem is that whenever we add a menu entry it really should be necessary. It decreases visibility of the other items and increases complexity for the user. 
So I don't think the menu is the right position for this. Any other ideas where to put this?

**Comment by xsrf** [comment]
Being able to change the eduroam password after you changed it for your TUM account is necessary...

Sure, you can popup the eduroam setup only when you shake your smartphone, then flip it three times within 5 seconds while pointing to the south and then swipe up on your display while praying to the eduroam gods... but... maybe an entry right next to "Startup-Wizard" and "In-App-Tutorial" (which is way more unnecessary than configuring eduroam) would be the more obvious choice.

Also, if you're worried about the usability of the menu... Make a submenu for all the cards visibility settings ;)

**Comment by pfent** [comment]
@xsrf Agreed!
Settings is a good place for this, instead of the left drawer menu.
When we're on it, we can probably also remove some of the unnecessary stuff from the settings you mentioned 👍

**Comment by kordianbruck** [comment]
Yea, lets get rid of the tutorial.

**Comment by kordianbruck** [comment]
- [ ] Add button to open activity to settings menu
- [ ] Add Explanation text about the card
