### ISSUE TITLE
Eduroam: guest mode

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#494]
@xsrf this is a question really for you, as you know this best:

would it make sense to have an option for a guest to enter a 5 digit code and have the wifi configured for him? So we could fetch the login data from TUMonline or something and automatically configure eduroam.

Yes/No/Maybe?

**Comment by xsrf** [comment]
So you want an API that returns the users credentials just by entering a 5 digit number? sounds great!

But... No. Why not use @BayernWLAN if you cannot remember your credentials?

**Comment by kordianbruck** [comment]
So after some discussion we concluded that the guest system currently in place is not to be used in the future. So this idea of simplifying access to WiFi for guests is obsolete.
