### ISSUE TITLE
Schedule in Roomfinder does not work properly

### ISSUE THREAD

**Issue by Yakuky** [TCA-Team/TumCampusApp#498]
## Steps to Reproduce
Backend provides API in form of api/roomfinder/room/scheduleById/RoomId/yyyymmdd/yyyymmdd
And then it returns every schedule of this room between the 2 days.
  
However, what frontend requests is api/roomfinder/room/scheduleById/RoomId/millisecondsInEpoch/millisecondsInEpoch

So the result is always empty.

Besides, frontend always requests 3 times for one room, which is not necessary.

### Environment
* Phone: 
* OS version: 
* TUM Campus App version: v1
* Language:

**Comment by kordianbruck** [comment]
Dupe of #431 

Thanks for opening this issue tho ;)
