### ISSUE TITLE
Current B.Sc. Informatik study plan missing (WS1617)

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#517]
And Informatik WS1213 error 404

**Comment by jacqueline8711** [comment]
Informatik WS1213:
http://www.in.tum.de/fuer-studierende/bachelor-studiengaenge/informatik/studienplan/studienbeginn-ab-ws-20122013-bis-sommersemester-2016.html
Informatik WS1617:
http://www.in.tum.de/fuer-studierende/bachelor-studiengaenge/informatik/studienplan/studienbeginn-ab-ws-201617.html

**Comment by kordianbruck** [comment]
Updated.
