### ISSUE TITLE
'News' filtering options closing after one click

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#527]
Annoying if you want to (de-)select multiple news sources

**Comment by pfent** [comment]
A quick search shows, that [an OptionsMenu is probably not the right fit for this](https://stackoverflow.com/questions/42931293/prevent-options-menu-from-closing-on-optionitemselected). Maybe migrate to a Dialog as suggested in that Stackoverflow answer...
