### ISSUE TITLE
Use EAP-PWD for eduroam

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#530]
LRZ now supports EAP-PWD for eduroam authentication. EAP-PWD is secure, only needs username and password, does not need any certificate and thus also does not force you to enable PIN lock on your phone to use it.
https://www.lrz.de/services/netz/wlan/anleitungen/android-pwd/

EAP-PWD should be used as preferred method for setting up eduroam.

**Comment by xsrf** [comment]
Shouldn't setSubjectMatchAPI23() / setSubjectMatch18To23() be removed from
[setupEnterpriseConfigAPI18](https://github.com/jacqueline8711/TumCampusApp/blob/c28773087a4adce1022b1aa3e6f8d16675d732d9/app/src/main/java/de/tum/in/tumcampusapp/managers/EduroamManager.java#L134) ? There is no certificate and thus no domain name to check with EAP-PWD.

**Comment by kordianbruck** [comment]
@xsrf rein logisch muss man sich ja immer noch mit unserem radius verbinden. Dafür ist der subject match ja vorgesehen.

**Comment by kordianbruck** [comment]
Ach, nochmal nachgeschaut: https://www.dfn.de/fileadmin/3Beratung/Betriebstagungen/bt64/BT64_MobileIT_EAP-PWD_Lawendy.pdf
Werden ja gar keine Zertifikate mehr verwendet. Na, dann können wirs wohl raus schmeißen.
