### ISSUE TITLE
Missing eduroam realm treated as insecure configuration

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#531]
TCA treats any eduroam configuration with missing realm as insecure configuration and alarms the user. A missing realm (username "go42tum" instead of "go42tum@eduroam.mwn.de") is not a security threat and shouldn't be treated as such.

**Comment by pfent** [comment]
A missing realm is still a wrongly configured connection, that doesn't work when roaming.
While this is not a security threat, we should still prompt the user to update his configuration.
Probably prompt the user with a less intimidating message in that case?

**Comment by kordianbruck** [comment]
Yea, I would vouch for a different text maybe in that case, but its still not 'correct' per se.
