### ISSUE TITLE
Enhance the calendar

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#534]
We regularely get complaints, that clicking on items in the calendar currently does nothing. Maybe create a detailed view for that entry?

Detailed information should be available in the CalendarRow model, we just need to display it.

We can also ponder to switch to another library, [Material Calendar View](https://github.com/prolificinteractive/material-calendarview) seems to have a WeekView, which might looks and scrolls a bit nicer than the solution we have right now

**Comment by kordianbruck** [comment]
MCV seems to be dead since may: https://github.com/prolificinteractive/material-calendarview/graphs/contributors

**Comment by pfent** [comment]
Well, Android Week View (which we are using right now) is effectively dead since more than a year :crying_cat_face: 
https://github.com/alamkanak/Android-Week-View/graphs/contributors
