### ISSUE TITLE
Rethink caching / rework CacheManager

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#544]
Maybe as a separate issue from [the iOS issue](https://github.com/TCA-Team/iOS/issues/156)

Our current approach to caching with hard-coded validities which don't respect cache headers, if there are any issn't optimal.
For okhttp, there is an [official guideline](https://github.com/square/okhttp/wiki/Recipes#response-caching) for simple HTTP header controled caching, maybe we can override this behaviour in some contexts and specify our own cache durations by extending the default cache.

**Comment by kordianbruck** [comment]
@thellmund @pfent are we done here? Should we add more caching headers? Maybe in the backend?

**Comment by pfent** [comment]
We might want to [monitor the network traffic manually](https://developer.android.com/topic/performance/power/network/gather-data) and see, if there is any remaining unexpected traffic...

**Comment by kordianbruck** [comment]
Sure, sounds like a great idea, lets open a separate issue for that. Closing this for now.
