### ISSUE TITLE
Access Token configured properly, "Identity could not be accessed"

### ISSUE THREAD

**Issue by Taxel** [TCA-Team/TumCampusApp#554]
This is not a bug I can reproduce on different phones but an issue that keeps me from using the app at all, so hopefully this is the right place to submit it ;)
Everything worked fine on the same phone before, then I reset it. I also applied the latest Android security patch (Oxygen 3.6.0 -> 3.6.1, Krack fixed) before installing it, but this looks more like a problem on TUM Online's side (at least I tried it ~10 times by now with the same result every time):

## Steps to ~~Re~~produce

1. Installed the App via Google Play
2. Started App, Startup Wizard is shown
3. Entered my LRZ ID, faculty informatics, tapped "Next"
4. In the browser, checked all five token rights, activated token
5. Tried to leave setup step 2 by tapping "Next" again

## Expected Result
The next step

## Actual Result
"Identity could not be accessed. Please check the rights of your TUMonline token" (Toast)

## Problem
When skipping this step and tapping "Go to TUM campus app" the following toast appears:
"Something is wrong with your chat registration", independent which boxes I check.

### Environment
* Phone: OnePlus 2
* OS version: Oxygen OS 3.6.1 (Android v. 6.0.1)
* TUM Campus App version: v1.4.9
* Language: English

**Comment by pfent** [comment]
Could you by any chance provide a logcat report for this issue?
Debugging this without more info will probably be hard...

**Comment by pfent** [comment]
@Taxel don't worry, I just reproduced the issue. Fixing it very soon

**Comment by kordianbruck** [comment]
@Taxel did you build the app yourself or did you download it from the play store?

**Comment by Taxel** [comment]
I downloaded it from the play store.

On Nov 8, 2017 17:45, "Kordian Bruck" <notifications@github.com> wrote:

@Taxel <https://github.com/taxel> did you build the app yourself or did you
download it from the play store?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TCA-Team/TumCampusApp/issues/554#issuecomment-342878106>,
or mute the thread

**Comment by pfent** [comment]
Well @kordianbruck, then it seems there was a braking change at TUMonline...

**Comment by kordianbruck** [comment]
This ain't fixed then?

**Comment by pfent** [comment]
well, could be that simplexml gets confused with the additional fields in the Identity.

nevertheless, I fixed it in the current master, we just need to do a release 🙈

**Comment by kordianbruck** [comment]
@pfent are we sure we can release the kotlin code? =S

**Comment by kordianbruck** [comment]
Here is the fix for simplexml: https://stackoverflow.com/questions/4740934/how-to-ignore-unused-xml-elements-while-deserializing-a-document

**Comment by pfent** [comment]
@kordianbruck wanna release a quickfix for [1.4.9](https://github.com/TCA-Team/TumCampusApp/tree/1.4.9) or just release the 1.5.0 soon?

**Comment by pfent** [comment]
Let's see if I can fix #561 today, apart from that, that kotlin code should be ready

**Comment by kordianbruck** [comment]
Kay. Doing the deployment now.
