### ISSUE TITLE
Single results in PersonSearch should proceed to PersonDetails

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#558]
## Steps to Reproduce
Search for "Kordian" in the PersonSearch

## Expected Result
Directly proceed to the profile of @kordianbruck 

## Actual Result
A single result is displayed

## Suggested Enhancement :sparkles:
Save that one precious tap and directly proceed to the result

**Comment by kordianbruck** [comment]
Done in https://github.com/TCA-Team/TumCampusApp/pull/579
