### ISSUE TITLE
Use Googles Room Persistency Library

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#560]
We currently don't have an ORM, but write all SQL queries / mappings by hand.

Google recently released the [Android Architecture Components](https://developer.android.com/topic/libraries/architecture/index.html) with the [Room Persistency Library](https://developer.android.com/topic/libraries/architecture/room.html). We should probably use this, which should significantly reduce the complexity of our various "Managers"

**Comment by kordianbruck** [comment]
@pfent allowMainThreadQueries() :+1:

**Comment by kordianbruck** [comment]
Overview: https://speakerdeck.com/hugovisser/room-the-blessed-object-mapper-devfest-bayern

**Comment by pfent** [comment]
Migrate Managers to use entities and DAOs:
- [x] CafeteriaManager
- [x] CafeteriaMenuManager
- [x] KinoManager
- [x] LocationManager
- [x] OpenHoursManager
- [x] SyncManager
- [x] TumManager
- [ ] Calendar Manager
- [ ] CardManager
- [ ] ChatMessageManager
- [ ] ChatRoomsManager
- [ ] NewsManager
- [ ] NotificationManager
- [ ] RecentsManager
- [ ] StudyRoomGroupManager
- [ ] SurveyManager
- [ ] TransportManager
- [ ] WifiMeasurementManager

Misc:
- [ ] Migrations / replacement for `AbstractManager.resetDb()`
- [ ] Use a proper DB abstraction for `EnhancedSearchRecentSuggestionsProvider`
- [ ] Strategy to replace MainThread queries with LiveData / Background Thread

**Comment by OliHalu** [comment]
@anselm92 @psukys I allready work on ChatMessageManager, ChatRoomsManager and CalenderManager

**Comment by anselm92** [comment]
@pfent @kordianbruck 
Regarding the strategy to replace main thread queries, i'd suggest using rxandroid (or rxjava in case of persistence api), I've used it many times before and love it :)

See: https://medium.com/google-developers/room-rxjava-acb0cd4f3757

Advantages: 
- It's included in the room persistence api
- It's quite easy to use. 

I'll implement it for one dao, to show how to use it.

**Comment by kordianbruck** [comment]
@anselm92 what are the benefits over using livedata?

**Comment by anselm92** [comment]
Basically:
+ Transformations are done on the background thread
+ Provides way more functional operations

Are we going to need it? Idk, i thinks it's more a matter of taste

See:
[https://stackoverflow.com/questions/46312937/when-to-use-rxjava-in-android-and-when-to-use-livedata-from-android-architectura](https://stackoverflow.com/questions/46312937/when-to-use-rxjava-in-android-and-when-to-use-livedata-from-android-architectura)
[http://akarnokd.blogspot.de/2017/10/android-livedata-api-quick-look.html](http://akarnokd.blogspot.de/2017/10/android-livedata-api-quick-look.html)
[http://hannesdorfmann.com/android/arch-components-purist](http://hannesdorfmann.com/android/arch-components-purist)

**Comment by pfent** [comment]
I'd say go for it.

Rxjava would probably also be great for a lot of the Networking stuff, where we currently use AsyncTasks

Building a common rxjava usage pattern for database and network access will award you all the kudos :)

**Comment by anselm92** [comment]
Alright, I've refactored the first manager (CafeteriaManager) into a viemodel approach with rxjava. (It already works, but it's still more a draft.)

Please have a look and tell me what you think about it:

https://github.com/TCA-Team/TumCampusApp/commit/c24e3996369947d7312ef38c73721ffdd691646b

**Comment by psukys** [comment]
I like the rxjava approach. I'mma converting NewsManager at the moment.

**Comment by psukys** [comment]
I haven't added rxjava (even tho PR is still big), will move into DAOizing *Calendar manager* as *NewsManager* is ready for review

**Comment by kordianbruck** [comment]
@TCA-Team/android three left to go :tada:

**Comment by psukys** [comment]
@OliHalu I take the SurveyManager then
