### ISSUE TITLE
Roomfinder does not find rooms with spaces

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#562]
## Steps to Reproduce

1. Open Roomfinder
2. Search for: "00.04.011, MI Hörsaal 2"

## Result
No room found

## Problem
The roomfinder does not find rooms with spaces. searching for "00.04.011" finds the room.

## Suggested Enhancement :sparkles:
Investigate, why spaces cause this problem. Maybe we need to specially encode them? Maybe we sould replace the spaces with wildcards?

**Comment by kordianbruck** [comment]
This probably is a backend issue and relates to us actually not doing a fuzzy db search. As either value reside in a separate column and no fulltext functionality is used.

**Comment by pfent** [comment]
Hm, then we should probably split up the query at spaces...

**Comment by kordianbruck** [comment]
Or use elasticsearch / solr or fulltext search

**Comment by kordianbruck** [comment]
This has been fixed by @foreverigor - thanks again.
