### ISSUE TITLE
Fix TU Kino

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#565]
Currently the activity is empty and shows no information. Check why, fix and write unit tests.

**Comment by psukys** [comment]
@kordianbruck , [KinoManager's sync request](https://github.com/TCA-Team/TumCampusApp/blob/548ed15f30e83db6c3fe509dd1332d1874bf4d5a/app/src/main/java/de/tum/in/tumcampusapp/managers/KinoManager.java#L66) returns movies up until 2017 February, is this intended?

**Comment by pfent** [comment]
@psukys This can't be. I see a movie for 14.11.2017 right on the start page.

The problem is rather, that the KinoActivity does not show anything when clicking on that card on the MainActivity.

**Comment by kordianbruck** [comment]
@pfent there are two endpoints. TU Kino gets pull from the news endpoint plus there is a separate TU Kino endpoint. I think @psukys is talking about the latter right?

**Comment by pfent** [comment]
Oh my... 🤦‍

I think the bug is, that we have two separate endpoints, that might be out of sync to begin with...

**Comment by kordianbruck** [comment]
Yes they are out of sync, as the second endpoint uses the data from the news to fetch additional data from imdb and stuff. @psukys do you want to have a look at the backend?

**Comment by psukys** [comment]
@kordianbruck sure, tho I'm still figuring out card's endpoint retrieval workflow

**Comment by psukys** [comment]
Unfortunately, I wasn't able to trace the second movie endpoint, tho it certainly exists.
Database-wise, the newer movies are added to *news*, the old ones (~70 movies) are added to *kino* table and later [pruned](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/managers/KinoManager.java#L48)

@kordianbruck can you point me into how/where the second endpoint is functioning?

**Comment by pfent** [comment]
@psukys the second endpoint is probably referenced in the NewsManager

All other endpoints should be referenced in the [TumCabeClient](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/api/TUMCabeClient.java#L58), but we never finished porting the News / Kino to retrofit...

**Comment by kordianbruck** [comment]
No, it should be directly in the KinoManager or KinoDetailsActivity.

**Comment by psukys** [comment]
@pfent @kordianbruck , so my initial guess on this is:

1. Kino cronjob is not running

  - the Kino external source RSS is functional and returns as expected
  - crontab doesn't have `kino` type

2. Backend has an old snapshot from 2017 February (or the cronjob was stopped back then)

3. News cronjob is running and working well

  - News cronjob fetches **all** news (from all news sources)
  - Fetched news are saved with their sources as ids (some integer)

4. Android app fetches Kino news, that are old and [gets pruned as they're old](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/managers/KinoManager.java#L47)

5. News (including the new movies) are fetched and [in NewsAdapter switched between](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/adapters/NewsAdapter.java#L97) either being FilmCard or NewsCard.

quick workaround would be enabling cronjob should fix the thing; longer - reviewing the workflow and structure (maybe use just a single endpoint)

**Comment by kordianbruck** [comment]
@psukys the Kino cronjob is actually still bein run, but probably fails. Did you try to run it manually? It fetches from several other sources as imdb to get all information. I will need to check the server logs, but right now they are not easily accessible unfortunately.

**Comment by psukys** [comment]
Will check the backend  cronjob that is responsible for fetching the movies.

As well, I've noticed that there's layout for when there are no movies and this is as well not triggered in the TCA app (layout/layout_no_movies.xml). Was this working before or just a draft for future? When debugging, the TCA app works as expected, prunes all movies which are in the past, thus, I believe, the layout_no_movies should be utilized.

**Comment by psukys** [comment]
Possible solution https://github.com/kordianbruck/tca-backend/pull/12

**Comment by kordianbruck** [comment]
@psukys thanks, it worked just great. If you can now still fix the no movies layout, I would be happy :heart: 

Good Work!
