### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#568]
Now that we have unit tests, we should also be made aware how bad the situation is.

Lets have Jenkins also calculate the code coverage.

**Comment by kordianbruck** [comment]
Parent Issue: #356

**Comment by psukys** [comment]
I suppose [JaCoCo](https://docs.gradle.org/current/userguide/jacoco_plugin.html) needs to be within gradle configuration. Can look into this

**Comment by psukys** [comment]
There's a lot of confusing documentation around this, I'll try to get a minimal working sample. Maybe we could integrate coverage information into codacy, since we're using it right now, @kordianbruck

**Comment by kordianbruck** [comment]
@psukys no, this should run as part of the gradle build and publish the results within jenkins. Codacy and other external tools are really unreliable. As you've seen in several PRs those tests might run, or not.
Please add some config files and modify the build target to produce a report.

Haven't look at it in depth, but this might help:
https://www.coshx.com/blog/2015/03/31/android-continuous-integration-using-gradle-android-studio-and-jenkins/

Please only implement it, if it is simple and does not obstruct the build.
