### ISSUE TITLE
Chat Room Activity does not have the drawer / up button

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#572]
Should be added using the base class

**Comment by kordianbruck** [comment]
@OliHalu this should be a quick fix probably? Can you do this till thursday?

**Comment by OliHalu** [comment]
@kordianbruck looks like there is already a drawer / up button in the ChatRoomActivity of the current master branch

**Comment by kordianbruck** [comment]
Cool, then this issue can be closed. Thanks.
