### ISSUE TITLE
Chat Room Activity does not show history

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#573]
Whenever you leave the room and reenter it, it now longer displays the previous messages

**Comment by OliHalu** [comment]
It looks like the Cursor we create in the `getNextHistoryFromServer(final boolean newMsg)` method is closed before the message history is retrieved. Deleting `cur.close()` will solve the problem that the message history is not shown. But I think the cursor needs to be closed somewhere to avoid memory problems right?

**Comment by kordianbruck** [comment]
@OliHalu ok, if that really the problem (I couldn't verify this in a quick debug session) please start migrating the Chat to the room persistency library and merge that into philipps branch (Create a PR for this). 
You guys really need to get going! :alarm_clock:
