### ISSUE TITLE
Calendar does not display past events

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#574]
It should not delete those, so one can actually go back

**Comment by kordianbruck** [comment]
@psukys is there any development on this? Done? Do we still purge the db on upgrade?

**Comment by psukys** [comment]
Haven't checked this in a while, only on when making CalendarManager DAO and then I couldn't find clear indicators of this behaviour, will look into this after I've resolved the fishy test db date issue (#640)

**Comment by kordianbruck** [comment]
As we now go two months backwards, this should no longer be a problem. Still a proper paging might be interesting in the future..
