### ISSUE TITLE
Can't setup tumonline account in startup wizard 

### ISSUE THREAD

**Issue by anselm92** [TCA-Team/TumCampusApp#576]
## Steps to Reproduce

1. Fresh install
2. Create token and grant all rights in tumonline
3. Click next

## Expected Result

Get to next screen

## Actual Result

Error: Identity could not be accessed. Please check the rights of your TUMonline token

## Problem

I can't get past step 2 in the startup wizard

See [stacktrace.txt](https://github.com/TCA-Team/TumCampusApp/files/1461010/stacktrace.txt)

### Environment
* Phone: HTC 10
* OS version: Android 7.0
* TUM Campus App version: v1.5
* Language: English

![screenshot_20171110-112407](https://user-images.githubusercontent.com/7032584/32654326-120b8d54-c60b-11e7-8bbf-702b189f7f77.png)
![screenshot_20171110-112421](https://user-images.githubusercontent.com/7032584/32654327-1223c9b4-c60b-11e7-908b-6737b1a3f62a.png)

**Comment by kordianbruck** [comment]
Please add the fix from #554 
" Here is the fix for simplexml: https://stackoverflow.com/questions/4740934/how-to-ignore-unused-xml-elements-while-deserializing-a-document "

But the model should also have defaults for all of the identities. Great issue to start. Should not take longer to fix than 5 minutes anselm ;)

**Comment by anselm92** [comment]
@kordianbruck  Jenkins does not run the new kotlin test. It works locally:

$ ./gradlew :app:test
[...]
de.tum.in.tumcampusapp.models.tumo.IdentityTest > testParsingXML PASSED
----------------------------------------------------------------------
|  Results: SUCCESS (26 tests, 26 successes, 0 failures, 0 skipped)  |
----------------------------------------------------------------------
:app:test
BUILD SUCCESSFUL in 32s

**Comment by kordianbruck** [comment]
@anselm92 yes, I know. Somehow the gradle build does not always clear the caches somehow. Its really weird. I will have to track this down one day.
