### ISSUE TITLE
SonarQube

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#586]
Parent Issue: #356

So for our iOS repository we already have this. (See comments from TCA-bot here: https://github.com/TCA-Team/iOS/pull/209)

Maybe we can copy the settings? https://github.com/TCA-Team/iOS/blob/master/sonar-project.properties

Heres how to setup the scanner in jenkins: https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Jenkins
(I can setup an account for you on jenkins - write me a mail)

Checkout the dashboard here: https://sonarcloud.io/dashboard?id=de.tum.in.www.Tum-Campus-App

**Comment by psukys** [comment]
In general, apart from the fact that it uses separate tooling, sonarqube for us would as well offer security vulnerability and code duplication analysis (and other functions would more or less overlap). Yay/nay, @kordianbruck  @pfent ?

**Comment by kordianbruck** [comment]
@psukys what is involved in maintaining it? Do we need some extra service? Or is it a simple gradle task?

**Comment by kordianbruck** [comment]
https://pmd.github.io/pmd-6.1.0/pmd_userdocs_cpd.html 
Maybe you can check if we can get that working?

**Comment by kordianbruck** [comment]
https://github.com/aaschmid/gradle-cpd-plugin

**Comment by kordianbruck** [comment]
Otherwise if it is too complicated, we can surely use sonar instead - its a industry standard by now pretty much
