### ISSUE TITLE
Do you guys include OS Build and App Version in Support ticket mails?

### ISSUE THREAD

**Issue by TG908** [TCA-Team/TumCampusApp#588]
I have the feeling that only ios implements that or some users keep deleting it.

**Comment by kordianbruck** [comment]
@TG908 no, currently not. We are planing to revamp the feedback button in the app shortly. @jacqueline8711 will actually work on this as her first task :+1: :grinning:

**Comment by kordianbruck** [comment]
@jacqueline8711 wir sollten das bitte in die Feedback Option mit aufnehmen.

**Comment by jacqueline8711** [comment]
@kordianbruck as an option (CheckBox) or should we just always send it?

**Comment by kordianbruck** [comment]
just always send it - should not be a problem

**Comment by pfent** [comment]
@kordianbruck don't we already include the App Version with `X-AppVersion` or something?

**Comment by kordianbruck** [comment]
Yes, with the debug reports, not with the feedback requests, which we just added.
