### ISSUE TITLE
Check codeclimate tool for QA

### ISSUE THREAD

**Issue by psukys** [TCA-Team/TumCampusApp#602]
Is free for open source projects. It has some nice plugins (such as using Sonar) and other tools. The part I like most is determining tech debt  and estimates on fixing issues. As an example, see https://codeclimate.com/github/shookees-TUM/kaldi-gstreamer-server

[1] - https://codeclimate.com

**Comment by kordianbruck** [comment]
@psukys what are the advantages over Codacy? 
According to this, it ain't really that much better: https://www.netguru.co/blog/comparison-automated-code-review-tools-codebeat-codacy-codeclimate-scrutinizer

CodeBeat might be worth a try?

**Comment by kordianbruck** [comment]
I think we are rolling pretty well with the stuff we already have. Integrating third party tools often results in not working hooks. Our Jenkins works 99% of the time - good enough for now. Tech debt and estimates are more bullshitty values, that don't give us any merit. Fix bugs/problems when you encounter them.

Thanks for the suggestion though!
