### ISSUE TITLE
Quiz: Remove or Improve

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#603]
* Add explaination what it is.
* Fix it
* Or remove it

**Comment by psukys** [comment]
So far, what's needed to review:

1. Move layout from code to XML (from SurveyActivity.java)
2. Review logic and simplify (ugly if pyramid for getting answer amount)

**Comment by xsrf** [comment]
Can someone explain me what this "Quiz", which is called "Survey" when you open it, is? I don't get it.
Also took me a while to find the white borderless input field(s) for the question on the white background.

**Comment by psukys** [comment]
@xsrf in short, quick surveying over all TCA users.
