### ISSUE TITLE
Switch AndroidWeekView forks

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#630]
The original [AndroidWeekView](https://github.com/alamkanak/Android-Week-View) isn't really maintained anymore. I just dug through the issues and now there seems to be a [actively maintained fork of the library](https://github.com/Quivr/Android-Week-View) by a Belgian student app...

Seems like no really breaking changes so far, but with more features.

**Comment by kordianbruck** [comment]
I've switched to the fork my branch. Seems to work solidly. More testing is welcome
