### ISSUE TITLE
Reintroduce Grading system

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#64]
Need to check with the TUMO developers to see if they fixed the API issue

**Comment by nilstk** [comment]
Since we might introduce the usage of credentials within the TCA for other reasons anyway and since TUMonline won't fix the issue anytime soon, we might think about reintroducing the old (never released) webpage-parsing approach (cf. TCA 2012 by V. Dolle, D. Mary etc.)

**Comment by kordianbruck** [comment]
@nilstk we don't currently use the credentials.

**Comment by kordianbruck** [comment]
Got added with the lastest release.
