### ISSUE TITLE
NewsDaoTest.cleanUpOldTest sometimes failing

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#640]
see the build server:
https://server4.wdkk.de/job/TCA-Android/269/testReport/de.tum.in.tumcampusapp.database.dao/NewsDaoTest/cleanUpOldTest/

**Comment by psukys** [comment]
Interestingly, it seems that database contains an entry with time 00:00:00 while the test does not explicitly set it so. Will check the routines for date handling [for the test](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/test/java/de/tum/in/tumcampusapp/database/dao/NewsDaoTest.java#L57)

**Comment by psukys** [comment]
Interestingly, it seems that database contains an entry with time 00:00:00 while the test does not explicitly set it so. Will check the routines for date handling [for the test](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/test/java/de/tum/in/tumcampusapp/database/dao/NewsDaoTest.java#L57)
