### ISSUE TITLE
Not all rooms shown till refreshed

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#659]
Happens every time I open the chatrooms activity. Before the refresh only 2-3 rooms are shown. After refresh I get all the rooms (20+)

**Comment by OliHalu** [comment]
@kordianbruck are 2-3 rooms of 'My Chatrooms' shown or the rooms which belong to the lecture the user attends?

**Comment by kordianbruck** [comment]
of 'My Chatrooms' - all of the current semester are missing somehow.

**Comment by anselm92** [comment]
I tested this on 1.5.1, happens there too. so this is an old bug

**Comment by kordianbruck** [comment]
Still, this should be fixed if possible in a reasonable time

**Comment by kordianbruck** [comment]
Fix in PR.
