### ISSUE TITLE
Easter Egg

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#660]
https://github.com/TCA-Team/iOS/pull/224

**Comment by jacqueline8711** [comment]
@kordianbruck in the iOS issue it says it changes when tapping on the tum logo, so I guess when tapping on the ActionBar (on the main screen)?

**Comment by kordianbruck** [comment]
We don't have the TUM Logo in the Toolbar/ActionBar on the main screen yet. 

No, the Idea was to have it during the startup screen, where we show the offical TUM logo for a few seconds.

**Comment by psukys** [comment]
Agree, with time it could build up even more variations, supposedly time-of-year theming as well
