### ISSUE TITLE
Startup-Wizard stuck when TUM-ID failed

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#663]
## Steps to Reproduce

1. Open "Startup-Wizard"
2. enter "test" as TUM-ID
3. press "WEITER"

## Problem

You're stuck now. You won't be able to use the app until you either enter a valid TUM-ID or delete the app data. "ÜBERSPRINGEN" always raises an error with chat. Removing the "test" TUM-ID from the input does not work, it reverts to the last known value.

### Environment
* Phone: Android
* OS version: all
* TUM Campus App version: v1.5.2
* Language: de

**Comment by kordianbruck** [comment]
![screenshot_20180216-173136](https://user-images.githubusercontent.com/298860/36318201-5fd03216-133f-11e8-8fba-3df7520080c2.png)

We check the TUM Kennung for validity. How is this possible?

**Comment by anselm92** [comment]
This is also an old bug, once you've entered a wrong id you have to delete the app cache to get past this step

**Comment by kordianbruck** [comment]
Yeah, OK, so if you mistype your tum id, you will be stuck probably. Not sure what the best solution would be here to fix this. A back step might overcomplicate the UI

**Comment by xsrf** [comment]
@kordianbruck just make "SKIP" work / discard the invalid TUM-ID ... no need to add anything to the ui

**Comment by kordianbruck** [comment]
@xsrf ok, you are right. I just checked and the "skip" button basically does nothing in terms of deactivating any of the TUMonline functionality. This needs to be adapted. 

From my understanding, anytime someone presses skip in Step 1&2, we need to absolutely deactivate any TUMonline and authenticated API actions to the app.tum.de API. This will fail in case the Token wasn't activated.
