### ISSUE TITLE
Do we really need custom SearchRecentSuggestionProvider?

### ISSUE THREAD

**Issue by psukys** [TCA-Team/TumCampusApp#675]
When reviewing search for things that use `Cursor` in TCA's codebase, I stumbled upon [EnhancedSearchRecentSuggestionsProvider](https://github.com/TCA-Team/TumCampusApp/blob/8219d041c7e5f525f74ec32db5d644b0e3c26b19/app/src/main/java/de/tum/in/tumcampusapp/auxiliary/EnhancedSearchRecentSuggestionsProvider.java). How does it enhance the recent search suggestions? 
Class description:
```java
/**
 * Slightly modified version of SearchRecentSuggestionsProvider taken from AOSP source code
 */
```

**Comment by kordianbruck** [comment]
From my perspective, it was customized to allow for separate search suggestions for each of our activities. This will most probably no longer be needed with #678
