### ISSUE TITLE
Student number

### ISSUE THREAD

**Issue by phixxx5** [TCA-Team/TumCampusApp#692]
Suggested Feature:
Show student number in the app

**Comment by kordianbruck** [comment]
@phixxx5 What advantage would this have? I fail to see a particular use case?

@xsrf what do you think?

**Comment by pfent** [comment]
@kordianbruck I guess there is no convenient way to look up your own student registration number (Matrikelnummer). Apart from looking at your student ID of course...

I'd probably go all the way and display all of ones own personal details (Stammdaten) when tapping on your picture / name in the side drawer.

**Comment by xsrf** [comment]
What's the use case? Ever heard of Datensparsamkeit? I wouldn't want the app to gather additional personal data just for the purpose of showing it to you...

**Comment by pfent** [comment]
The TCA does not *gather* data, but TUMonline does.
Datensparsamkeit is about not gathering data in the first place...

IMHO this proposal is rather about making already existing data accessible, which is in line with the hacker ethics' "Information wants to be free".

Nevertheless, here are some use-cases:
* You need to enter your Matrikelnr into a form, but don't have your ID card in reach.
* You want to check, if you already updated your address after moving.
* The TCA could potentially also check if the phone number saved in TUMonline is still your current phone number

Those things can already be done with TUMonline, but only hardly accessible on mobile

**Comment by kordianbruck** [comment]
Closing this issue in favor of #1009 "digital student card"
