### ISSUE TITLE
Add a Debug Bridge

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#696]
Stetho lets you access sqlite and shared_prefs from chrom dev tools - magic! :astonished: 

https://facebook.github.io/stetho/

**Comment by pfent** [comment]
Uhh, their documentation only describes unconditional application of the library.

Probably, we shouldn't deploy a full-access backdoor for production :see_no_evil:

**Comment by kordianbruck** [comment]
Well then nevermind. I think we are pretty good as we are right now.
