### ISSUE TITLE
Feedback URL funktioniert nicht mehr

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#706]
Alle URLs funktionieren nicht mehr und werden nur mehr weitergeleitet. 

Siehe auch: https://www.support.tum.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=2864718

**Comment by jacqueline8711** [comment]
@kordianbruck mit "Alle URLs" meinst du nur den "Im Browser ansehen" link, oder? Der Link zu den Fotos funktioniert doch.
Ob es beim Server Fehlermeldungen gibt kann ich ja nicht sehen, aber das sieht ja so aus, als kennt er das ganze "Feedback"-Modul (also den Ordner) nicht. Du hattest es aber doch zu dem modules table hinzugefügt, oder?

**Comment by kordianbruck** [comment]
Ja, genau :)
Fehlermeldung gibts nicht, nur ne Umleitung. Fehlt da eventuell noch ein Datenbankeintrag?

**Comment by jacqueline8711** [comment]
ich hatte es als Kommetar zum PR hinzugefügt was alles in der Datenbank geändert werden muss

**Comment by kordianbruck** [comment]
Schande über mein Haupt. Mein Fehler. Das erste Statement war aber halt auch nicht gültig :stuck_out_tongue:
