### ISSUE TITLE
Move to SDK 21

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#711]
We currently have less than 1% using any of 4.1,4.2,4.3, about 150 alltogether. 
4.4 is still used by ~350 users. 

@pfent what do you think about increasing to API level 19 starting with our 1.6 release?

**Comment by kordianbruck** [comment]
Also I've added a release branch: https://github.com/TCA-Team/TumCampusApp/tree/release/1.6

**Comment by pfent** [comment]
[@minSdkVersion](https://twitter.com/minSdkVersion) agrees with you, but I don't see any new exciting features we can use with 14 -> 19

API 21 on the other hand would be more promising :rocket:

**Comment by kordianbruck** [comment]
I don't really care for 4.4 users either. Those phones are like 3+ years old. 
We can keep the 1.5.X branch for those users and do bug fixes, but as for new features, sure, lets go with SDK 21.
