### ISSUE TITLE
Repository wiki structure

### ISSUE THREAD

**Issue by psukys** [TCA-Team/TumCampusApp#736]
Currently [our Github wiki](https://github.com/TCA-Team/TumCampusApp/wiki) is based on ~articles to document some functionality and guides on using something. Mainly structure can be defined on a homepage or sidebar.

I've made some changes to the sidebar by proposing this structure:
 - General guides
 - Development docs
   - Component-wise docs
 - QA docs

*There must be a better way*

**Comment by kordianbruck** [comment]
Me likey very much - thank you very much - a lot better!
