### ISSUE TITLE
Issues with the reviews by TCA-Bot

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#739]
The TCA-Bot is leaving a lot of (annoying) comments. Maybe we can avoid some of those
- [ ] there has to be a whitespace after if
- [ ] the first sentence in a javadoc has to end with a period
- [ ] id is not used (even though it is used by a Kotlin class)
- [ ] Missing registered class referenced in the manifest (for Kotlin classes)

**Comment by psukys** [comment]
I would agree with last two points as they're purely sound like linting interoperability shortcomings (not able to analyze Kotlin code), rest is up to us to define.

Jenkins report to Github [currently has 4\* sources for reports](https://github.com/TCA-Team/TumCampusApp/wiki/Jenkins-configuration#violations-to-github), which we could adjust:
 - [checkstyle](https://github.com/TCA-Team/TumCampusApp/wiki/Code-style-with-Checkstyle) which is most likely the check for whitespace and javadoc.
 - [PMD](https://pmd.github.io/pmd-6.1.0/) which helps on generic code climate.
 - FindBugs which checks source with common bug patterns.

\* duplicate static analysis PR is still up for review.

**Comment by kordianbruck** [comment]
>  there has to be a whitespace after if

use auto format before commits. (Checkbox in the Android Studio view)

> the first sentence in a javadoc has to end with a period

Makes sense and one gets used to it quickly.

The points related to Kotlin code is true and we might have to deactivate those checks, till there is a solution for them.

**Comment by psukys** [comment]
Ok, by the looks of [related issues](https://youtrack.jetbrains.com/issue/KT-12499) fix is already available to *Android Studio*, but not Gradle. I guess this *should be* a matter of time, but for now let's just ignore it, going to propose a PR soon

**Comment by kordianbruck** [comment]
> FWIW this is fixed in "com.android.tools.build:gradle:3.1.0-beta1" and subsequent versions.

maybe we should upgrade so this gets fixed?

**Comment by kordianbruck** [comment]
3.1 has been released today and I've updated it, so the Kotlin related stuff should no longer happen. 
Regarding auto format: feel free to ask me - I'll happily show you how to do that :+1:
