### ISSUE TITLE
Drop PDFView

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#743]
> Also, when moving to 21, we could also drop the PDFView dependency:
> 
> Also, an inline display for the PDFs would be nice to have. There is a PDFRenderer available for API 21+, even with an exhaustive example on GitHub. Then you can use the fileprovider as a fallback for lower APIs.
> 
> AndroidPdfViewer comes with PdfiumAndroid, which is ~16MB

**Comment by pfent** [comment]
Shamelessly pasta-ing my suggestions :spaghetti:

**Comment by kordianbruck** [comment]
@pfent better? :dagger:
