### ISSUE TITLE
Setup Wizard won't complete when token not activated properly first time

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#760]
## Steps to Reproduce
If you haven't enabled all (?) token rights the first time you tap NEXT after the token was requested, the wizard won't complete. Even if you activate the token rights afterwards, the app won't work. NEXT will fail. You have to skip the wizard.

## Environment
TUM Campus App version: v1.5.6

**Comment by kordianbruck** [comment]
This is most probably already fixed in #755

**Comment by kordianbruck** [comment]
Implemented (probably)
