### ISSUE TITLE
Chat: add via QR code not working

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#763]
Adding a user to a chat via the qr code is not working. The QR code displayed is correct, but once scanned by the other user, will not add him. I'm guessing something goes wrong here on the backend part.

**Comment by rishabhraaj17** [comment]
onActivityResult() method for the barcode scan was not getting inside the first if loop as the first parameter requestCode with value 1 was not correct or I can say that being false was not letting ceateOrJoinChatRoom(name)  to execute. I removed the first parameter and it is working now.

**Comment by kordianbruck** [comment]
@rishabhraaj17 I would love to see the pull request regarding that. Please check https://help.github.com/articles/about-pull-requests/ for further information

**Comment by rishabhraaj17** [comment]
created pull request

**Comment by pfent** [comment]
I think this was fixed with #822
