### ISSUE TITLE
Roomfinder: "irgendetwas ist schief gegangen"

### ISSUE THREAD

**Issue by rabelux** [TCA-Team/TumCampusApp#765]
## Steps to Reproduce

1. Search for "n1080" in Roomfinder
2. Tap on single result "August-Föppl-Hörsaal"

## Expected Result
Map shows where the room is
## Actual Result
No map is shown, only an error message appears
## Further Information
Searched for different rooms in MW and Chemie, they work. Maybe this only affects rooms at Stammgelände Nord?
### Environment
* Phone: Oneplus X
* OS version: Android 6.0.1
* TUM Campus App version: v1.5.8
* Language: German

**Comment by jacqueline8711** [comment]
Hm, I don't get that error when I look for that room, I get the map. (v1.5.8, Android 8)

**Comment by rabelux** [comment]
I just updated the app and don't know whether there is a connection but the map for room N1080 is now shown
