### ISSUE TITLE
Allow users to customize/filter the calendar

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#768]
- [x] whether to show moved/canceled events 
- [x] hide weekend (possible?)
- [ ] show timespan e.g. only 8am to 8pm according to user input (possible with #630 )

related: #408

**Comment by kordianbruck** [comment]
![unnamed](https://user-images.githubusercontent.com/298860/39406704-377fd8d4-4bbb-11e8-9538-ed2083ece842.png)


Example for a filter option (top right)

**Comment by kordianbruck** [comment]
related: #408
