### ISSUE TITLE
Build Server Down

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#774]
Currently the jenkins server is down, as I'm reworking it to run inside my kubernetes cluster. So merging might not work for the time being.

**Comment by psukys** [comment]
@kordianbruck , it seems to be still down, do you need any help on the kubernetes setup?

**Comment by kordianbruck** [comment]
@psukys have you worked with it before? Actually in the mean time I'm rethinking migrating back to TravisCI. Jenkins is really a mess with all its plugins and with the new Github Check API, we can actually do much better.

**Comment by psukys** [comment]
kubernetes - yes. Jenkins in k8s - no. Travis or any other CI sounds good as well, tbh.

**Comment by kordianbruck** [comment]
@thellmund can you check our git history for a `.travis.yml`, restore it and optimize it? Maybe even add Github checks?

**Comment by pfent** [comment]
travis is up and running
