### ISSUE TITLE
Make Person Details look fancy

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#789]
Right now the Person Details Activity is using HTML to format and display any details. This looks not as good as it could. It would be nice, to create a new fancy looking person details layout in material design fashion. 

Bonus points: This person details activity could be linked from the chat as well.

Don't forget to delete `HTMLStringBuffer` once you've moved to a pure android layout.

**Comment by thellmund** [comment]
Made a pull request for this ([801](https://github.com/TCA-Team/TumCampusApp/pull/801)). Let me know if that’s in line with what you imagined and if you want anything changed.
