### ISSUE TITLE
Upload obsfucated IDs

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#790]
The TUMonline `id` endpoint now gives us the obsfucated IDs for the current logged in user. We can use those to display the profile pictures in Chat and other upcoming interaction features (Study Cards :+1: ) to make the whole experience more personalized.

We need to upload these IDs to our API backend (tumcabe), so that we can deliver them with each ChatMessage and generally give the possibility to get a profile pic for any user.

There are several ways to do this:
* Augment the current existing API for uploading the chat registration to also include those IDs
* Add a new API that will allow us to upload IDs once.
* ???

Please look at the existing implementation and let me know what makes sense. (Backward compatibility and ease of use)

**Comment by jacqueline8711** [comment]
https://wiki.tum.de/display/tumonlineappdevndoc/id

**Comment by jacqueline8711** [comment]
- [ ] background service that lets us check what IDs have been uploaded and upload missing ones if possible
- [ ] upload the obfuscated ids directly after logging into tum online after checking if they already exist
- [ ] rename remaining gcm names to fcm / firebase
- [ ] check if merging DeviceVerification and ChatVerification would be a good idea e.g. ChatVerification extends DeviceVerification

backend:
- [ ] alter table member (add three columns for the obfuscated ids)
- [ ] create api endpoint that allows user to upload the ids (only once, a second upload should cause error)
- [ ] api endpoint to check for all existing ids (student/employee/external obfuscated id, RSA key, device id, firebase id) by sending device id which is added to the server db automatically
- [ ] accept all rsa keys and verify them with TUMonline later on (and then set the flag pkactive), flag has to be set for all requests that use ChatVerification

**Comment by thellmund** [comment]
Finished in #908.

**Comment by kordianbruck** [comment]
Follow up issue, due to renaming fields in models by @thellmund #1059
