### ISSUE TITLE
Migrate all Services to Kotlin

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#792]
We still have a lot of crashes in the background services. As a first step to combat this, we should move all our classes inside the `service` package to use kotlin, so that NPEs are no longer a problem.

**Comment by thellmund** [comment]
Hi guys 👋 
A pull request for this issue is opened ([link](https://github.com/TCA-Team/TumCampusApp/pull/796)). It’s my first contribution here – looking forward to feedback and more future work.

**Comment by kordianbruck** [comment]
@thellmund looks good! Our team will review your work and get back to you with comments. Maybe it would be cool to write 2-3 sentances what steps you actually did, without having to look through every line, as this PR is quite big. 

Generally we would advise new collaborators to start with smaller tasks, we will surely make this work. Thanks :+1:

**Comment by thellmund** [comment]
@kordianbruck Alright, will keep this in mind for the future. Steps I took here were mostly just converting to Kotlin via the Android Studio feature and then make adjustments where necessary, such as avoiding the !! operator.
