### ISSUE TITLE
Create SRS document for new features

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#795]
For the Android practical course we are required to create an Software Requirements Specification (SRS).
Ticket Sale will be the first feature to be implemented. Thus, we will do a more detailed specification for the user stories including an analysis of challenges and possibly needed libraries.
For Study Cards and Room Finder we are only going to do a high level overview of the planned features based on the user stories.

**Comment by kordianbruck** [comment]
Yea, please also go ahead and create issues for the ticket sale. Let me know who is going to focus on backend work, so I can add that person to that repository and you can start to scout that out. Make sure you add your documentation to the wiki!

**Comment by saileru** [comment]
I created the issues for user stories of the ticket sale which we categorized as critical. We can add the other ones as needed.

**Comment by kordianbruck** [comment]
@saileru great, this issue can be closed then?

**Comment by saileru** [comment]
We updated the wiki pages for the user stories. The issue is closed now.
