### ISSUE TITLE
Ticket Sale: Handle purchase and send ticket data

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#803]
TS-C-2: As a student, I receive a QR code for each ticket, so that the ticket check at the entrance is simplified.

QR codes are already used in many areas for mobile ticketing, e.g. for cinema or public transportation. The server should send the raw string containing the ticket data. The QR code is then generated on the client side from the raw string.

**Comment by schulzalexander** [comment]
Done in [#28](https://github.com/kordianbruck/tca-backend/pull/28)
