### ISSUE TITLE
Ticket Sale: Overview of booked events

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#804]
TS-C-3: As a student, I see an overview of my booked events, including QR codes, so that I can check the time and location at any time.
In the ticket sale activity, the student sees an overview of all events including title, date and time, which she or he booked. The next events should be shown at the top. The list can be updated by using the well-known Swipe-to-Refresh functionality. By clicking the event, the student can access the QR code, so that it can be checked by the cashier.

**Comment by schulzalexander** [comment]
Done in #868
