### ISSUE TITLE
Ticket Sale: Admin should see total number of sold tickets for an event

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#805]
TS-C-4: As a cashier/admin, I want to be able to look up the total number of ticket sales for a certain event, so that event planning is facilitated.

This can also be implemented as a live ticker showing the current amount of sold tickets as logged by the server, i.e. using the same data source. This live ticker can be included in the admin gateway that we agreed on to provide in the server's web-interface.

**Comment by velev8** [comment]
<img width="267" alt="screen shot 2018-06-26 at 13 42 24" src="https://user-images.githubusercontent.com/38428686/41909176-a7ad0600-7946-11e8-8c30-e0413462efaf.png">

**Comment by kordianbruck** [comment]
Waaaaait, what? Let's discuss this tonight.

**Comment by saileru** [comment]
Transferred to TicketCheck repository and provided a link to this issue
