### ISSUE TITLE
Ticket Sale: Describe and illustrate frontend concept

### ISSUE THREAD

**Issue by schulzalexander** [TCA-Team/TumCampusApp#809]

**Comment by schulzalexander** [comment]
For the Ticket Sale, we want to add an extra "Events" section to the menu.
This will lead the user to a new event overview, which is basically a table view simular to the news feed, but only containing upcoming events.
Selecting an event (which will first only be TUFilms) will continue to the Detail-Activity that already exists for movies. We need to add a "buy" button there in order to start the ticket purchase process for the user. This includes showing a quick summary including price etc. and the login to Stripe.
After successful purchase, the ticket will be saved to a "My Tickets" section, also accessible from the menu (or putting some shortcut in the event overview)
![ticketsalesketch](https://user-images.githubusercontent.com/30290755/39778441-98e997e8-5306-11e8-9066-7c2705cbed07.png)

**Comment by schulzalexander** [comment]
@kordianbruck is this in line with what you expected for the frontend?

**Comment by kordianbruck** [comment]
Yes, I like the flow - except the last page does not exist, as we have a TUMonline login as a prerequisite - so its not even possible to "buy" without a token

**Comment by schulzalexander** [comment]
jap, that’s why it says „Stripe Login“ ;) When we have saved the user‘s Stripe credentials, then of course this shouldn‘t be a login but rather just for the user to confirm the purchase.

**Comment by kordianbruck** [comment]
Stripe does not have a login from what I know - you simple enter your creditcard details :+1:

**Comment by kordianbruck** [comment]
@schulzalexander when closing an issue, please also state the fix, if it is not a PR. In this case: did we finish the implementation and/or are we using the illustration in any of the (sub)issues?

**Comment by schulzalexander** [comment]
@kordianbruck sorry, my bad.
I changed the last page in the illustration from a login to a payment selection.
Nothing of the illustrated parts is implemented by now, but it's referenced by #812 and #813 . Issues for the payment selection and summary are still to be created.

**Comment by kordianbruck** [comment]
@schulzalexander thanks for clarifying - maybe add the workflow (or a part of it) to the sub issues as well? This issue is now linked, so only if you think it helps the implementing person...
