### ISSUE TITLE
Mensa: Parse additional feeds via OCR / PDFs

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#81]
YQL - Is it possible to read PDFs?  Possibly use Webservice?
Maybe we can extend the dining information (mensa food) and add Loose, the IPP and other facilities

**Comment by nilstk** [comment]
Freiraum Garching-Hochbrück 
http://www.freiraum.rest/media/wysiwyg/Wochenkarte/Speisenplan_pdf_KW_26.pdf

**Comment by kordianbruck** [comment]
Thanks to @mammuth we now have a simple possibility to parse that data without many troubles: https://github.com/mammuth/TUM.sexy/blob/master/hunger/index.php

Might just steal that code :tada:

**Comment by mammuth** [comment]
@kordianbruck 
ohoh, you might think about using this code. It's really dumb 'parsing' ;-)

**Comment by kordianbruck** [comment]
Closing in favor of #127 - fmeat has those other cafeterias included.
