### ISSUE TITLE
Ticket Sale: Event Overview

### ISSUE THREAD

**Issue by schulzalexander** [TCA-Team/TumCampusApp#812]
Implement a seperate activity showing a list of upcoming events, sorted by date.
The Activity should be accesible by the main menu.

Include a button to filter for events that the user bought tickets for.

For reference, see illustration at #809 .

**Comment by kordianbruck** [comment]
I would suggest a card view similar to the home & news screen. Events should be fetched from our own API (TBD)

**Comment by schulzalexander** [comment]
Done in #868
