### ISSUE TITLE
Ticket Sale: Add "Buy/Show Ticket" button to detailed view of TU Kino

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#813]

**Comment by Kailiangdong** [comment]
Create a new activity that presents the detailed view of each events. There should be a button in the activity. For not-booked button , it is  a "Buy" button. For booked event, it is a "Show Ticket" button.
The activity should be accessible by clicking the corresponding events in the list of upcoming events.

**Comment by schulzalexander** [comment]
for reference, see illustration in #809 .

**Comment by kordianbruck** [comment]
@saileru this was also done? Any other PR than the one mentioned above?

**Comment by saileru** [comment]
Yes, this has already been merged to the ticket sale feature branch after the Pull Request https://github.com/TCA-Team/TumCampusApp/pull/821
