### ISSUE TITLE
Ticket Sale: QR Code Ticket Activity

### ISSUE THREAD

**Issue by schulzalexander** [TCA-Team/TumCampusApp#814]
Create a new activity that presents the ticket for a booked event as a QR Code.
This activity should be accessible by the event's Detail Activity by clicking the "Show Ticket" button (which for not-booked events is used as the "Buy" button).

**Comment by kordianbruck** [comment]
Ideally you can use a library to generate the QR code. In the chat activity we already display a QR code using google charts which is not so nice.

**Comment by saileru** [comment]
For the implementation an open source library such as zxing can be used (https://github.com/zxing/zxing/wiki/Getting-Started-Developing).

**Comment by kordianbruck** [comment]
@Kailiangdong is this issue done? Merged? Please leave a comment, on what happend and why we are closing this issue.
