### ISSUE TITLE
Ticket Sale: Get all events from Server

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#815]
GET - https://app.tum.de/Api/ticket/event/list
Return: all events including name, event ID, date and time, location, price, number of available tickets

The corresponding database table "Events" should contain columns for all of these values

**Comment by kordianbruck** [comment]
Please make the table 'event' and the endpoint something like: /ticket/event/list - we prefer to use singular for our types.

**Comment by schulzalexander** [comment]
New endpoint specification (compare [WIKI](https://github.com/TCA-Team/TumCampusApp/wiki/Ticket-Sale%3A-API-and-database-concept)):

**Get information for all events.**

GET api/event/list

_Parameters:_
earliest (optional) -> only return events that happen at or after the specified timestamp
latest (optional) -> only return events that happen at or before the specified timestamp
id (optional) -> only return event with the defined ID

Response { “event_list”: { “$eventID1”: { “event”: “$eventID”, “title”: “...”, “description”: “...”, “file”: “$PictureLink”, “locality”: “...”, “date”: $timestamp, “link”: “$url” }, “$eventID2”: {...}, ... } }

**Comment by schulzalexander** [comment]
Done in [#23](https://github.com/kordianbruck/tca-backend/pull/23) of backend repo.
