### ISSUE TITLE
Ticket Sale: Create new event

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#817]
For event organizers the server should provide a function to add a new event. However, this function should not be exposed and is not part of the API!
It can be accessed with a login on the page with the corresponding rights.

Params: name, date and time, location, price, number of available tickets

Create random strings for all tickets (or later as needed?)

Return: event ID of new event

**Comment by kordianbruck** [comment]
Does this create an event or a ticket for an event? What the API should be doing, is not clear to me. Following this question, please also rename it to /ticket/event/

**Comment by kordianbruck** [comment]
Done
