### ISSUE TITLE
Move all constants from CalendarActivity

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#820]
We have a lot of local constants in `CalendarActivity` that should be moved to `Const.kt`

**Comment by pfent** [comment]
I'm still not convinced of unnecessarely increasing their scope...

**Comment by pfent** [comment]
Although I'm totally in favour of merging "same" constants, like discussed in #818

**Comment by kordianbruck** [comment]
Closing this for now.
