### ISSUE TITLE
Notification timings are wonky

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#825]
I sometimes get notificatins at very confusing times. E.g. notifications for cafeteria menus at 7pm...

## Expected Result
Notifications should appear at appropriate times.
E.g. for upcoming meals at around 10am or 11 am;
for MVV about an hour before the last lecture of the day finishes

**Comment by thellmund** [comment]
I was just reminded of this bug when I received a notification about tuition fees that are due in 2.5 months. That’s not information that I need today. 

I like @pfent’s suggestions and I think we could go even further. Consider tuition fees: 
1. The first notification could appear a month before the deadline – more than enough time. 
2. If the student has not paid the tuition two weeks before the deadline, another notification. 
3. Then one week.
4. Then daily notifications starting half a week before the deadline. 

There are probably more cases where we can move to a more intelligent scheduling of notification. Let’s discuss them in person sometime in the next few weeks 🙂

**Comment by thellmund** [comment]
Worked on in #879.

**Comment by thellmund** [comment]
Finished in #879.
