### ISSUE TITLE
TicketSale: Return list of event suggestions for fuzzy search

### ISSUE THREAD

**Issue by schulzalexander** [TCA-Team/TumCampusApp#830]
**Fuzzy search for an event. Only returns information shown in the single cards of the event overview.**

GET api/event/list/search

_Parameters:_
search_string (required)

Response { “event_list”: { “$eventID1”: { “event”: “$eventID”, “title”: “...”, “description”: “...”, ... }, “$eventID2”: {...}, ... } }

**Comment by schulzalexander** [comment]
@kordianbruck can I define custom MySQL functions to use in the query? If so, where should I put the according file?

**Comment by kordianbruck** [comment]
@schulzalexander no, please do any logic from PHP without stored sql procedures.

**Comment by schulzalexander** [comment]
Done in [24](https://github.com/kordianbruck/tca-backend/pull/24) of backend repo.
