### ISSUE TITLE
Notifications shown by default

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#834]
Notifications for cards should not be shown by default.

**Comment by kordianbruck** [comment]
@pfent I know many students, that absolutely love MVV timings in the App. We can argue, if a notification for it is really smart, as we show it at such random times. I'm all for removing that part, especially as its not implemented too great. => Remove MVV notifications

Killer feature sounds great => lets do that as well

**Comment by pfent** [comment]
#879 will make the notifications more useful.
Users can always disable them, but we decided to keep them enabled by default
