### ISSUE TITLE
TicketSale: Create concept for API endpoints

### ISSUE THREAD

**Issue by schulzalexander** [TCA-Team/TumCampusApp#838]
Define API endpoints for ticket sale in the [Wiki](https://github.com/TCA-Team/TumCampusApp/wiki/Ticket-Sale:-API-and-database-concept).

**Comment by schulzalexander** [comment]
@kordianbruck I defined the public API endpoints. Would be nice if you could quickly have a look ;)

**Comment by kordianbruck** [comment]
@schulzalexander it looks good. Please go ahead with the implementation. We are still missing the authentication part from the specs, but thats fine for now.
