### ISSUE TITLE
TicketSale: Create static API endpoints

### ISSUE THREAD

**Issue by schulzalexander** [TCA-Team/TumCampusApp#839]
Create API endpoints with static return values, in order for the frontend to already be able to implement and test the client's API-fetching functions.

**Comment by kordianbruck** [comment]
@schulzalexander great, please get on it, so we can send some dummy data over the network.

**Comment by schulzalexander** [comment]
Done in [#22](https://github.com/kordianbruck/tca-backend/pull/22) of backend repo.
