### ISSUE TITLE
Curricula unreadable / look horrible

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#841]
the study plans are pretty much html sites without css...
this is how it looks after you zoom out:
![screen_curricula](https://user-images.githubusercontent.com/16260112/40577240-afe8ce1e-6102-11e8-8e59-5a1cea13ae6d.png)
![screen_curricula_2](https://user-images.githubusercontent.com/16260112/40577241-b0f82192-6102-11e8-92e2-755d3966ad92.png)

**Comment by pfent** [comment]
I think we can get rid of the study plans altogether.
We never supported curriculas outside of computer science, plus viewing them always was uncomfortable anyways...

I'd prefer to remove them, until we have a proper API for that information...
@xsrf Any chance for "Curricula Support" / "Studienplan" to be exposed by an API?
In theory, that should be public information (aka the same as on the website) - except for your own progress in your curriculum?

**Comment by kordianbruck** [comment]
Anyone interested: I will try to setup a meeting for Friday the 8th - maybe we can organize a new API for this matter finally

**Comment by kordianbruck** [comment]
So we removed them for now. Maybe in the future we will get an API, but this is still uncertain for now.
