### ISSUE TITLE
Refactor CardManager

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/TumCampusApp#842]
## Problem
When I was fixing a bug in MainActivity (tapping “Open card settings" crashed the app for some cards), CardManager’s current behavior made it unnecessarily difficult. 

## Suggested Enhancement :sparkles:
I suggest refactoring CardManager and surrounding classes in the following ways: 

**CardsManager**
1. We update the CardsManager.update() method to return _LiveData_, so that we don’t need to take care of managing listeners ourself (also, lifecycle-aware 😎; in CardsWidgetService and DownloadService, we can use a CardsManager.updateNow() method to do it synchronously).
2. This can also help us to remove calls like `CardManager.getCard(index)` within the CardAdapter. The Adapter should be provided with its list of items, not request the appropriate one on every onBindViewHolder. 

**MainActivityViewModel**
1. We add a ViewModel that stores all UI data in MainActivity. 
2. This ViewModel performs the calls to _CardsManager_.
3. This helps us separate concerns and simplify MainActivity. 

**DiffUtil**
1. We use _DiffUtil_ with _CardsAdapter_ to determine differences between the old list of items and the new list. 
2. It automatically adds insert/remove animations, resulting in a nicer user experience. 

**Listeners**
1. We pass a listener to CardViewHolders that notifies the CardAdapter when a Card’s menu item was selected. 
2. This allows for a more streamlined reaction to “Always hide”, as this option should not only update the SharedPreferences, but immediately hide the corresponding Card.

**Open Questions**
We currently also update the cards on a swipe down and on connectivity change. I’ll research how to best implement those with LiveData.

Let me know what you think, @kordianbruck @jacqueline8711 @pfent. Are there other aspects that I didn’t mention here?

**Comment by pfent** [comment]
Sounds like a great idea :+1:

If we use `MutableLiveData`, we can update the values on a refresh and the Main Activity should update.

**Comment by kordianbruck** [comment]
Good suggestion - long due overhaul of the way we handle the whole card system. No additional comments from my side, except that we might also need to rethink about how to better give certain properties to cards (dismissable, always on top, etc.). But thats for another issue.

**Comment by thellmund** [comment]
Working on this in #854.

**Comment by kordianbruck** [comment]
Merged
