### ISSUE TITLE
Update behavior of Navigation Drawer

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/TumCampusApp#843]
**Solution today** 
When the user selects a list item in the Navigation Drawer, we open a new Activity. 

**Problem today** 
When the user repeatedly selects list items, they end up with a stack of Activities. They need to tap back multiple times to get back to MainActivity. Also, these Activities have a back button _and_ show the Navigation Drawer when swiping in from the left. 

**Proposed solution** 
We convert all Activities into Fragments. When the user selects a list item, we perform a Fragment transition in MainActivity. Exceptions are About, Feedback and Settings – they can remain Activities. 

**Benefits** 
For the user: 
- Simplified navigation flow without huge backstack
- Navigation Drawer icon will be visible as an affordance all the time

For us: 
- No need to include the Navigation Drawer in every layout
- More flexibility for the future (e.g. introducing bottom navigation)

Open to discussion.

**Comment by kordianbruck** [comment]
Lets have a group read on this:
* https://stackoverflow.com/questions/18500438/activities-vs-fragment-implementation
* https://stackoverflow.com/a/23535445/409460
* https://stackoverflow.com/a/44898179/409460

Still open questions:
* Performance?
* RAM requirements for low end phones?
* Is there any actual benefit other to having a single super god like activity that does everything?
* What architecture are we aiming for? (MVP? MVI? MVC?)
* How does this work together with MVVM?

**Comment by thellmund** [comment]
@pfent Sure, we want to do this step-by-step. I think the right approach would be this: 
1. Slowly (one after the other) move all Activities that have corresponding list items in the Navigation Drawer to the same model as PlansActivity, where the Activity is just a wrapper for a Fragment. We keep the current behavior, where a new Activity is opened when a list item is selected in the Navigation Drawer. (For this step, we’ll need to provide base Fragments that handle everything that currently is in `component/other/generic/activity`.)
2. Once that is working, remove these Activities and refactor MainActivity to display the Fragments directly.

**Comment by thellmund** [comment]
Behavior change mostly implemented #1062, but did not yet transition `Activity` content into `Fragments`.

**Comment by kordianbruck** [comment]
I think this idea is good to use more fragments, but for now just too much effort for little return.
