### ISSUE TITLE
Ticket Sale: Add EventDetailsFragment

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#847]
For the ticket sale we need an activity similar to the KinoDetailsFragment which should use the new Event model class instead of the Kino model class.

**Comment by saileru** [comment]
Many of the current tickets are highly dependent on how we want to combine the Ticket Sale with the existing Kino classes. A great part of the kino code should be reusable for the ticket sale. Separating the implementation for now would probably lead to much duplicated code. We could always do a Refactoring afterwards. I do not know what is easier: Combine event and kino now or implement it separately and refactor later.

Considering this open question and all the gaps in the implementation especially in the connection to the server, it is difficult for me to make good progress here without expecting to have to change much code later. 

We already discussed this in our working session on Thurday (@Kailiangdong @velev8 @schulzalexander). We thought about doing a separate implementation for now. But I am sceptical if this is the best approach... @kordianbruck Do you have any suggestion on how we should continue here?

**Comment by kordianbruck** [comment]
Please separate those two things completely and only reuse parts that are really needed. You are expected to change code at a later stage again. Thats not a problem.

**Comment by saileru** [comment]
Closed in #853
