### ISSUE TITLE
Uninformative NewsCard for new issues of Impulsiv magazine

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/TumCampusApp#849]
**Situation today**
In MainActivity, we show new issues of the _Impulsiv_ magazine as a NewsCard. 

**Problem today**
The card is not very informative. I only displays the issue number, but not the issue cover or any additional information. 

![screenshot_20180602-121158](https://user-images.githubusercontent.com/11819826/40873312-55d01822-665e-11e8-9276-22317cdf17e9.png)

**Ways to fix**
We should display more information about the issue. For instance: 
1. Display the issue cover on the left hand side, similar to the cards about movies. 
2. Display the main topics covered in the issue. (Not sure if this is actually desirable, but let’s test it.)

**Comment by kordianbruck** [comment]
This is more of an server Issue and we need some magic there, to get those things working. Also relevant for iOS in that regard.

**Comment by thellmund** [comment]
You’re right, @kordianbruck. I’m happy to take a look at it, as I’d love to get familiar with the server.

**Comment by kordianbruck** [comment]
@thellmund you already have access to the backend. Let me know if you need any help with that.

**Comment by kordianbruck** [comment]
I've added "Impulsiv - Ausgabe XXX" to the title for now. A cover image would be nice, but kinda is too much work for now.
