### ISSUE TITLE
Add dedicated options button for card’s menu

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/TumCampusApp#850]
**Situation today**
When a user long-clicks on a card today, two things happen: 
1. We enter drag-&-drop mode, allowing the user to move the card up and down. 
2. We open the card’s pop-up menu, which allows the user to open the card settings or always hide to card. 

**Problems today**
1. This is an odd behavior. A long-click should not trigger two distinct behaviors simultaneously. 
2. While dragging, the options menu remains on the screen. 
3. Card options are not very discoverable.

**Suggestion**
We add a dedicated options button that opens the card’s menu. It can be displayed in the lower right corner of each card (not upper right, as some cards have a header image). 
This way, we avoid having two actions on a long-click and make it more obvious that the user can take actions on cards.

**Comment by kordianbruck** [comment]
I think we can just remove the long press for settings, as its not used that much from my perspective. You have the gear wheel in the toolbar on that screen in any case, that takes you to the settings.

**Comment by thellmund** [comment]
@kordianbruck The toolbar no longer features a settings icon, as they should not have multiple entry points. Having settings in a navigation drawer is the standard in most Android apps, so users should be familiar with it. 

Do we have any metrics on how often these card options are opened?

**Comment by kordianbruck** [comment]
@thellmund we have some metrics, but not how often the settings are used for each of the cards. I'm not sure if we can see this inside analytics - maybe?

**Comment by thellmund** [comment]
@kordianbruck Rather [this type of icon](https://material.io/tools/icons/?search=vert&icon=more_vert&style=baseline), which is the universal options icon.

**Comment by kordianbruck** [comment]
@thellmund excellent!

**Comment by thellmund** [comment]
Implemented in #1100.
