### ISSUE TITLE
Ticket Sale: Refactor Event classes

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#864]
I expect that a lot of code for the event classes will be copied from the Kino classes. I think we could maybe make Kino a subclass of Event and reuse the Kino implementation...

**Comment by saileru** [comment]
Update meeting 19.06.2018: we decided not to unify Event and Kino classes. They should be treated as separate activities which might develop differently in the future.

But we still should have a look over all new classes after the feature is finished to clean up the code.

**Comment by schulzalexander** [comment]
A refactoring of all classes is done in PR #981

**Comment by saileru** [comment]
Closed in #981
