### ISSUE TITLE
Special character shown as "?" in Roomfinder

### ISSUE THREAD

**Issue by DreierF** [TCA-Team/TumCampusApp#87]
![screenshot_2014-08-24-11-09-18](https://cloud.githubusercontent.com/assets/5631865/4023033/b5c43b8e-2b6e-11e4-9ada-b2e5da2fee25.png)

Example: http://vmbaumgarten3.informatik.tu-muenchen.de/rooms/title?s=hoch

**Comment by kordianbruck** [comment]
The current "dirty quickfix" is located in the auxiliary XMLParser Class in the function getValue

**Comment by kordianbruck** [comment]
@Carlinho89 @arash-a2k @enricogigantiello will work on this issue together
