### ISSUE TITLE
Add Room migrations

### ISSUE THREAD

**Issue by velev8** [TCA-Team/TumCampusApp#893]
Currently we have migrations disabled, as we were not able to reliably test, that they work. Especially migrating from a previous Database was not possible and attempted several times. Each time, it would fail during the validation phase of the migration. The problem was not easily reproducible and happend several times, which lead to user being in a "stuck" system, that they were not able to use and would crash on startup.

**Comment by kordianbruck** [comment]
@thellmund started adding migrations and they seem to work, when one commits the schema file with the repo. So in the future we will try to add migrations for any database change
