### ISSUE TITLE
Ticket Sale: Feedback Event Details

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#896]
Please give us feedback how to improve the ticket sale UI

Points from the Scrum Meeting are:

- "Buy" button as floating action button
- obvious/motivating color like green/red
- include price in the event details, maybe on the buy button
- link as separate button below the picture, so that the picture has more room 

![screenshot_20180612-142624](https://user-images.githubusercontent.com/12066533/41290695-eff7f52c-6e4d-11e8-9924-348140c0bc6a.png)
![screenshot_20180612-142637](https://user-images.githubusercontent.com/12066533/41290696-f095da94-6e4d-11e8-92e9-5a6cee7997f3.png)

**Comment by kordianbruck** [comment]
* properly format the date according to locale
* link address to google maps / room finder
* Not sure we need the pager / spinner on top, to switch between events. The user flow should be that one selects one event from the list and looks at it. Otherwise, why would we have the list in the first place?

**Comment by thellmund** [comment]
Aren’t event posters in landscape format? In that case, I think it makes sense to adapt the layout accordingly.

**Comment by velev8** [comment]
I would also make the different tab buttons (tunix, winterball, garnix) stand out more as buttons

**Comment by velev8** [comment]
To Do: 

- [ ] Format date according to locale
- [ ] Link Address to google maps (click listener)

**Comment by pfent** [comment]
I really dislike the buttons for the link / buy ticket.
Please refer to [the material design guidelines](https://material.io/design/components/buttons.html#hierarchy-placement), especially for placement of buttons.

IMO, floating action buttons at the bottom of the screen are the way to go, but feel free to come up with ideas.

**Comment by velev8** [comment]
New mockup for this issue, please give feedback 
<img width="271" alt="screen shot 2018-06-26 at 15 34 46" src="https://user-images.githubusercontent.com/38428686/41915622-70b14728-7956-11e8-8c44-cb6c12c6ccdf.png">

**Comment by kordianbruck** [comment]
@velev8 Looks really good, love it. Some things:

1. I would put the website link as a button on the very bottom
2. Why should we split date & time? Do we really support date ranges?
3. Can we add the event to the calendar, once somebody clicks on the date? (make it a button?)

**Comment by saileru** [comment]
@velev8 @kordianbruck We planned to have pictures in something like 16:9 landscape, right? This format won't work for the new UI layout.

**Comment by kordianbruck** [comment]
@saileru yea, pretty much. Can we just make the Image smaller to fit those proportions?

**Comment by saileru** [comment]
@kordianbruck I made a suggestion for layout adjustment in #946

**Comment by kordianbruck** [comment]
@saileru thanks. 

Is this issue done then?

**Comment by saileru** [comment]
Yes, I think we can close it.
Closed in #941 und #946
