### ISSUE TITLE
Ticket Sale: Feedback Show Ticket

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#898]
Please give us feedback how we can improve the ticket sale UI

![screenshot_20180612-142629](https://user-images.githubusercontent.com/12066533/41292264-5ca79af2-6e52-11e8-8978-e0d5fcdf6138.png)

**Comment by kordianbruck** [comment]
* Titel of event could be bigger
* link address to google maps
* Properly format date according to currently set locale
* "Ticket QR Code"
* This activity should set the screen brightness to 100%, so scanning is easier
* Ticket Redepmtion status should be shown?
* Ticket Price should be shown

**Comment by thellmund** [comment]
I don’t think we need the headers. If we layout the content appropriately (e.g. make the title bigger), it should be easy enough to grasp. And particularly for the QR code, the header is unnecessary. 
- [ ] Remove the headers

The background of the activity should be the same as the background of the QR code image. 
- [ ] Use the same background for background and QR code

I support @kordianbruck’s requests. The link to Google Maps though should however not be a text link. Instead, set a click listener on the text view (or is parent, if appropriate).

**Comment by velev8** [comment]
- [ ] Bigger title of event
- [ ] Remove the headers
- [ ] Use the same background for background and QR Code 
- [ ] Link address to google maps (click listener on the text view or its parent)
- [ ] Format Date to current locale
- [ ] "Ticket QR Code" (add space, capitalze C)
- [ ] Set screen brightness to 100% 
- [ ] Show ticket redemption status
- [ ] Show ticket price
