### ISSUE TITLE
Ticket Sale: Feedback Credit Card Activity

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#899]
Feedback from the meeting:

- After the purchase the user should be taken to the show ticket view (currently main activity...)
- remove separator in checkout or make spacing tighter

![screenshot_20180612-142652](https://user-images.githubusercontent.com/12066533/41292808-e3217b38-6e53-11e8-960d-307a5a6ef46d.png)
![screenshot_20180612-142726](https://user-images.githubusercontent.com/12066533/41292810-e34f86fe-6e53-11e8-84b4-7ed387980044.png)

**Comment by jacqueline8711** [comment]
There is a law that says what has to stand on the buy button, which I think applies here too. So we should probably change the text it to "Jetzt kaufen" / "Buy now"
https://de.wikipedia.org/wiki/Button-L%C3%B6sung#Zul%C3%A4ssige_Bezeichnungen
Even if it does not apply I think this would be a clearer label.

**Comment by kordianbruck** [comment]
* what Jacqueline says makes absolute sense, so please use that unified language
* Button align to right? Does that look better?
* Remove the separator / space
* You will probably want to allow the user to enter the credit holder name, as this might not be the same as the currently logged in user
* Same button style as in feedback activity
* Please formalize the top sentence. Right now its really informal.
* Add a heading: "Kreditkarten Daten" or something
* Add: "save credit card" option?

**Comment by thellmund** [comment]
Can this be a dialog instead of an activity? 

If the user has already added a credit card, we display a list view dialog to select the appropriate card or add a new one. 
If the user has not added a credit card, we display the credit card input form.

**Comment by velev8** [comment]
To Do:

- [ ] "Buy now" button in accordance to law 
- [ ] If user has already added a credit card: display list view dialog to select the card or add new one
- [ ] If not, display the credit card input form
- [ ] Allow user to enter credit card holder name
- [ ] Same button style as in feedback activity
- [ ] Formalize top sentence
- [ ] Add Heading "Kreditkarten Daten" or something similar
- [ ] Allow user to save the card

**Comment by saileru** [comment]
@schulzalexander What is the status of the implementation of the feedback for this activity?

**Comment by schulzalexander** [comment]
@saileru most of them are implemented, but of course some points may need to be revisited since the design completely changed. We'll see that in today's feedbaack round

**Comment by schulzalexander** [comment]
Done in #944
