### ISSUE TITLE
TicketSale: Feedback Payment Selection

### ISSUE THREAD

**Issue by schulzalexander** [TCA-Team/TumCampusApp#904]
The "payment selection" by now is just a button redirecting to the credit card form.

In case we have more than one payment option, how should this selection activity look?

Also: If we don't plan to add new payment options in the near future, we could for now get rid of this activity and directly direct the user to the yet to be implemented credit card overview.

<img width="223" alt="bildschirmfoto 2018-06-11 um 13 58 01" src="https://user-images.githubusercontent.com/30290755/41421163-69e86dfe-6ff6-11e8-90db-029f59c4eb92.png">

**Comment by kordianbruck** [comment]
* the margin on the left is less than on the right? (or is the screenshot cut off?)
* Use same button style as in Feedback activity (strong blue with white text)
* We can really skip this step, as long as there is only one option - please add some logic for that

**Comment by thellmund** [comment]
I think a list view would lend itself better for this situation. Every list item would refer to a credit card that the user has added. The last list item could be something lik “+ Add credit card” to allow the user to add a new credit card. 
- [ ] Switch to list view

Each list item could display the appropriate credit card icon (VISA, MasterCard, etc.) and should definitely show the name of the credit card holder (do we have/need that information?) and the credit card number. 
- [ ] Show credit card details

The user should also have the option to delete credit cards. Is that in the scope, @kordianbruck?
- [ ] Add delete option

**Comment by velev8** [comment]
ToDo: 

- [ ] Fix margins
- [ ] Use same button style as in feedback activity
- [ ] Add a Credit Card icon according to the credit card type (Visa, MC, etc.)
- [ ] List view for credit cards, where each list element contains icon, name and credit card number with only the last four digits visible, while the preceding digits in asterisks
- [ ] Add Delete option (?)

**Comment by pfent** [comment]
I thought we only have stripe as payment provider (#888)?

If we don't have any additional payment methods in the forseeable future, we [aren't gonna need this screen](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)

**Comment by saileru** [comment]
This screen is currently not used as credit card is the only payment option. The feedback should be implemented when more payment options are implemented. Thus, I move it to the backlog for now.

**Comment by kordianbruck** [comment]
@saileru please remove the activity then, if its not used. Thanks.

**Comment by saileru** [comment]
Removed in #1003
