### ISSUE TITLE
TicketSale: Feedback Ticket Check

### ISSUE THREAD

**Issue by velev8** [TCA-Team/TumCampusApp#905]
Please give us feedback on how we can improve the ticket check UI 

![whatsapp image 2018-06-14 at 18 59 58](https://user-images.githubusercontent.com/38428686/41432493-9ddacba0-7016-11e8-8f66-db511e0914a1.jpeg)

**Comment by kordianbruck** [comment]
* Add the Toolbar that is in every other activity
* show: Buy date
* show: Redemption Date, if already checkedin
   * in this case there should only be an: "close" button
* show: TUM Kennung (go42tum)
* buttons: cancel & checkin
* Checkin button should be more prominent with a background color - green? (You want to highlight the action the user should do)

**Comment by thellmund** [comment]
I agree with most points. However: 
- What’s the rationale for showing the TUM ID? 
- If the ticket was already redeemed, we should not hide the “Confirm” button, but instead make it inactive.

**Comment by kordianbruck** [comment]
@thellmund 
* TU Film wants to have it
* Sounds good.

**Comment by velev8** [comment]
ToDo:

- [ ] add toolbar on top
- [ ] show: Buy Date 
- [ ] show: redemption date 
- [ ] show: checkin status (if redeemed, make "Confirm" button inactive)
- [ ] show: TUM Kennung
- [ ] make the checkin button more prominent

**Comment by pfent** [comment]
After scanning the code, we can probably show another screen, which displays the information.
Full-screen scanning screen actually looks good to me, as long as we switch to a informative screen after scanning completed

**Comment by saileru** [comment]
The feedback will be implemented in the Ticket Check repository
https://github.com/TCA-Team/TicketCheck/issues/8
