### ISSUE TITLE
Switch to JodaTime and add DateConverter

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/TumCampusApp#906]
We’re often using strings to store dates in our database, which is not a good solution. Instead, we should add a custom DateConverter that converts those date strings into JodaTime objects.

**Comment by pfent** [comment]
Also migrate the DateUtils to Kotlin and JodaTime

**Comment by kordianbruck** [comment]
btw. JodaTime is already part of the project - its used at some places already.

**Comment by kordianbruck** [comment]
Done in linked PR.
