### ISSUE TITLE
Ticket Sale: Send events to calendar app

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#915]
TS-Mi-2: As a student, I can add the event to my preferred calendar app, so that I can see it in context of my schedule.
Each event should have an “add to calendar“-button in its detail activity (regardless of whether a user has already bought tickets for an event or not). Additionally, we can add an icon for this action to the section of each event in the event overview (possibly a tableView), if there is still space for this. Once an event is added to the local calendar, the icons/buttons should change their appearance to signal that the calendar entry has been created. Clicking on the very same icons/buttons again should simply remove the event from the calendar.
Adding an event to the default calendar can be done by using the Calendar Provider, which offers a bunch of Calendar Intents. These allow to specify the action you want to perform on the calendar, in our case, add an event. When executed, this will take the user right to the calendar app itself, where they can still modify and finally confirm the event. Afterwards, the user will be taken back to where they were in our app. Using this approach, we don’t need the WRITE_CALENDAR user-permission in our manifest, as compared to the other possibility of just adding the event to the calendar without user interaction, which would require that permission.

Maybe something like this could also work: https://stackoverflow.com/questions/6617231/how-to-use-calendar-intent

**Comment by pfent** [comment]
We already have some code to add calendars, maybe you want to have a look at `CalendarActivity`

**Comment by velev8** [comment]
After the scrum meeting our team decided that we will create the mockup for this issue this weekend since we are still waiting for a little more progress!
