### ISSUE TITLE
Add Event into TUM Calendar and integrate to CardView

### ISSUE THREAD

**Issue by velev8** [TCA-Team/TumCampusApp#918]
Integrate in TCA Calender Activity

**Comment by saileru** [comment]
@schulzalexander Did we agree on anything about getting the event duration/end time from the server?

**Comment by schulzalexander** [comment]
@saileru not yet, I'd suggest either we include the duration info in the description, or we deploy a seperate field for it in the database and in the Event class.

**Comment by saileru** [comment]
@schulzalexander Yes, I think a separate field in database and Event class would make sense.
I do not quite understand why we whould add it to the description. You mean like:
description : "2018-08-06 16:00 This event is very good."
And then we would need to parse it from the description field? Or what did you have in mind?

**Comment by schulzalexander** [comment]
@saileru oh no, no parsing^^ I just meant that the duration would somewhere be mentioned in the text of the description if needed, but I'd also tend towards the other solution.

**Comment by saileru** [comment]
See #965

**Comment by saileru** [comment]
@kordianbruck What is meant by "integrate to CardView"?

**Comment by saileru** [comment]
@kordianbruck "Integrating to CardView" still open. We are not sure what is meant by that.

**Comment by kordianbruck** [comment]
@saileru sorry, must have missed this issue. 

CardView is the main screen, once you open the app. We can supply an event card for that view so the next event is always visible there.

**Comment by saileru** [comment]
@kordianbruck Ok thank you! I created a new issue for that as it does not seem to be directly connected to the "Expot Event To Calendar" function. #980

**Comment by saileru** [comment]
"Add to calendar" implemented in #964
