### ISSUE TITLE
TicketSale: Search student name or TUM-ID to find ticket

### ISSUE THREAD

**Issue by velev8** [TCA-Team/TumCampusApp#919]
TS-Ma-5: As a cashier, I want to be able to access the tickets purchased by a certain
student number, so that also students who have forgotten or lost their phone can be
checked.

As one student can only buy one ticket per event, we can link every ticket that is created during
a purchasing process with the student’s identity, i.e. name and TUM ID). We can do this by
building the respective database partition for the tickets as a dictionary that maps the TUM ID
to the ticket, as TUM ID's are unique. In case a student forgot their ticket for the event,
cashiers can check the name on the government ID

**Comment by xsrf** [comment]
You already have access to the TUM-ID which also serves a greater audience. I don't see the need to associate event tickets with matriculation numbers.

**Comment by kordianbruck** [comment]
Nah, no need for matriculation numbers :+1:

**Comment by velev8** [comment]
Student ID was helpful to check on the students tum card in case they forgot their tiket. How will we verify the TUM-ID in case the perso  forgot their ticket/phone, doesnt have internet access etc.?

**Comment by kordianbruck** [comment]
@velev8 usually the Name is sufficient with a valid government issued ID, we can hand those out.

**Comment by velev8** [comment]
Please give Feedback for this Mockup

<img width="547" alt="screen shot 2018-06-22 at 15 50 16" src="https://user-images.githubusercontent.com/38428686/41781532-213a0a3e-7638-11e8-90a7-d5fa32462424.png">

**Comment by saileru** [comment]
Transferred to TicketCheck Repository 
Create Activity:
https://github.com/TCA-Team/TicketCheck/issues/5
Implement Search
https://github.com/TCA-Team/TicketCheck/issues/7
