### ISSUE TITLE
TicketSale: Pull to refresh for remaining tickets

### ISSUE THREAD

**Issue by velev8** [TCA-Team/TumCampusApp#920]
TS-Mi-3: As a student, I want to see how many tickets are still available for a certain
date, so that I know whether I should hurry.

The number of available tickets to buy via TCA is a very important info, that should therefore be shown both in the section of each event in the overview as well as the detail activity. This label should be updated via pull to refresh (especially interesting for quickly selling events, like Feuerzangenbowle etc.) by implementing an event listener to the database,
which is provided by the Firebase API.

**Comment by MeisterGig** [comment]
As a member of the TU-Film. I can tell you that having a Ticket Sale Counter for the Feuerzangenbowle is not feasible. Because the tickets are sold out in less than an hour after we start the ticket sale. To get a Ticket you probably need to cue up hours before.

**Comment by kordianbruck** [comment]
@MeisterGig the idea is to show the number of sold tickets through the campus app, not how many have sold in total. So it should technically be possible.

@velev8 lets simplify this issue to have only the requirement to display the number of tickets left. No need for overly complicated live updates and threading and all that. On a Pull to refresh, the values should be updated accordingly - that's it.

**Comment by velev8** [comment]
@kordianbruck updated

**Comment by velev8** [comment]
This is also a mockup for #896 

<img width="274" alt="screen shot 2018-06-26 at 15 45 48" src="https://user-images.githubusercontent.com/38428686/41916315-12ee03e0-7958-11e8-8d61-d840c4f3e0a6.png">

**Comment by saileru** [comment]
Looks great! 
I think we also need a button for adding the event to calendar in this view, right?

**Comment by kordianbruck** [comment]
@saileru we could just use the date/time thingy, once you tap that, it could prompt you accordingly.

**Comment by saileru** [comment]
I added a ticket to create the corresponding server API endpoint #967

**Comment by saileru** [comment]
Closed in #994
