### ISSUE TITLE
User stuck in TUM login

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#934]
## Steps to Reproduce

1. enter lrz id and click on next
2. in TUMonline: check 'aktiviert'
3. click on next in TumCampusApp

## Expected Result
after giving rights to the token a second click on 'next' in the app should accept the changes and move to the next screen

## Actual Result
app won't change the Toast error message even if we change the token permissions afterwards

**Comment by kordianbruck** [comment]
This is fixed with #791 as we no longer cache the error message but properly handle the error. A nicer UI message could be implemented in the future.
