### ISSUE TITLE
Access prints in the app

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/TumCampusApp#945]
Printing documents is a common use case for students, as they have to provide their certificate of enrollment for internship applications or to their insurance company. I suggest that we offer access to this functionality in the app. 

Users should be able to get a list of all available prints, select their preferred language and then open the generated PDF.

**Comment by pfent** [comment]
@thellmund you probably mean the "Ausdrucke für Studierende" / "Print Documents" in TUMonline

as with all things TUMonline: ping @xsrf

**Comment by thellmund** [comment]
Already learned that it would require a huge engineering effort. Given that this feature will not be used regularly, we can probably close this issue.

**Comment by psukys** [comment]
@thellmund no API endpoint from TUMOnline?

**Comment by kordianbruck** [comment]
@psukys no, unfortunately not.

**Comment by thellmund** [comment]
Closing this issue due to missing endpoint.
