### ISSUE TITLE
Integrating AnkiDroid: Learn Karten System

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#95]
Students of the Android Practical Course created the Android version of AnkiDroid some semesters ago. This might be a cool, new feature for the TCA and the introduction of a new chapter "Teaching/Research" in the TCA in general. Besides AnkiDroid, we might think about adding a survey feature, which is quite useful for all kinds of research works. Nevertheless this needs some further research itself (How to find participants? etc.).

Related links:
http://code.google.com/p/ankidroid/

**Comment by kordianbruck** [comment]
We started our own learn karten in #457 issue. Closing this for now.
