### ISSUE TITLE
Ticket Sale: Retrieve event duration from server

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#966]
Implement after #965 
Also add the event duration to all places where it is needed. Primarily the addToCalendar() method in EventDetailsFragment

**Comment by kordianbruck** [comment]
Instead, we opted to have a start & end datetime, which should better fit our needs for events.

**Comment by schulzalexander** [comment]
I opened a PR for this #976

**Comment by schulzalexander** [comment]
Done in #976
