### ISSUE TITLE
TUM Calendar: Titles not displayed correctly in some cases

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#970]
Event titles which include multiple upper case letters or numbers are not or not completely displayed in the calendar. For example, "TUNIX 2018" is not displayed at all.
e.g."abc", "Abc", "Ab Ab", "A-Ab" work correctly. Problems occur i.a. in the following examples:

## Steps to Reproduce

Create a new Event with one of the following names
"A" ->""
"A-A" ->"A"
"tunix 2018" -> "tunix"

![screenshot_20180707-161120](https://user-images.githubusercontent.com/12066533/42411700-6fc3f600-8200-11e8-8b08-d919c0e037ef.png)

**Comment by kordianbruck** [comment]
@thellmund I'm happy to just remove the code, it was a test and obviously the regex is just too broad.
