### ISSUE TITLE
Joda Time: Locale dependent formatting

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#972]
Currently, DateTimeUtils does not seem to consider Locale. The date format is statically specified as "yyyy-MM-dd HH:mm:ss"

It would be nice if the date formatting would be dynamically adjusted for the current Locale.

**Comment by pfent** [comment]
@saileru This is the ISO date time format and shouldn't be used for user facing strings.

Please use your own [DateTimeFormat](http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html), which can be customized for your needs.
I'd suggest starting with the formatting guidelines [in the docs](http://www.joda.org/joda-time/key_format.html), i.e. starting with `DateTimeFormat.mediumDate()`, or the appropriate variant thereof.
If you have special formatting needs, you can use pattern based formats using [`DateTimeFormat.forPattern()`](http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html#forPattern-java.lang.String-)

**Comment by saileru** [comment]
@pfent Ok, I see. Thak you for the clarification. 

However, wouldnt it be nice to provide some formatting functions for user facing strings in the DateTimeUtils as well?

**Comment by saileru** [comment]
@pfent I will implement the date formatting for user-facing strings in the ticket sale with your suggestions and then close this issue.

**Comment by schulzalexander** [comment]
This is included in PR #981
