### ISSUE TITLE
Refactor MVV API calls

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/TumCampusApp#977]
We’re currently using our `NetUtils` to call the MVV API. We should switch to Retrofit and use GSON to parse the result into `Departure` objects. This will help us streamline error handling and provide higher stability.

**Comment by kordianbruck** [comment]
Isn't it HTML that we parse in this case?

**Comment by thellmund** [comment]
Nope, it’s a JSON response (see `TransportController.getDeparturesFromExternal()`).

**Comment by kordianbruck** [comment]
Cool then. :dancer:

**Comment by pfent** [comment]
The EFA API can also provide XML output, if @thellmund rather want's to wrangle TickXML :wink: 

Should actually be not that much work, let's look at it on Friday

**Comment by thellmund** [comment]
TikXML 💕 

But beware of the phrase “Should actually be not that much work”, @pfent 😉
