### ISSUE TITLE
Get rid of data binding

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#987]
As we are primarily using kotlin extensions and they provide a much nicer syntax and seem less error prone than data binding, we should get rid of it for now.

I've done some work on the feature/ticketsale branch, but it ain't perfect. So either we remove the studycards, that primarily implement this, or we refactor this out. 

@thellmund what do you think?

**Comment by thellmund** [comment]
We’d have to do some serious refactoring to get the most out of data binding (e.g. provide actual view models for each entity that we display, for instance an ExamViewEntity that encapsulates all formatted data and that can simply be handed over to the view). For that reason, I think we should remove data binding for now and get back at it once the above-mentioned refactoring has been performed.

**Comment by pfent** [comment]
#973 got rid of data binding.
