### ISSUE TITLE
Ticket Sale: automatically delete outdated tickets

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#999]
This was one of the requirements in the SRS document. I am not completely sure if we still want this.

@kordianbruck Do you want us to implement this?

**Comment by kordianbruck** [comment]
Ehm, this is a server ticket - @schulzalexander 

Lets delete Tickets in a cron job, that runs every few minutes and deletes tickets older than a day that have not been yet payed.

**Comment by saileru** [comment]
@schulzalexander Isn't there already a server implementation for deleting reserved, unpayed tickets after a certain timespan?
I also meant deleting purchased tickets for past events from both the server and the local database. Maybe we want store them on the server a bit longer? On the client we could for now just automatically delete tickets which are older than e.g. one week. Later we could maybe add a function for manual deletion by the user.

**Comment by kordianbruck** [comment]
Implemented by @schulzalexander in the backend as a cronjob.
